### PR TITLE
BlockMoistureChangeEvent

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Comment by aikar** [comment]
min max to moistures?

**Comment by BillyGalbreath** [comment]
@aikar done

**Comment by molor** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/3e2858f6e680d43b85a760866df1fb4c1f9547b9?

**Comment by aikar** [comment]
Well Spigot actually beat you to this, and I do kind of like using block states over magic numbers, so closing.

**Pull request closed without merging**
