### PR TITLE
Limit hopper transfer to max. stack size of container.

### LINKED ISSUE #6329: Composter dont work like expected with bigger hopper
### Expected behavior

If for example 5 items get transported by an hopper that the composter manages them correctly.

### Observed/Actual behavior

If 5 items get pushed into a composter, it go only by 1 row higher, manually with hand it is 5 times faster so I believe the composter registers only 1 and not 5 items.

### Steps/models to reproduce

Hopper connected with a composter
Change paper config setting from 1 item per push to a higher level (the higher the clearer)
Look at the composter 

### Plugin list

No plugin

### Paper version

This server is running Paper version git-Paper-156 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d239eca)
You are running the latest version
Previous version: git-Paper-92 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_No response_

### PR DESCRIPTION
**Pull request by NoahvdAa**
This PR aims to temporarily fix # 6329 until the upstream issue is fixed. The patch checks if the item being moved is bigger than the max stack size of the container, if it is, the number of items transferred will be limited.

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Duplicate of #4838?

**Comment by NoahvdAa** [comment]
Not sure how I managed to miss that, closing this!

**Comment by Machine-Maker** [comment]
Could you test if that PR also fixes the issue that you opened this PR to address?

**Comment by NoahvdAa** [comment]
> Could you test if that PR also fixes the issue that you opened this PR to address?

Just checked, it does! The composter is filled one item at a time, as intended.

**Pull request closed without merging**
