### PR TITLE
Fixed large packet handling

### PR DESCRIPTION
**Pull request by lukalt**
Fixed handling of too large packets. This patch seems to got broken at some version update in the past.

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Owen1212055** [comment]
image
Does max size need to be adjusted?

**Comment by electronicboy** [comment]
was just looking deeper; yes, max size needs to be adjusted, that if statement down below actually needs to be moved up

**Comment by lukalt** [comment]
@Owen1212055 You're right. I actually did not see that the throwing of the PacketTooLargeException was moved further but down. I have updated the constant and removed the second check as it is obsolete now.

**Comment by electronicboy** [comment]
The second check was *the* check, this actually won't work right now, that if statement needs to be moved up

**Comment by electronicboy** [comment]
So, basically;
That check at the bottom is what was actually doing the size check, I was wrong in saying that this won't work, it will, just not for packets which are actually "skippable", which, is probably not an issue, but something we should probably restore the correctness of

I think that we should restore papers check, and remove mojangs

**Comment by lukalt** [comment]
Thanks! Looks good to me @electronicboy

**Pull request merged**
