### PR TITLE
Make debug dump file names consistent

### PR DESCRIPTION
**Pull request by powercasgamer**
before: 
image

after:
image

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Review by olijeffers0n — APPROVED** [review]

**Review by TheKodeToad — APPROVED** [review]
How could I possibly not?

(since the extra comments have been added, this isn't blind)

**Review by Owen1212055 — APPROVED** [review]
Let it cook for a couple days…

**Review by Lulu13022002 — COMMENTED** [review]
The syncloadinfo command has the same issue if i remember correctly

**Comment by olijeffers0n** [comment]
Let's see how many approvals we can get. Discord lurkers engage!

**Review by Astralchroma — APPROVED** [review]

**Comment by jpenilla** [comment]
Please do not encourage spam

**Review by Lulu13022002 — APPROVED** [review]

**Pull request merged**
