### PR TITLE
Prevent Vanilla Worldgen Deadlock

### LINKED ISSUE #4272: Vanilla WorldGen Lakes Deadlock
Vanilla appears to have a Deadlock risk here.

Lakes are looking for a structure, but structure escapes out of the RegionLimited world wrapper
This then hit some chunk that is still pending, but since main is blocked, itll never be not pending.

Full log from Zeffy here: https://paste.gg/p/anonymous/77db790e273446b3bedb58123725b337
```

[02:43:57] [Paper Watchdog Thread/ERROR]: ------------------------------
--
  | [02:43:57] [Paper Watchdog Thread/ERROR]: Current Thread: Server-Worker-2
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 	PID: 17 \| Suspended: false \| Native: false \| State: WAITING
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 	Stack:
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:476)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.World.getChunkAt(World.java:356)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.IWorldReader.getChunkAt(IWorldReader.java:100)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.StructureManager.a(StructureManager.java:27)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:2184)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.RegionLimitedWorldAccess.a(RegionLimitedWorldAccess.java:382)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenLakes.a(SourceFile:36)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenLakes.generate(SourceFile:18)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureConfigured.a(SourceFile:55)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureComposite.a(SourceFile:23)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureComposite$$Lambda$5582/1099215437.accept(Unknown Source)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)


```

### PR DESCRIPTION
**Pull request by MiniDigger**
fixes #4272

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
pretty sure the author of that one should be aikar cuz he mentioned the fix

**Comment by Chew** [comment]
> pretty sure the author of that one should be aikar cuz he mentioned the fix

Well if he mentioned the fix that means someone can do it, if Aikar likes it he can approve and merge it, I see this an absolute win!

**Review by aikar — DISMISSED** [review]
I don't care overall on author for such a tiny fix.

I've created a bug on mojira for this, https://bugs.mojang.com/browse/MC-199487
Can you update the patch for this in the ID/comment and also can you make slight improvement to move the getting wrapped structure manager to the ctor, store it, then access the wrapped manager by field so we don't churn new wrappers every request.

Good to go after that so pre-approving.

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
