### PR TITLE
Provide ComponentSerializer services

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Review by kashike — APPROVED** [review]

**Review by kezz — CHANGES_REQUESTED** [review]
This should probably also include a provider for MiniMessage as well, will just be a no-op for now but will be good to get in for future work with custom tags/etc.

Also, is it worth deprecating the entire `PaperComponents` class for removal at some point?

**Comment by Machine-Maker** [comment]
> Also, is it worth deprecating the entire PaperComponents class for removal at some point?

It's still valid to get the ComponentFlattener right? Unless there's no need anymore but I think there prob is.

**Comment by kezz** [comment]
Ah yeah, forgot about the flattener. I can't reaaallly see a use case for it, but it can't hurt to expose it I suppose?

**Comment by zml2008** [comment]
The flattener's useful for anyone trying to do custom serialization formats -- discord markdown, html, etc, where they need to lose the structure of different component types.

**Comment by kezz** [comment]
bad bot been approved

**Pull request merged**
