### PR TITLE
Mob Spawner API Enhancements

### LINKED ISSUE #1977: Setting a high delay in CreatureSpawner makes the number overflow
Setting a high number in CreatureSpawner#setDelay or min delay or max delay will break it and set it to a negative, firing the spawner rapidly. 

Code: https://i.imgur.com/MMuLwAv.png

Behavior:
a

Please note I am calling vanilla API, just using Boss for convenience testing.

### Plugin list:
Boss

### Paper build number:
621

### PR DESCRIPTION
**Pull request by BillyGalbreath**
This stores integer delay values in NBT as integers instead of shorts (fixes #1977)

Also adds more API methods for plugin use.

### CODE REVIEW

**Comment by wizjany** [comment]
Doesn't this mean the spawners are no longer valid in vanilla (or anything else for that matter)?

**Comment by BillyGalbreath** [comment]
~~@wizjany Only for the ones that set values beyond the scope of a short. Nothing else will change in that regard (99.99% of use-cases)~~

Fixed concern by keeping vanilla values around, but clamping them. Added new paper compound to hold true integer values

**Comment by electronicboy** [comment]
I was thinking of this, but ideally, we'd write to our own compound in there so that we can leave the vanilla values in place, otherwise vanilla would be broken when trying to versions stored in our change, was debating on default vs clipping

**Comment by kangarko** [comment]
That is excellent! Where can I donate? <3

**Pull request merged**
