### PR TITLE
Expose Command Dispatcher

### PR DESCRIPTION
**Pull request by MiniDigger**
Saves ppl who want to do stuff with brigadier from having to use reflection

### CODE REVIEW

**Comment by zachbr** [comment]
Glowstone and friends aren't going to like this.
Frankly, I'm not sure I'm in love with it either.

**Comment by MiniDigger** [comment]
brigadier is open source, if glowstone doesnt like this they can just throw unsupported operation exception I guess.

Aikar is working on different stuff, it will most likely make this unnecessary, so lets wait for that.

**Comment by A248** [comment]
I don't like this because it's too implementation-specific

**Comment by aikar** [comment]
Per our convo on discord, we don't want to just raw expose the entire dispatcher. 
We are going to be introducing a new way to access Brigadier stuff in a different manner here soon though.

**Pull request closed without merging**
