### PR TITLE
Reimplement world container in bukkit.yml

### PR DESCRIPTION
**Pull request by TheMolkaPL**
Reimplements world-container feature in the `bukkit.yml` file.

Related:
- https://hub.spigotmc.org/jira/browse/SPIGOT-5824
- https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7ea3c040bc4f1b400bc4749b76c87c6b8dd3dca7#src/main/java/org/bukkit/craftbukkit/CraftServer.java
- 75d9b04deb799589784c79d6fe3e690121b79473

### CODE REVIEW

**Comment by BillyGalbreath** [comment]
That's quite a big diff compared to #3873

**Comment by TheMolkaPL** [comment]
Yeah, I moved file loading to main and removed it from CraftServer. Your solution is simpler, but parses `bukkit.yml` twice.

**Comment by aikar** [comment]
I was gonna suggest this to billy, but this is now on the track.

Id rather see us init the configs at start, and just keep a static reference to them, and then where we current were init it, just pull from the static reference.

That'll keep diff low and not need to change all the signatures.

also removal in Main seems unnecessary. 

Kinda think these 2 PR's should be merged since both touching on same concept "we need config earlier"

**Comment by TheMolkaPL** [comment]
@aikar is this ready to be merged?

**Comment by aikar** [comment]
I merged billy's PR as this one was not implemented correctly for priority order of flag over config, and also decided against reusing the yaml object.

we cant init the configs earlier due to other stuff like loggers not being fully ready, so was just too much work.

**Pull request closed without merging**
