### PR TITLE
Add sendMiniMessage and sendPlainMessage methods

### PR DESCRIPTION
**Pull request by kennytv**
Not sure about any more in-depth docs there, but there we go, exemplifying how easy it is to use minimessage and at least providing one shorthand method for the most common usecase + having something separate from the legacy text accepting sendMessage method for plain text

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Do we care about minimessage or plain methods for actionBar messages? or just regular chat

**Comment by kennytv** [comment]
I'd only have it here before people start asking for that in even more places, just there to show it's easy

**Comment by imDaniX** [comment]
Calling it `sendMiniMessage` seems a bit obscure outside the context. Also, `MiniMessage` class itself is a serializer, not a message type - probably something like `sendMiniMessageMessage` would be more appropriate, but that's, well... you can see it yourself. Can't the method be called something like `sendRichMessage` instead?

**Comment by kennytv** [comment]
I like sendRichMessage more as well; any other opinions?

**Comment by Machine-Maker** [comment]
I like it as well, but sendRichMessage (removing association with MiniMessage from the method name) makes it seem official so I think this should be done when mini message becomes the official text representation. when configs and whatnot default to mini message.

**Comment by FawksX** [comment]
Any consideration to have the original `sendMessage`  undeprecated and use the LegacyComponentSerializer instead?

**Comment by Machine-Maker** [comment]
The original sendMessage isn't deprecated, but it will be at some point in the future

**Comment by kennytv** [comment]
Added in https://github.com/PaperMC/Paper/commit/09c9215b85b14be60c3a3dc22ea6f95d4b2615bb

**Pull request closed without merging**
