### PR TITLE
Cleanup and restructure the project

### PR DESCRIPTION
**Pull request by DenWav**
Also update Paperclip, as required for the build changes. All scripts have been moved to a `scripts` directory, with a single `paper` command which now handles all Paper building and patching. It also provides a set of new useful functions to enhance the shell. All CraftBukkit, Bukkit, Spigot, and BuildData stuff is now in the work directory, keeping the main directory clean.

### CODE REVIEW

**Comment by Gabscap** [comment]
How about replacing all `(...) || exit 1` constructions with `set -o errexit` at the top of the script?

**Comment by zachbr** [comment]
@TitanicFreak @Techcable being that you two are the odd men out on support of this PR, you should voice your concerns with it here, or else they may be ignored completely.

**Comment by Techcable** [comment]
My concern is a giant monolithic script, and moving the submodules into the 'work' directory.
You should be able to instantly see what version of each submodule you have
Also I just find giant monolithic scripts bad.

**Comment by DenWav** [comment]
@Techcable what giant monolithic script are you talking about? You're clearly seeing something wrong.

And the submodules aren't relevant to the project other than being the basis of what we patch. Our patches and the API and Server projects that come from it are the relevant parts, so they are placed on root. The rest is background noise and is moved to work/. If you want to see what versions of the other modules you are running, it's just in the work directory, it's not like it's suddenly hard to find.

**Comment by zachbr** [comment]
I'm not entirely sure 100 lines of bash counts as "giant" or "monolithic"

**Comment by DenWav** [comment]
@Gabscap can you clarify what you mean by that? What's the benefit?

**Comment by Gabscap** [comment]
The line `set -o errexit` tells the interpreter to exit the script with an exit code 1 if a single line has a exit code != 0. It makes bash scripts more robust by preventing further execution of a script if a command fails.
e.g. if you clone the repo and execute `./paper e server` it prints

```
$ ./paper e server
./paper: line 54: cd: <path_to_>/Paper/Paper-Server: file or directory not found
fatal: Needed a single revision
invalid upstream branch upstream/upstream
No stash found.
```

With `set -o errexit` the script fails before trying to rebase and stash the Paper dir, because it fails to cd into `Paper/Paper-Server`.
Scripts called from the paper script will not have the errexit-setting, so every script in `work/` should have errexit enabled.
Therefore `(...) || exit 1` would be rundundant, because errexit does this for every command.

**Comment by DenWav** [comment]
@Gabscap oh I see, that would be good. Added.

**Pull request merged**
