### PR TITLE
Correctly handle interactions with items on cooldown

### LINKED ISSUE #8005: Can't open doors while goat horn is cooling down
### Expected behavior

I expected the door to open and stay open.

### Observed/Actual behavior

The door opens momentarily before closing again.

### Steps/models to reproduce

Use a goat horn, while it's cooling down you can't interact with doors.

[Video](https://www.youtube.com/watch?v=Jc6cmLlKf98)

### Plugin and Datapack List

None.

### Paper version

This server is running Paper version git-Paper-24 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: dd61319)
You are running the latest version

### Other

_No response_

### PR DESCRIPTION
**Pull request by Machine-Maker**
This is a potential minefield, I tested the following situations:
* No PlayerInteractEvent changes: items on cooldown no longer prevent block interactions (can open a door)
* `PlayerInteractEvent.setUseItemInHand(DENY)`: block interactions don't happen when using the item and pressing shift

Fixes https://github.com/PaperMC/Paper/issues/8005

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by electronicboy** [comment]
This is somewhat of a behavioral change in regards to the API, so this is bleh all around, but, I can't really think of any sane alternatives here, so, approved (Also, note that I ci-skip'd the dupe patch numbers)

**Comment by Machine-Maker** [comment]
Well it was a significant behavioral break from vanilla. You couldn't open a door with an item that was on cooldown, which works totally fine in vanilla. Firing a PlayerInteractEvent with useClickedBlock set to DENY isn't new, it just shouldn't happen when the item in hand is on cooldown. The interaction isn't cancelled just cause an item is on cooldown, the useItemInHand is

**Comment by electronicboy** [comment]
Yea, that was my sthinking, the way that the event was being fired is just wrong, hence the fix; biggest minefield to me is at least the API side, but, I mean, I can't see any plugin expecting this to be the case, and there's no real other fix for this, so, it's got my vote

**Comment by Machine-Maker** [comment]
Rebased for 1.19.2

**Review by kennytv — APPROVED** [review]

**Pull request merged**
