### PR TITLE
Add server reload event for tracking when is the server reloading

### PR DESCRIPTION
**Pull request by TheMeinerLP**
Helps plugin developer to save data between reloads only

### CODE REVIEW

**Comment by molor** [comment]
Same as `ServerLoadEvent` w/ `LoadType.RELOAD`?

**Comment by TheMeinerLP** [comment]
Not really. The ServerLoadEvent is called after. But this one is called before. To tigger a save logic inside of plugins for like databases or disk save

**Comment by e-im** [comment]
Just `Server#isStopping` in `onDisable`?

**Review by Machine-Maker — CHANGES_REQUESTED** [review]
I think this event is redundant. As it was pointed out, the onDisable method in JavaPlugin is called on reloads and Server#isStopping returns false if it's a reload. Is there some usecase that that fact and the ServerLoadEvent doesn't cover?

**Comment by TheMeinerLP** [comment]
I have some cases that is not coverd. Also i miss a ServerStopEvent thats called before all Players kicked

**Comment by emilyy-dev** [comment]
During shutdown, Plugin#onDisable is called before players are kicked, and players aren't kicked on reload anyway

**Comment by Machine-Maker** [comment]
@TheMeinerLP can you be specific about what cases you believe aren't covered by existing events/onDisable? Otherwise I'm gonna close this as redundant.

**Pull request closed without merging**
