### PR TITLE
Remove old reduce debug info patch

### PR DESCRIPTION
**Pull request by Owen1212055**
This would resend the value when the client joined. It seemed that this was fixed a while ago, as removing this doesn't seem to change anything

### CODE REVIEW

**Review by Machine-Maker — APPROVED** [review]
Looking into how the client handles this now, it looks to be set in the ClientboundLoginPacket and the same thing would happen when sending the EntityEvent packet right after. So I think it is def redundant and can be removed.

**Comment by Owen1212055** [comment]
Rebased!

**Comment by Owen1212055** [comment]
Can someone remove this patch when dealing with 1.18?

**Comment by kennytv** [comment]
Done, thanks :p

**Pull request closed without merging**
