### PR TITLE
Fix ITEM_DROPPED stat not working properly

### LINKED ISSUE #6307: Scoreboard Dropped
### Expected behavior

I was making a vanilla system with a scoreboard that counts the number of times you dropped the item you chose (/scoreboard objectives add test minecraft.droppped:minecraft.lever)

### Observed/Actual behavior

Strangely, when I drop the item, it doesn't add me the point at each drop and stays at a score of 0

### Steps/models to reproduce

We create a scoreboard with the "criteria" minecraft.droppped:minecraft.lever (/scoreboard objectives add test minecraft.dropped:minecraft:lever) then we drop the item as the lever

### Plugin list

image

### Paper version

image

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_No response_

### PR DESCRIPTION
**Pull request by NoahvdAa**
This PR fixes #6307 and makes changes made in ItemDropEvent reflect in the ITEM_DROPPED stat.

### CODE REVIEW

**Review by Proximyst — APPROVED** [review]
Fixup with the patch that changed the behaviour for this

**Comment by NoahvdAa** [comment]
> Fixup with the patch that changed the behaviour for this

How do I do that?

**Comment by Proximyst** [comment]
Merger will take care of it for you :)

For the sake of answering regardless as no knowledge is too much… do an interactive rebase and move the commit under the one it fixes, and change it from pick to fixup.

**Comment by NoahvdAa** [comment]
> Merger will take care of it for you :)
> 
> 
> 
> For the sake of answering regardless as no knowledge is too much… do an interactive rebase and move the commit under the one it fixes, and change it from pick to fixup.

Thanks, would I need to do this for future PRs or would that be handled by the merger?

**Comment by Proximyst** [comment]
No worries about it, someone will usually point it out and it’s fairly trivial for a merger to do. A little annoying every so often, yes, but that’s just how it is 🤷🏻‍♀️

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
