### PR TITLE
removed duplicate ProjectileHitEvent for fireball

### LINKED ISSUE #4880: ProjectileHitEvent for Fireball is called twice
### What behaviour is expected:
When launching a Fireball using Player#launchProjectile(Fireball.class) and listening for hit events using ProjectileHitEvent, I expected to see the event fire only once for the one fireball.

### What behaviour is observed:
The ProjectileHitEvent is fired twice for a single Fireball hitting the ground.

### Steps/models to reproduce:
Launch a Fireball using Player#launchProjectile(Fireball.class) and listen for the event.

### Plugin list:
(my plugin, of course), Citizens, DiscordBotAPI, Essentials, EssentialsChat, LuckPerms, TAB, Vault, WorldEdit, WorldGuard

### Paper version:
git-Paper-322 (MC: 1.16.4) Implementing API version 1.16.4-R0.1-SNAPSHOT

### Anything else:
"SPAWNED FIREBALL" - printed when calling launchProjectile()
"projectile hit" - printed at the top of ProjectileHitEvent
"FIREBALL HIT" - printed when checking projectile instanceof Fireball and some other simple checks about the Fireball
"Fireball" - printing a list of nearby entities when the Fireball hits

I launched the Fireball using Fireball.class, not LargeFireball.class, so I do not understand why EntityLargeFireball shows up in this Stacktrace at all... Could this be the issue?

image

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes #4880

### CODE REVIEW

**Review by Proximyst — CHANGES_REQUESTED** [review]
What exactly was the reason this kept to begin with? I'm not sure we can do this at all.

**Comment by Machine-Maker** [comment]
Well I don’t know for sure, but aikar’s reasoning sounds solid. https://github.com/PaperMC/Paper/issues/4880#issuecomment-765505055

**Review by Proximyst — APPROVED** [review]
Rename patch to `Remove ProjectileHitEvent call when fireball is dead` and comment the original line instead of the modified one.

**Comment by Machine-Maker** [comment]
Done

**Review by Proximyst — APPROVED** [review]
Would be a shame if GitHub Actions blocked merge :Krappa:

**Comment by kennytv** [comment]
uhm, whoops

**Comment by electronicboy** [comment]
https://www.youtube.com/watch?v=wcnpZYmNAuI

**Pull request closed without merging**
