### PR TITLE
Drop carried item when player has disconnected (#5036)

### LINKED ISSUE #5036: Cancelling PlayerDropItemEvent deletes items on logout/kick etc.
### What behaviour is expected:
The item to go back into the player's inventory

### What behaviour is observed:
Item is completely deleted

### Steps/models to reproduce:
Cancel **PlayerDropItemEvent** then hold an item in your cursor then close MC or get kicked in anyway.
Normally the item in your cursor will get thrown on the floor when you leave the server but if you cancel the drop item it'll get deleted completely instead of being added back into the player's inventory like how the event handles it every other time.

### Plugin list:
Plugins (1): DevTest
A test plugin that just cancels the PlayerDropItemEvent 
    @EventHandler
    public void drop(PlayerDropItemEvent event) {
        event.setCancelled(true);
    }

### Paper version:
[22:48:31 INFO]: This server is running Paper version git-Paper-399 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[22:48:31 INFO]: Checking version, please wait...
[22:48:31 INFO]: You are running the latest version

### PR DESCRIPTION
**Pull request by JonMagon**
Comparison video:

https://user-images.githubusercontent.com/31476952/107112803-6cbc4800-686b-11eb-8e2f-e0fd51b7c724.mp4

```java
@EventHandler
public void drop(PlayerDropItemEvent event) {
    System.out.println("PlayerDropItemEvent is fired");
    event.setCancelled(true);
}
```

Fixes #5036

### CODE REVIEW

**Comment by HexedHero** [comment]
Thank you so much! This is great.

**Review by Proximyst — CHANGES_REQUESTED** [review]
Most definitely not. The drop event was cancelled, therefore we cannot drop it. The correct fix would be to add it to their inventory.

**Comment by JonMagon** [comment]
> Most definitely not. The drop event was cancelled, therefore we cannot drop it. The correct fix would be to add it to their inventory.

The item **will be added** to the inventory if the event is cancelled.

**Comment by Trigary** [comment]
There is no guarantee that there's free inventory space for the cursor-item: you can take the item into your cursor and then pick up items from the ground, filling your inventory. No clue how to handle this if dropping items is not an option (since the event can get canceled).

**Comment by JonMagon** [comment]
> There is no guarantee that there's free inventory space for the cursor-item: you can take the item into your cursor and then pick up items from the ground, filling your inventory. No clue how to handle this if dropping items is not an option (since the event can get canceled).

You're right, but it's definitely not linked to the 5036 issue. What you're talking about affects all situations when the PlayerDropItemEvent is cancelled, need to be fixed in `EntityHuman#a(ItemStack itemstack, boolean flag, boolean flag1)`

**Comment by electronicboy** [comment]
I'm not sure this actually fixes the issue as it's still calling `PlayerDropItemEvent` ?

**Comment by JonMagon** [comment]
Added demonstrative video to the first comment.

**Comment by Trigary** [comment]
@electronicboy Yes, the event is still called, but it's handled differently: if the event is cancelled the item is added to the inventory (instead of just disappearing, as it happens without this patch).

**Review by Trigary — APPROVED** [review]
Tested, works well. The `PlayerItemDropEvent` only gets called once, as it should; this patch did not introduce such a bug.

**Review by electronicboy — APPROVED** [review]

**Comment by electronicboy** [comment]
Planning to rebase this tomorrow™ I haven't slept yet time, unless somebody wants to get to that before moi

**Pull request merged**
