### PR TITLE
Add Sign#getInteractableSideFor

### LINKED ISSUE #9423: Player Interact Sign Event for Dyeing and Glowing
### Is your feature request related to a problem?

Using the existing logic of PlayerInteractEvent makes it incredibly complicated to determine which side of a sign the player interacted with, when using dyes or ink sacs. 

Issue #9293 / PR https://github.com/PaperMC/Paper/pull/9300 addressed a similar issue for the purposes of editing signs, but did not address this use case, and the original issue reporter even noted this use case in the PR before merging: https://github.com/PaperMC/Paper/pull/9300#issuecomment-1586080271

### Describe the solution you'd like.

A event that triggers when a player tries to dye a sign, or use an ink sac on it, with a way to get which side of the sign is being clicked.

### Describe alternatives you've considered.

As before with #9293, the only alternative I see is via NMS.

### Other

_No response_

### PR DESCRIPTION
**Pull request by Machine-Maker**
Adds API to get the specific Side of a sign that an entity, position, or coord pair is facing. Not 100% on the method name, so open to other options.

### CODE REVIEW

**Review by lynxplay — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Renamed method to `computeVisibleSide`.

**Comment by molor** [comment]
(why does adding all the new features that users most want (look at reactions) always take so long?)

**Comment by electronicboy** [comment]
Welcome to the joys of a hobby project, I currently do not have hardware/eyes to work on stuff right now either

**Comment by kennytv** [comment]
Why "compute"? Prefixing every method that computes something with compute would be silly and isn't too relevant to the user here (as opposed to something like getComputedBiome or computeIfAbsent). If it's to let users know they should put it into a local var instead of re-calling it multiple times, you should note that to the javadocs instead

**Comment by electronicboy** [comment]
It was the nicer name that we could come up out of the alternatives to getting this information

**Review by kennytv — APPROVED** [review]
Whatever name it may be, pre-approving anyways

**Comment by me4502** [comment]
Suggested in Discord, but how does `findSide` feel as a name? IMO it's less verbose and still gets the point across. It also still implies it's not a simple getter, but doesn't use the word compute

**Comment by Machine-Maker** [comment]
Hopefully the final rename to `getInteractableSideFor`. Its longer, but more accurate.

**Pull request merged**
