### PR TITLE
Make the GUI graph fancier

### PR DESCRIPTION
**Pull request by BillyGalbreath**
Fancy Graph :O

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Is it possible to make the console part of it user color codes as well?
Not a huge priority, just would add to the fancierness of this PR

**Comment by Puremin0rez** [comment]
> 
> 
> Is it possible to make the console part of it user color codes as well?
> Not a huge priority, just would add to the fancierness of this PR

Billy has actually already done that, but seemingly only the graph portion of his entire patch is what's being PR'd at this time.
Full patch: https://github.com/pl3xgaming/Purpur/blob/master/patches/server/0086-Make-the-GUI-better.patch

**Comment by BillyGalbreath** [comment]
Planned for future PRs ;) Still playing with things in my fork. Colors are something I think I can do better

**Comment by ShaneBeee** [comment]
Awesome :) Thanks for letting me know 👍

**Review by zachbr — APPROVED** [review]

**Pull request merged**
