### PR TITLE
Prevents nether portals from accepting portals built above the nether cei…

### LINKED ISSUE #7208: nether-ceiling-void-damage-height doesn't alter portal search
### Expected behavior

Portals made above the nether roof should not be considered as valid targets as they'll instant kill any player who travel to them when nether-ceiling-void-damage-height is set to the roof - it should try for a different portal instead

### Observed/Actual behavior

Player exits above roof, takes void damage, dies, and so do their items.

### Steps/models to reproduce

Build portal on roof, then set nether-ceiling-void-damage-height=128

### Plugin and Datapack List

NoCheatPlus
IllegalStack
BanItem
Pistonchat

### Paper version

[01:27:22 INFO]: This server is running Paper version git-Paper-400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ac995a on ver/1.17.1)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-398 (MC: 1.17.1)

### Other

_No response_

### PR DESCRIPTION
**Pull request by BigCrazyOfficial**
…ling as valid for teleporting entities

(hopefully) Fixes [#7208](https://github.com/PaperMC/Paper/issues/7208)

If a portal is built above the Y level specified under `nether-ceiling-void-damage-height`, entities can no longer enter the nether through that portal, even if no other options are available. Previously, it kind of just never checked this, which was simple enough to fix.

Tested by setting `nether-ceiling-void-damage-height` to 0, building a portal on the nether roof, returning to the overworld, building a portal in the proper location, setting `nether-ceiling-void-damage-height` to 128 and attempting to travel through it.

### CODE REVIEW

**Comment by kennytv** [comment]
Don't reformat code you don't change, as that makes the diff a lot larger/unreadable - even if having two if statements with the same indentation is going to look bad in code, we prefer that for the cleaner patch diff

**Comment by BigCrazyOfficial** [comment]
Alright, I'll look into it in a bit as IntelliJ is giving me issues. Apologies, as this is my first time contributing to a project that's not my own and I wasn't entirely clear on how I should be formatting my changes.

**Comment by kennytv** [comment]
No worries, the general gist is to simply have minimal diff. Sometimes it's easier to temporarily disable autoformatting, otherwise see the contributing guidelines on how to edit your patch

**Comment by BigCrazyOfficial** [comment]
I think this is what you meant, though I can't for the life of me figure out to to get rid of these two duplicate patches.

**Comment by Machine-Maker** [comment]
This was handled in #6986. It was marked as closing the same issue around 10 months ago. 

Also, tip for future PRs, don't open them from the master branch of your repo, create a new branch.

**Comment by BigCrazyOfficial** [comment]
Apologies: I was still able to reproduce it myself on a server running the latest version of Paper, so I figured it hadn't been fixed by then. 
I'll keep that in mind for the future, thanks.

**Comment by kennytv** [comment]
The PR machine linked wasn't merged until yesterday, it had just been sitting around for a longer while and I forgot to check for already existing prs linked to the issue, sorry about that

**Pull request closed without merging**
