### PR TITLE
Log when plugins register listeners for PlayerChatEvent

### PR DESCRIPTION
**Pull request by Spottedleaf**
Log when dum plugins register listeners for PlayerChatEvent

### CODE REVIEW

**Comment by prplz** [comment]
I don't like the comments

**Comment by 0-x-2-2** [comment]
@prplz kek

**Comment by AlfieC** [comment]
biased comment and retards won't understand so just throw an exception or something and then they will think it's an error and do something about it

**Comment by Spottedleaf** [comment]
Give a better comment and I'll update it with it

**Pull request closed without merging**
