### PR TITLE
Implement a new and improved in-memory UUID cache

### PR DESCRIPTION
**Pull request by Techcable**
With the new UUID API, plugins will be hitting the UserCache very heavily.
The UserCache has a number of disadvantages:
1. Not designed to be thread safe
   - Paper has modified the UserCache to be thread safe for the UUID API
     - Due to the delicate nature of thread-safety, this is likely to break without warning if mojang ever modifies the user cache
   - Even with mojang's changes the UserCache will lock on lookups, so if one thread is doing uuid-intensive work, it is likely to block other lookups
2. It only clears cache entries on exit.
   - If a plugin does a lot of UUID lookups, those entries will persist in memory until shutdown _even if not needed_
   - There is no limit to how large this map can grow, and it may even cause an OOME
3. It evicts entries based on when they were added, not when they were last used  - Commonly used entires may be evicted in favor of less commonly used entries _even though the entries are still valid_
4. The UserCache isn't transparent to calling code, and often isn't used
   - Mojang's internal UUID fetching API completly ignores the UserCache
   - Code must explicitly use the uuid api in order to benifit from the cache
   - Caches are reimplemented all around the codebase (for example in TileEntitySkull)

However this reimplementation:
1. Is designed to be thread safe
   - Will never break across updates, since its a complete reimplementation
   - Uses guava's Cache based on ConcurrentHashMap for fully concurrent reads and highly concurrent writes
2. Automatically clears cache entries
   - If a plugin does a lot of UUID lookups, the cache will intelligently cleanup  - Will automatically clear entries based on last access if low on memory
3. It evicts cache entries based on last access, not based on when they were first added
   - Commonly used entries will remain in the cache, while uncommonly uses entries will be cleared
   - Invalid entries will be removed as in the previous system
4. Transparent to calling code
   - The UserCache now wraps the new cache, so code will automatically use the new system
   - Mojang's internal UUID API now checks the new cache, so code will automatically check the new cache, and so now almost all code benifits from the cache
   - Caches all around the code base are unified into the new implementation
     - For example TileEntitySkull now uses the new cache instead of implementing its own

Requires #33

### CODE REVIEW

**Comment by Ichbinjoe** [comment]
i'm commenting without any knowledge of the commits you present, only from reading.

Do you have any plan for a user injectable cache layer? For example, a network may cache profile results in a redis, and want those to be used.

If not, thats fine :P I am simply wondering the scope of the commit.

**Comment by Techcable** [comment]
@Ichbinjoe 
The existing UUID API fires a PreProfileLookup event before looking up from mojang.
Networks could already hook into that api to cache requests for the UUID API.
However now with this commit NMS code that uses the UserCache (and even NMS code that doesn't use the UserCache) will also check redis (after checking the in-memory cache).

**Comment by minecrafter** [comment]
Instead of Guava, try [Caffeine](https://github.com/ben-manes/caffeine), which boasts higher performance and a lower memory footprint.

**Comment by Techcable** [comment]
@minecrafter 
Oh my god its the HikariCP of caches 😮

**Comment by aikar** [comment]
There is no need to add another cache library when we have Guava. 
If our cache library we use to help performance, becomes a performance problem, then we have serious other issues.

But for this PR, I'd love to see it decoupled from the Profile API. 

UUID cache is 1 component of the server
Profile lookup is another.

We can optimize them separately. 

UUID cache calls profile lookup, but ideally the profile lookup patch should hook into the same method the uuid cache calls. So ideally the callpoint in the uuid cache shouldn't need to be changed.

So if you can decouple this from the profile API, and make the patches independent of each other (which is a great thing to do when building the patches so that order and temporarily removing things doesn't cause such a nightmare of issues), then we could even get this one in before the profile API is finished.

**Comment by Techcable** [comment]
@aikar But its good to route it all though the profile API, since then if you change the profile lookup implementation, then all code will route through your implementation.

As for hooking it into the Profile API, it allows us to use the Profile API's existing infrastructure on the plugable implementation and provides a good test-case.

**Comment by SystemUpdate** [comment]
Nothing big, but was looking at the code and noticed a double space @ https://github.com/PaperMC/Paper/pull/309/commits/2eef99a0097774f1c5b95b95e8c09d86566b6f27#diff-554538027989f8d885814033f7bd345bR359

**Comment by AlfieC** [comment]
Why is this blocked?

**Comment by zachbr** [comment]
Depends on the Profile API in GH-33.
Not sure why that same commit is also here, but you can't merge this without the other.

**Comment by kashike** [comment]
Any update to this?

**Comment by kashike** [comment]
Feel free to open a new PR if/when you update this.

**Pull request closed without merging**
