### PR TITLE
Expose LivingEntity hurt direction

### PR DESCRIPTION
**Pull request by mikroskeem**
Helps implementing a cosmetical fix to https://bugs.mojang.com/browse/MC-26678

Example (for [DamageTilt mod](https://github.com/Charles445/DamageTilt)):
```kotlin
    @EventHandler
    fun on(event: EntityKnockbackByEntityEvent) {
        val victim = event.entity as? Player ?: return

        if (!victim.listeningPluginChannels.contains("damagetilt:attackedatyaw")) {
            return
        }

        // Send hurt direction
        victim.sendPluginMessage(plugin, "damagetilt:attackedatyaw", ByteArrayOutputStream().also { baos ->
            DataOutputStream(baos).also { dos ->
                dos.writeFloat(victim.getHurtDirection())
            }
        }.toByteArray())
    }
```

### CODE REVIEW

**Review by Proximyst — DISMISSED** [review]

**Comment by BillyGalbreath** [comment]
The client mod linked doesn't need server side assistance anymore. https://github.com/Charles445/DamageTilt/blob/master/src/main/java/com/charles445/damagetilt/HookEntity.java

**Comment by mikroskeem** [comment]
Hm, I only checked 1.16-fabric branch myself heh. Explains why I missed that.

**Comment by Titaniumtown** [comment]
Wait, so is this patch unncessisary then? Is this something that needs to be fixed client-side?

**Comment by BillyGalbreath** [comment]
> Wait, so is this patch unncessisary then? Is this something that needs to be fixed client-side?

it's something that can _only_ be fixed client side. The original mod required both client and server modifications (to send a packet like this PR is doing), but has been remade to not need that packet. Instead, it now uses the knockback direction to determine the tilt, which is a much cleaner fix that has no latency issues.

**Comment by Proximyst** [comment]
> Wait, so is this patch unncessisary then? Is this something that needs to be fixed client-side?

Unnecessary but not useless; having a little more useful API is not a bad thing.

**Comment by BillyGalbreath** [comment]
> Unnecessary but not useless; having a little more useful API is not a bad thing.

Just want to clarify that I agree with this. This added API is great, I just wanted to inform that the mod linked doesn't need it. Could definitely be used in other use-cases, though ^_^

**Review by MiniDigger — DISMISSED** [review]

**Review by electronicboy — DISMISSED** [review]
should maybe clarify more what the direction represents, is it a angle in degrees? etc

**Review by kashike — DISMISSED** [review]

**Comment by Proximyst** [comment]
@limbo-app ready

**Comment by Proximyst** [comment]
@limbo-app ready

**Comment by kashike** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
