### PR TITLE
i am no dumb taco hater

### PR DESCRIPTION
**Pull request by ramidzkh**
i am no dumb taco hater

### CODE REVIEW

**Review by Draycia — APPROVED** [review]

**Review by jacobsandersen — APPROVED** [review]

**Comment by MiniDigger** [comment]
> not editing the existing patch

**Comment by Draycia** [comment]
> not liking tacos

**Review by jacobsandersen — CHANGES_REQUESTED** [review]
While I'm happy that you are interested in making others aware of the taco-related legality that is implied by the use of Paper, I have to remind you that ignorance is not a defence of your dumb-taco-hater role. Dumb taco hater. That is, until you prove that you're not a dumb-taco-hater.

A quadruple dumb-taco-hater.

Also edit the existing patch.

**Comment by kennytv** [comment]
If you at least hadn't randomly thrown in a comma into that sentence

**Comment by DrkMatr1984** [comment]
I have no idea what just happened here

**Comment by ninja-** [comment]
Please don't merge this, I hate tacos

**Comment by sophuric** [comment]
:taco:s for life! :taco:s ftw! If you hate tacos, you're dumb.

**Pull request closed without merging**
