### PR TITLE
Optimise chunk BlockPosition queue

### PR DESCRIPTION
**Pull request by AlfieC**

### CODE REVIEW

**Comment by DenWav** [comment]
Please provide a more specific and helpful title to the patch.

Also this patch is silly and doesn't provide any real performance improvements.

**Review by kashike — CHANGES_REQUESTED** [review]
Please give the patch and pull request a better description.

**Comment by aikar** [comment]
Still a bad name, this is a Pending Tile Entity change type queue.

But what I suggest is to make one patch that collects all of these various inefficient queue processes and just make 1 "Optimize Inefficient Queue Processing"

Squash and the other PR's of yours into 1.

**Comment by aikar** [comment]
based on feedback with others, I don't think we need micro optimizations on this level unless it was extremely hot code and a known hotspot was because of this type of code.

changes like this add to the project maintenance. it's just not worth it for us.

**Pull request closed without merging**
