### PR TITLE
Fire entity knockback event for ownerless tnt

### LINKED ISSUE #7169: EntityKnockbackByEntityEvent not called if there's no source entity
### Expected behavior

The event should be called even if there is no source entity for a TNT or a projectile.

### Observed/Actual behavior

Its not called if there's no source entity.

### Steps/models to reproduce

1. /summon tnt
2. The event wasn't called

However, if player primes the TNT with a flint and steel, then it is called.

### Plugin and Datapack List

Only test plugin which debugs the event.

### Paper version

This server is running Paper version git-Paper-85 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: df8d28a)
You are running the latest version

### Other

Related: #7168

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes https://github.com/PaperMC/Paper/issues/7169

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Rebased for 1.18.2

**Review by Warriorrrr — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Rebased for 1.20.1

**Comment by YHDiamond** [comment]
Any idea when this will be merged? I'm relying on it for a project so if there is anything I could do to make it go faster please let me know.

**Comment by vLuckyyy** [comment]
> Any idea when this will be merged? I'm relying on it for a project so if there is anything I could do to make it go faster please let me know.

I think it would be great if we could get this merged. I have same problem with.

**Review by lynxplay — APPROVED** [review]

**Pull request merged**
