### PR TITLE
Add API to change friction and gravity for Arrows and its subclasses

### PR DESCRIPTION
**Pull request by TheShermanTanker**

### CODE REVIEW

**Comment by tomcraft** [comment]
Could this be applied to any Projectile or is there something that prevent that ?

**Comment by TheShermanTanker** [comment]
> 
> 
> Could this be applied to any Projectile or is there something that prevent that ?

As of now it only applies to Arrow-like entities, which means Arrows and Tridents. I did try to implement this API for other projectiles, but every single projectile has vastly different physics hooks and implementations, and some even disable physics (Enabling physics breaks their behaviour in weird ways), so unfortunately I couldn't do this for all the projectiles

**Comment by tomcraft** [comment]
Ok, was just curious. Is the tracking of a configured arrow still consistent ? If I remember correctly, arrow trajectory is computed client-side for rendering.

**Comment by TheShermanTanker** [comment]
> 
> 
> Ok, was just curious. Is the tracking of a configured arrow still consistent ? If I remember correctly, arrow trajectory is computed client-side for rendering.

From my experience with this the arrows are still accurate so long as they don't exceed a speed of 80 blocks per tick (m/s)- Normal arrows at their fastest usually fly at 60.3m/s so changing the gravity and friction shouldn't bother client side rendering too much since it doesn't directly set the arrow velocity

**Comment by Machine-Maker** [comment]
There a reason this was closed? Seems like a fine idea. I don't see it being saved/loaded on the entity anywhere tho.

**Pull request closed without merging**
