### PR TITLE
Add creative-arrow-despawn-rate

### PR DESCRIPTION
**Pull request by BillyGalbreath**
Adds #1393

### CODE REVIEW

**Comment by LuminousLoreBloom** [comment]
What about renaming patch https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0076-Configurable-Non-Player-Arrow-Despawn-Rate.patch#L35 to 'Configurable ~~Non Player~~ Arrow Despawn Rate' and popping this in there?.

Otherwise I think it fragments the project too much.

**Comment by BillyGalbreath** [comment]
@Mystiflow yeah, but ugh, effort. :s

**Comment by aikar** [comment]
yeah id rather merge this with the other patch.

**Comment by aikar** [comment]
@BillyGalbreath what was this closed for? if you want us to do the merging just say and we can.

**Comment by BillyGalbreath** [comment]
@aikar I didnt know ya'll could do that :O

**Comment by zachbr** [comment]
This was closed inadvertently as we moved branches around. Feel free to re-open this @BillyGalbreath.

my bad.

**Review by zachbr — APPROVED** [review]

**Review by aikar — APPROVED** [review]

**Pull request merged**
