### PR TITLE
Moved all the packages to the io.papermc group

### PR DESCRIPTION
**Pull request by toficzko**
This PR for sure requires a rebase for most of the other PRs

### CODE REVIEW

**Comment by NotMyFault** [comment]
👀 ❓

**Comment by tadhgboyle** [comment]
why?

**Comment by Proximyst** [comment]
Please start testing your PRs. We will not accept this at the current time, and will do this move ourselves when the time is right.

**Comment by toficzko** [comment]
> Please start testing your PRs. We will not accept this at the current time, and will do this move ourselves when the time is right.

It was tested , but it needs the remote repos like sonatype to be updated , the name of some pom’s mostly

**Pull request closed without merging**
