### PR TITLE
Fix PersistentDataContainer contract violation (_->!null returns null)

### LINKED ISSUE #3913: Block.getState(useSnapshot: false) breaks nullability contract for returned PDC
### What behaviour is expected:
When using `block.getState(false).getPersistentDataContainer()`, the returned value is not null.

### What behaviour is observed:
The returned value is null.

### Steps/models to reproduce:
Load this plugin: https://github.com/Prof-Bloodstone/PaperBlockStateSnapshotBug 

Jar (rename from .zip to .jar): [PaperBlockStateSnapshotBug-1.0-SNAPSHOT.zip](https://github.com/PaperMC/Paper/files/4927626/PaperBlockStateSnapshotBug-1.0-SNAPSHOT.zip)

`/give @s player_head`

Place player head on the floor.

The following messages will be shown:
```
[21:53:37 INFO]: Checking snapshot...
[21:53:37 INFO]: PDC is NOT NULL
[21:53:37 INFO]: Checking live state...
[21:53:37 INFO]: PDC is NULL
```

### Plugin list:
Just the one I linked.

### Paper build number:
```
[22:02:25 INFO]: This server is running Paper version git-Paper-91 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[22:02:25 INFO]: Checking version, please wait...
[22:02:25 INFO]: You are running the latest version
```

### PR DESCRIPTION
**Pull request by Proximyst**
Fixes #3913.

### CODE REVIEW

**Comment by Prof-Bloodstone** [comment]
Thanks for fixing it!

I don't have code in front of me, so I might be remembering something wrong. If I remember correctly, the `createSnapshot` method of CraftBlockEntityState also fills in the PDC with Bukkit NamespacedKeys and values (TEs `load` method iirc). That being said, I didn't see the exact path the data takes, which was the reason why I didn't fix it myself yet. Might have missed something really obvious though. 

I think the only difference I'd expect is that if I don't use the snapshot, all my changes are live immediately, without need for updating and remaining behavior should stay the same.

**Comment by Proximyst** [comment]
That is read from the `persistentDataContainer` field in the `TileEntity` class; if it's null, there are no values to copy, so no need to replicate that.

**Review by Prof-Bloodstone — DISMISSED** [review]
I've tested it with a bit more updated version of a plugin that was attached for reproduction in #3913 : https://github.com/Prof-Bloodstone/PaperBlockStateSnapshotBug

This patch causes PDC from snapshot and live PDC to differ, despite both being empty for some reason (`PDC.equals(other)` only compares 2 hashmaps, so I don't really know why).
```
[20:40:34 INFO]: Checking snapshot state...
[20:40:34 INFO]: PDC is NOT NULL
[20:40:34 INFO]: Checking live state...
[20:40:34 INFO]: PDC is NOT NULL
[20:40:34 INFO]: PDCs are not equal!
[20:40:34 INFO]: Snapshot is empty!
[20:40:34 INFO]: Live is empty!
```

That being said, I don't think causes any issues. All in all - LGTM.

**Comment by Proximyst** [comment]
They are in fact equal:
```java
        if (snapshotPDC.equals(livePDC)) {
            getServer().broadcastMessage("PDCs are not equal!");
        } else getServer().broadcastMessage("PDCs are equal!");
```
You messed up the check :p

**Comment by Prof-Bloodstone** [comment]
Oh, FFS. That's what happens when you refactor quickly ;)
All good!

**Review by aikar — DISMISSED** [review]

**Comment by Proximyst** [comment]
@limbo-app ready

**Review by aikar — DISMISSED** [review]

**Comment by Proximyst** [comment]
I hadn't pushed (nor rebuilt it seems...) the changes Leaf requested a while ago. Please re-review as the entire fix is different, @aikar.

**Review by aikar — APPROVED** [review]

**Pull request merged**
