### PR TITLE
Fix section symbols not working in logger

### PR DESCRIPTION
**Pull request by JRoy**
Fixes a regression in the hex pattern converter that caused a breaking change unintended before hard fork.

cc @broccolai @Spottedleaf

bcc @jpenilla

### CODE REVIEW

**Comment by jamespglines** [comment]
i already tryed this and they said no no no no no #7767

**Comment by jamespglines** [comment]
so not "unintended regression"

**Comment by JRoy** [comment]
> i already tryed this and they said no no no no no #7767

this fix comes from jmp and is better than your pr

**Comment by jamespglines** [comment]
on discord he sayd it is not accepted no matter how good the code. ik mine is bad when i look back. even w/ toggle.

gl

**Review by Spottedleaf — DISMISSED** [review]
flawless pr

**Review by mdcfe — APPROVED** [review]

**Review by rymiel — CHANGES_REQUESTED** [review]
working as intended

**Comment by JRoy** [comment]
@limbo-app ready

**Review by electronicboy — DISMISSED** [review]

**Pull request closed without merging**
