### PR TITLE
Feature/fix chat visibility

### LINKED ISSUE #8776: vanish "Chat message validation failure"
### Expected behavior

chat message

### Observed/Actual behavior

kick all players with reason "Chat message validation failure"

### Steps/models to reproduce

https://streamable.com/4odlkb

### Plugin and Datapack List

VanishNoPacket or EssentialsX

### Paper version

```
[17:55:27] [Server thread/INFO]: Checking version, please wait...
[17:55:27] [Thread-25/INFO]: This server is running Paper version git-Paper-372 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 214a8c5)
You are running the latest version
Previous version: git-Paper-363 (MC: 1.19.3)
```

### Other

I tested only EssentialsX and VanishNoPacket 
(probably a new reporting system xD)

### PR DESCRIPTION
**Pull request by CoreyShupe**
Aims to resolve #8776

### CODE REVIEW

**Review by NoahvdAa — CHANGES_REQUESTED** [review]
Needs Paper start and end comments. Not sure if this should be a separate patch or part of the adventure one.

**Comment by electronicboy** [comment]
Yea, I would imagine shove i tin the adventure patch, just for the sake of keeping all the chat system system changes and stuff together

**Review by electronicboy — APPROVED** [review]

**Review by NoahvdAa — APPROVED** [review]

**Comment by Bluzbur** [comment]
I use essentialsX (latest version) and attempted the new #375 download which said this was fixed, I just attempted on my server (Im on 1.19.2 optifine, my alt is 1.19.3 vanilla) and this issue still occurs. Am I missing something here? I can provide any information needed if you can't reproduce this issue.

**Comment by Bluzbur** [comment]
I believe this is just essentials vanish, I will test.

**Comment by Bluzbur** [comment]
Alright after doing some testing on a completely new server, it seems essentialsx (latest) kicks players off if I speak while vanished and supervanish does not, I'll see if essentials can fix anything on their end

**Comment by jurohn** [comment]
Can reproduce this error with latest paper with supervanish installed and essentialsx vanish disabled. Problem still excist.

**Pull request merged**
