### PR TITLE
[Untested] Use arrays instead of maps in the DataWatcher

### PR DESCRIPTION
**Pull request by Techcable**
Maps provide no benefit over arrays.
Arrays are much faster and more efficient than maps.
Removes locking, which is not an issue, as there are only some async reads (which are safe now that we use arrays).

Hardcoded to a length of 16, as thats all the length we need for 1.9.

### CODE REVIEW

**Comment by Techcable** [comment]
This is untested, yay!

**Comment by Zbob750** [comment]
I am under the impression that, as we all discussed in IRC, the solution @aikar proposed, and we merged in 017c6f73be6f5f65955dad8df36d354a054d7f38, was the best solution at hand. If you feel differently, and that more optimizations are needed, or that changes to that commit are necessary , please do not hesitate to contact me directly in IRC or open a new PR.

**Comment by zachbr** [comment]
This was not the right PR. I wanted to close PR #52

**Comment by zachbr** [comment]
Do we have stability/compatibility tests or any idea of the performance impact this will have? I don't recall discussing this much in IRC. Feel free to bug me there as well if you prefer.

**Comment by kashike** [comment]
:-1: from me. This just looks like a disaster waiting to happen with what people do.

**Comment by aikar** [comment]
For drastic, potentially game breaking changes like this, please least test and use on your server first.

**Comment by DenWav** [comment]
Necroing this, but I'm not convinced this has any real performance improvement over a map, other than just adding complexity.

**Comment by aikar** [comment]
Oh while it's not exactly as tech was going for, I made this obsolete by switching it to an Int2ObjectOpenHashMap. We can get gains by a 1 line diff and keep the same overall logic, avoiding risk of breaking NMS plugins.

So not really worth the risk this version adds.

**Pull request closed without merging**
