### PR TITLE
Don't use event to get block position

### LINKED ISSUE #9294: Placing powder snow bucket causes error
### Expected behavior

 *

### Observed/Actual behavior

[23:47:19 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseItem@23af9115, suppressing error
java.lang.NullPointerException: Cannot invoke "org.bukkit.event.block.BlockPlaceEvent.getBlock()" because "placeEvent" is null
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:517) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:596) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1957) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-3]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### Steps/models to reproduce

*

### Plugin and Datapack List

*

### Paper version

This server is running Paper version git-Paper-3 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: dc30ee5)

### Other

_No response_

### PR DESCRIPTION
**Pull request by Owen1212055**
Fixes https://github.com/PaperMC/Paper/issues/9294

Place event strikes again 😄

### CODE REVIEW

**Review by lynxplay — APPROVED** [review]

**Comment by CodeByCam** [comment]
LGTM :)

**Comment by lynxplay** [comment]
LGTM, glad you found a way without an AT :+1: :smiley:

**Comment by emilyy-dev** [comment]
there is an unneeded extra line in the diff, owen pls fix

**Review by Machine-Maker — APPROVED** [review]

**Comment by UnknownAMD** [comment]
What known bugs are there for 1.20?

**Pull request merged**
