### PR TITLE
Add config option for spider worldborder climbing

### LINKED ISSUE #6440: Config for disable Spiders to climb in WorldBorder
### Is your feature request related to a problem?

Currently if i wanna make a "Arena" for kill mobs i have the issue where the spiders start to climp the worldborder and hidden in max Y.

### Describe the solution you'd like.

A config in paper for disable spiders (not sure if another mobs can make this) to climp the worldborder

### Describe alternatives you've considered.

Using plugin for run when a spider is in the worldborder and change direction or teleport to ground.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

In vanilla happen the same issue with spiders... spiders are cowards for hide in the worldborder...

### PR DESCRIPTION
**Pull request by NoahvdAa**
Implements #6440.

---
Download the paperclip jar for this pull request: [paper-6448.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/487829237.zip)

### CODE REVIEW

**Comment by Doc94** [comment]
Nice, thanks for this. (This can close #6440 )

Question.. this work in cave spiders not by extends class not?

**Comment by NoahvdAa** [comment]
Cave spiders extend Spider, so this also effects them

**Review by kennytv — APPROVED** [review]

**Review by MiniDigger — APPROVED** [review]
lgtm

please attach a PR to the docs repo that documents this new option

**Comment by NoahvdAa** [comment]
I don't think I can link this as I don't have write perms, pr is at PaperMC/PaperDocs#105

**Review by kennytv — DISMISSED** [review]
Wait no, this just disables collision with the worldborder for spiders outright 🦧

**Comment by NoahvdAa** [comment]
I've gone and changed the logic so that spiders won't be set to the climbing state when the only thing they horizontally collide with is the border (and if allow-spiders-to-climb-worldborder is set to false, of course). Not entirely sure if this is the best solution, but this seemed like the easiest and most maintainable way of implementing this.

**Comment by NoahvdAa** [comment]
Rebased, Tuinity merge made this a lot easier.

**Comment by Doc94** [comment]
i still need this bot e.e

**Comment by BillyGalbreath** [comment]
I made a [cleaner solution](https://github.com/PurpurMC/Purpur/commit/1f2d9788a74e6483779346326ee9ccaa110a2605) that still prevents spiders from escaping the world border like normal ;)

[Option to prevent spiders from climbing world border](https://youtu.be/ccIDCe7Pj9Y)

**Comment by Doc94** [comment]
F?

**Comment by electronicboy** [comment]
This should probably be shoved under the game mechanics section

**Comment by Doc94** [comment]
Ey.. Stale i still wanna this PR for avoid teleport spiders...

**Comment by NoahvdAa** [comment]
Rebased and updated to use @BillyGalbreath's solution

**Review by Owen1212055 — APPROVED** [review]

**Comment by Owen1212055** [comment]
Can you open a new documentation PR for this?

**Review by Owen1212055 — APPROVED** [review]

**Pull request merged**
