### PR TITLE
Add Material Tag for Buttons

### PR DESCRIPTION
**Pull request by HexedHero**
Useful for checking if a player interacted with a button etc.

Also adds an un-added comment for the COLORABLE material tag with a removal of a random empty line and line with spaces when no others do.

### CODE REVIEW

**Review by MiniDigger — APPROVED** [review]

**Comment by Trigary** [comment]
Does this button tag differ from `org.bukkit.Tag.BUTTONS`? I would consider adding the answer to the JavaDocs.

**Comment by MiniDigger** [comment]
good catch! those are the same, and vanilla even has WODDEN_BUTTONS too, so this isn't needed.

thanks for the contribution anyways @HexedHero

**Comment by MiniDigger** [comment]
actually, since you had the javadoc line, if you wanna remove the buttons and reopen, we can get that in.

**Comment by HexedHero** [comment]
> actually, since you had the javadoc line, if you wanna remove the buttons and reopen, we can get that in.

#5376

**Pull request closed without merging**
