### PR TITLE
Revert Block Change Packet API

### PR DESCRIPTION
**Pull request by MrFrydae**

### CODE REVIEW

**Comment by egg82** [comment]
Not sure about the use-case for this (since you can just re-send the correct block) but what about multi-block changes? Generally more efficient to send one of those than many single block changes.

Also, yes, what's the use-case? You can already simply re-send the "correct" block using the existing API.

**Comment by MrFrydae** [comment]
This way, you don’t need to know what the “correct” block is. It just grabs the actual block from the location and sends that one. 

I don’t really have a specific use-case for this, but I just thought that this way would be simpler that having to manually tell the server what block to revert back to, when the server can just do it for you.

**Comment by electronicboy** [comment]
There is some level of legitness in such a PR, but I only really find that to be relevant if TE data was resent, some blocks wouldn't work as expected from what bukkit provides, e.g. signs

**Comment by Spottedleaf** [comment]
sounds like we should add a send state with blockstate too then

**Pull request closed without merging**
