### PR TITLE
Expose PotionEffectType Display Name

### PR DESCRIPTION
**Pull request by tahmid-23**

### CODE REVIEW

**Review by lynxplay — CHANGES_REQUESTED** [review]
This should really just implement adventures `Translatable`.
https://github.com/PaperMC/Paper/pull/6248 implemented this for a bunch of other types, I don't see why potion effect type should use a different method that directly returns the translatable component.

**Comment by tahmid-23** [comment]
ah ok I did not know about that interface

**Comment by Machine-Maker** [comment]
In fact, my PR #5737 does just that, implements Translatable

**Comment by tahmid-23** [comment]
okay didn't see

**Pull request closed without merging**
