### PR TITLE
Prevent wither skulls from using portals

### LINKED ISSUE #4241: Wither projectiles traveling through bedrock from the end to spawn
### What behaviour is expected:
Wither projectile skulls stay and explode in the end when the wither is trapped in the center bedrock block of the portal such as in vanilla.

### What behaviour is observed:
When attacking the wither the projectile skulls can travel through the portal to spawn and destroy the surroundings.

### Steps/models to reproduce:
Create a wither in the end under the portal so that it's main head is in the center bedrock. Attack it and randomly the projectile skulls travel through the portal to spawn.

### Plugin list:
No plugins

### Paper version:
This server is running Paper version git-Paper-158 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
I discovered this on a server running git-Paper-147 (MC: 1.16.2). So I then tested on my servers running git-Paper-158 (MC: 1.16.2)
Also have tested this on my 1.16.2 vanilla server and cannot recreate this issue.

In the pictures, left half is the end and right half is spawn. I had set mobGriefing to false so as to not destroy spawn for the pictures.  Attacks from players have the same results as attacks from iron golems.

Screenshot from 2020-08-28 19-59-02
Screenshot from 2020-08-28 19-59-46

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4241

### CODE REVIEW

**Comment by lynxplay** [comment]
This *feels* like it should be fixed in whatever is breaking the collision checks no?
Not sure how well that would play with vanilla behaviour.
At least this would need some config option to re-enable this behaviour for whatever maniac uses wither skulls travelling through portals.

**Comment by JRoy** [comment]
> This *feels* like it should be fixed in whatever is breaking the collision checks no?
> Not sure how well that would play with vanilla behaviour.
> At least this would need some config option to re-enable this behaviour for whatever maniac uses wither skulls travelling through portals.

Having the possibility for a random wither skull being teleported to the world spawn feels like something that shouldn't happen period lmfao

**Comment by Owen1212055** [comment]
I mean, wouldn't this logic also apply to other projectiles? If a separate "prevent projectiles using end portals" config was added that would make sense, but, this is a bit of a behavior change that doesn't fix whatever the core issue actually is that may be causing this.

**Review by YanisBft — APPROVED** [review]

**Comment by Owen1212055** [comment]
Closing, in the general, is just a work around and I feel that just blindly disabling wither skulls from being able to use portals it not the valid solution here. This is in general most likely caused by the collision optimizations that paper does.

**Pull request closed without merging**
