### PR TITLE
Performance boost

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Review by Redned235 — APPROVED** [review]

**Review by ChrystiGalbreath — APPROVED** [review]

**Review by Spottedleaf — APPROVED** [review]
Amazing work! 20 tps finally!

**Review by HexedHero — APPROVED** [review]

**Review by Draycia — APPROVED** [review]

**Review by jacobsandersen — APPROVED** [review]
I have 60tps now. wow

**Comment by Draycia** [comment]
Surber teps is ovar 9000!!!!1

**Comment by ghost** [comment]
bruhhh lmfao

**Comment by LB45440078L** [comment]
Now the tps are too big for pls fix

**Comment by Aaron2550** [comment]
@TheViperShow at least not too big for a long, most methods only take ints sadly

**Comment by TheRobLP** [comment]
I approve too, even tough I cant klick a button to do so :D . But really, I dont think anyone would miss the reload command. It is too dangerous to use anyways, if you plan on using plugins. Trust me I know what Im talking about. I litterally broke a whole server once because I did /reload (luckily I make backups :P)

**Review by kennytv — CHANGES_REQUESTED** [review]
7/10 not enough red, bold messages and explosions

**Comment by krusic22** [comment]
Speed merge this.

**Comment by HexedHero** [comment]
We're all meme'ing but I feel like this should be a thing lmfao or at least a config setting with it disabled by default

**Comment by BillyGalbreath** [comment]
> We're all meme'ing

I'm not.

**Comment by krusic22** [comment]
I know Shev would kill for this to be merged. Same goes for me. People reloading with protocol hacks installed.

**Comment by Draycia** [comment]
I absolutely never meme. I am serious 100% of the time.

**Review by RikoDEV — APPROVED** [review]

**Comment by electronicboy** [comment]
While this PR does offer some massive performance gains in specific (hopefully) edge-case scenarios, I believe that it's not suitable for the project as a whole

**Comment by allbombson** [comment]
lame

**Pull request closed without merging**
