### PR TITLE
Remove choice on zero-tick farms

### PR DESCRIPTION
**Pull request by Proximyst**
Remove the choice from the zero-tick farm fix.

Unsure how seriously this will actually be considered, but I personally think it
would be completely fair, especially with regards to the outcome of the
argument in #3544 resulting in no choice for the bug fix.

### CODE REVIEW

**Review by BillyGalbreath — APPROVED** [review]

**Comment by MissPotato** [comment]
I think it's time to change the FAQ's as well then. These are changes the players are going to notice, after all.

**Comment by zachbr** [comment]
1.16 will take care of this one for us soon enough.
Removing this with 1.16 so close and the current debacle would just be antagonistic.

**Comment by PreciseOXT** [comment]
Hi,
Why was this option removed?
What was the last build to still have the option?
Thanks in advance

**Comment by clrxbl** [comment]
mojang removed it in 1.16

**Comment by PreciseOXT** [comment]
> mojang removed it in 1.16

Alright, thanks mate 👌

**Pull request closed without merging**
