### PR TITLE
Add consumer parameter for spawning falling blocks

### PR DESCRIPTION
**Pull request by booky10**
Bukkit already has this consumer for spawning normal entities and dropping items, but the method for spawning falling blocks is missing it

### CODE REVIEW

**Comment by Malfrador** [comment]
I would personally prefer having a `setBlockData` method in `FallingBlock`, so that its possible to just use the existing consumer-based methods with FallingBlocks. 

FallingBlocks being the only entity that require a special spawning method in `World` is kinda weird, and the only reason for this is that they require BlockData to be spawned, which was impossible before the consumer methods existed.

**Comment by booky10** [comment]
Yeah, would make sense to add api for changing the blockstate.

But still, the falling block spawning method is the only one which doesn't have a consumer parameter. This seems like an inconsistency to me.

**Comment by Machine-Maker** [comment]
I agree with @Malfrador that a setBlockData method on FallingBlock is a better solution. I don't really like all the unique spawn methods for various things, Paper already has changes to make other entities work with the general spawn methods. Not sure we should be adding more.

**Comment by booky10** [comment]
So should I scrap the current PR and implement the proposed alternative solution?
Also, should the specific spawning-methods (for spawning falling blocks/dropping items) be deprecated/marked as obsolete?

**Comment by lynxplay** [comment]
If we manage to get a FallingBlock#setBlockData (or the likes) to properly work, then yea, we could mark the special spawning method as `@Obsolete` and link the proper methods.

I'd keep this branch around tho, if implementing the setBlockData method seems too troublesome/runs into client restrictions down the line, we might just have to fall back onto this proposal.

**Pull request closed without merging**
