### PR TITLE
Optimise DataWatcher

### PR DESCRIPTION
**Pull request by AlfieC**

### CODE REVIEW

**Comment by Spottedleaf** [comment]
Benefits of optimizing this vs maintaining this?

**Comment by AlfieC** [comment]
Well, if you review the code for Int2ObjectOpenHashMap, you'll see this is a lot faster and is only one array lookup per operation vs many.

Also, this patch will likely be built upon by a friend of mine soon, making the DataWatcher lockless. For now, this is an improvement but the more substantial gains will follow.

**Comment by Spottedleaf** [comment]
I know what this optimization does. My original question asks you to explain why it's worth paper's time to accept & maintain this patch.

**Comment by AlfieC** [comment]
Because it is of very little effort to maintain this patch. The benefits outweigh the drawbacks - this alone speeds up DataWatcher lookups and more will come.

**Review by prplz — CHANGES_REQUESTED** [review]
https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/wrappers/WrappedDataWatcher.java breaks

**Comment by AlfieC** [comment]
Do not accept in current state.

It has been pointed out to me that ProtocolLib uses reflection to get the map. In order to rectify this, I will have to "wrap" the array with a class that implements Map.

**Comment by zachbr** [comment]
While you're at it, rename the patch file something more specific please.

**Comment by aikar** [comment]
We already have a patch optimizing this to the FastUtil map... This is a patch replacing one of our patches...

I don't think the benefit is worth the added diff vs what the simple FastUtil swap provides us.

Would need to see benchmarks of cost of method and improvements.

**Comment by Techcable** [comment]
Since data watcher ids are now guaranteed to be sequentially increasing, it would come at no memory cost to use a plain array to store values and directly index them.
This may provide a noticeable speed increase, but we could increase it even more by eliminating the read locking.
Currently, the datawatcher uses a [ReadWriteLock](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReadWriteLock.html) to make the datawatcher thread-safe.
Although this is less contented than a synchronized block, it still has a lot of overhead on reads (much more so then a hash map).
If we switch to arrays, we could safely use an [atomic array](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicReferenceArray.html), resorting to a lock only to protect write-access.
This comes at almost zero overhead for reads, and may even improve write performance since traditional locking is so optimized compared to.
However, this could cause some minor concurrency issues with readers seeing inconsistent state, so it should probably be hidden behind a flag and be extensively tested.

**Comment by AlfieC** [comment]
No, an atomic array does not need to be used at all. I may PR a lockless version if I am able - I've been using it for months without a problem.

**Comment by Techcable** [comment]
How else would threads be guaranteed to see updates from each other? The updates aren't guaranteed to occur without a memory barrier.

**Comment by AlfieC** [comment]
Yes, not "guaranteed' to occur but in this instance they simply do not. The updates only occur from the main thread & are read from the netty threads iirc - in my months of running a lockless and a simple array based DataWatcher I have faced no issues at all. In your version of it you really overcomplicated it - there are only 3 packets (in my version at least) that read from the DataWatcher asynchronously and as such all that is needed is for those three packet classes to be imported, and the reading from the DataWatcher done synchronously in packet construction to avoid any potential concurrency issues.

**Comment by kashike** [comment]
Do we want this, @PaperMC/paper-push?

**Pull request closed without merging**
