### PR TITLE
Optimize CraftPlayer#invertedVisibilityEntities

### PR DESCRIPTION
**Pull request by Gerrygames**
Tested on a lobby server with 20-40 players.
Before: https://i.imgur.com/hmUYRWX.png
After: https://i.imgur.com/OJkDvpN.png
containsKey is much faster

### CODE REVIEW

**Comment by Gerrygames** [comment]
> I'm sure this breaks the moment an entity changes its entity id. UUID is persistent, entity id can change, for example when a player respawns

The entity id of a player does not change (in one server session). It is only transmitted to the client in the ClientboundLoginPacket, not in the ClientboundRespawnPacket. The entity id of entities in the world will only change if they are unloaded and then loaded again, but this calls CraftPlayer#onEntityRemove which resets the visibility and is thus irrelevant.

**Comment by Gerrygames** [comment]
It looks like the entity id will change when changing dimensions. This does not apply to players but would still be a problem. Will do further analysis/testing.

**Comment by Spottedleaf** [comment]
You may have better luck optimising the function by using !isEmpty && containsKey instead of just containsKey.

**Comment by lynxplay** [comment]
Closing this as any larger improvements probably need some deep cuts into how the tracker handles "vanilla would track but CB doesn't" players.

**Pull request closed without merging**
