### PR TITLE
Modify offline mode warning to include Velocity line

### PR DESCRIPTION
**Pull request by mja00**
This adds a check to the offline-mode warning to see if Velocity is enabled. If it is enabled then it warns the user to make sure to secure their server and links to the Velocity documentation on that.

Attempt 2 since I had no idea about the branch name requirement.

### CODE REVIEW

**Review by NoahvdAa — CHANGES_REQUESTED** [review]
This should go into the [Velocity support patch](https://github.com/PaperMC/Paper/blob/18fabc08d52ecbddd993d17fb06c51db27941014/patches/server/0882-Add-Velocity-IP-Forwarding-Support.patch)

**Comment by mja00** [comment]
Time to figure out how to modify patches now. 👍🏻

**Comment by mja00** [comment]
I think I did it correctly lol

**Review by MiniDigger — APPROVED** [review]
that dos indeed look correct.
the branch requirement is so that the team can properly modify your branch, github prohibits that on master.

one thought I had is extracting the two variables (link and software) out so that the text isn't duplicated, but prolly not worth it so approving as it

**Review by NoahvdAa — APPROVED** [review]
lgtm

**Comment by Peter-Crawley** [comment]
I think if velocity forwarding + velocity online mode is enabled the warning should be hidden entirely

**Comment by electronicboy** [comment]
This message feels weird given that velocity forwarding is much more secure than bungees; I also wouldn't mind if velocity online mode was an info message instead of a warn

**Comment by Peter-Crawley** [comment]
tbh the existing message for bungeecord is kinda bad too, might be a good idea to clean that up a bit as well
i dont know if anyone wants suggestions for the wording or not though

**Comment by mja00** [comment]
If someone else figures out the wording I'd gladly swap it to that (I am not a wordsmith). Otherwise I can change up the if statement so we're not duplicating that one line and swap it to INFO if wanted.

**Comment by mja00** [comment]
This latest change should be what Mini was suggesting I believe. Definitely makes it cleaner. I'm not too sure how to go about swapping to using INFO if online-mode for velocity is enabled. It seems like we'd be duplicating a lot of lines for that. Unless we just change that message entirely.

**Review by Machine-Maker — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]

**Pull request merged**
