### PR TITLE
Handle exception on convert to api for locate structure

### PR DESCRIPTION
**Pull request by Owen1212055**

### CODE REVIEW

**Comment by Machine-Maker** [comment]
yeah.... idk if this is what we want. There are actually 2 missing structure types, and upstream specifically ignore the tests that they made to check this. I didn't add the api then because they are def gonna. and if they don't we can come back to it.

**Comment by Owen1212055** [comment]
> yeah.... idk if this is what we want. There are actually 2 missing structure types, and upstream specifically ignore the tests that they made to check this. I didn't add the api then because they are def gonna. and if they don't we can come back to it.

Should I just skip structures not supported by the api then?

**Review by Machine-Maker — CHANGES_REQUESTED** [review]
see my comment

**Comment by Machine-Maker** [comment]
> Should I just skip structures not supported by the api then?

Skip them where? tests? the tests have the `@Ignore` annotation so they don't run. I just wouldn't do this at all until some time has passed and upstream hasn't done it.

**Comment by Owen1212055** [comment]
image
See paper-contrib

**Comment by Owen1212055** [comment]
See now

**Comment by Machine-Maker** [comment]
Mmmm I think there's a better way. I'm refactoring PaperRegistry to support stuff like this in the future. to gracefully handle stuff like this in a more general fashion.

**Comment by Owen1212055** [comment]
Alrighty

**Pull request closed without merging**
