### PR TITLE
make class CraftMetaLeatherArmor public

### PR DESCRIPTION
**Pull request by rgnter**
Why on earth would meta class be package-private.

### CODE REVIEW

**Comment by electronicboy** [comment]
Because these classes are part of a system in which is designed to be self-contained, there is no reason for them to be public, they are not part of the API, etc

**Comment by rgnter** [comment]
how are you supposed to change color of leather armor item stack with current API?

**Comment by electronicboy** [comment]
https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/meta/LeatherArmorMeta.html#setColor-org.bukkit.Color-

**Comment by kezz** [comment]
> how are you supposed to change color of leather armor item stack with current API?

https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/meta/LeatherArmorMeta.html

**Pull request closed without merging**
