### PR TITLE
Updated the LICENSE file

### PR DESCRIPTION
**Pull request by NikNikovsky**
No, I didn't add myself since I made no code.

### CODE REVIEW

**Comment by kennytv** [comment]
There's *some* correct changes here, but a majority of the changes in your prs are wrong, so I'm closing them

**Comment by kennytv** [comment]
Well you created 3 prs that are basically just spam, that's on you, not Grammarly

**Comment by NikNikovsky** [comment]
not trying to make an argument out of this, but I did change some of the errors that were in there (text not code). If you see something that can be applied to the files I modified then modify them yourself.

**Comment by uvalubia** [comment]
thanks for using grammarly for us

**Comment by NikNikovsky** [comment]
i have no idea if this is an actual thank you or a sarcastic message.

**Pull request closed without merging**
