### PR TITLE
Fix duplicated BlockPistonRetractEvent call

### LINKED ISSUE #7110: Multiple BlockPistonRetractEvent are fired for a single piston pull
### Expected behavior

When pulling a block with a sticky piston, only one BlockPistonRetractEvent should be created and called.

### Observed/Actual behavior

**When pulling a block with a sticky piston, two BlockPistonRetractEvents are created and called.**

This does not happen, if the piston retracts without moving a block.

This does not happen when using the latest build of spigot, it only happens on paper.

This does not happen for BlockPistonExtendEvents

_This is an example of simply logging when an event is called after moving a block with a piston:
[19:21:16 INFO]: [PistonRetractEventTest] Piston retraction detected org.bukkit.event.block.BlockPistonRetractEvent@1a23fae5
[19:21:16 INFO]: [PistonRetractEventTest] Piston retraction detected org.bukkit.event.block.BlockPistonRetractEvent@5ab245e7_

### Steps/models to reproduce

- Listen to piston retraction events, simply log a message when they happen. 

- Place a sticky piston and a lever next to it,
- Extend the piston by using the lever
- Place a block next to the piston head
- You can even send a message or something to prove that the previous steps didn't produce any logs.
- Retract the piston by using the lever

--> Multiple piston retraction events will be created, fired, listened to, and logged.

### Plugin and Datapack List

The only plugin im using is a plugin that only prints out an error message each time a piston retract event is fired. The source is included in 'other'

### Paper version

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are running the latest version

### Other

This is the main class of the plugin:
```java
public class PistonRetractEventTest extends JavaPlugin {   
  @Override
  public void onEnable(){
    getServer().getPluginManager().registerEvents(new PistonRetractionListener(this), this);
  }

}
```
This is the listener
```java
public class PistonRetractionListener implements Listener {
  private Plugin plugin;

  public PistonRetractionListener(Plugin plugin){
    this.plugin = plugin;
  }
  
  @EventHandler
  public void onPistonRetraction(BlockPistonRetractEvent e){
    plugin.getLogger().info("Piston retraction detected " + e);
  }
  
}
```

### PR DESCRIPTION
**Pull request by Machine-Maker**
This fixes #7110 

Unsure which patch to put this in, but I know it belongs in some existing patch.

### CODE REVIEW

**Comment by lynxplay** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0718-Move-BlockPistonRetractEvent-to-fix-duplication.patch might do ?

**Comment by Happily-Coding** [comment]
> https://github.com/PaperMC/Paper/blob/master/patches/server/0718-Move-BlockPistonRetractEvent-to-fix-duplication.patch might do ?

No, i believe there was triplicate logging before and that reduced it to duplicate logging.

**Comment by lynxplay** [comment]
> > https://github.com/PaperMC/Paper/blob/master/patches/server/0718-Move-BlockPistonRetractEvent-to-fix-duplication.patch might do ?
> 
> No, i believe there was triplicate logging before and that reduced it to duplicate logging.

The only other patch that touches the event, at least from a quick search, would be https://github.com/PaperMC/Paper/blob/master/patches/server/0302-Fire-BlockPistonRetractEvent-for-all-empty-pistons.patch

**Comment by Machine-Maker** [comment]
> The only other patch that touches the event, at least from a quick search, would be master/patches/server/0302-Fire-BlockPistonRetractEvent-for-all-empty-pistons.patch

I think this patch caused part of the issue, the other patch fixed some and this one fixes the rest. frankly, I think they should all 3 be merged into the same patch. Some "Fix BlockPistonRetractEvent for sticky pistons" patch.

**Comment by lynxplay** [comment]
> I think they should all 3 be merged into the same patch

Probably best yea, else we are just adding patches after patches trying to fix the previous patch :sweat:

**Comment by Machine-Maker** [comment]
Ok, I merged them all into one patch.

**Review by Owen1212055 — APPROVED** [review]
BEFORE:
```
[02:31:53 WARN]: java.lang.NullPointerException
[02:31:53 WARN]: 	at test-plugin-1.0.0-SNAPSHOT.jar//io.papermc.paper.testplugin.TestPlugin.on(TestPlugin.java:17)
[02:31:53 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
[02:31:53 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[02:31:53 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:31:53 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:31:53 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:31:53 WARN]: 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:242)
[02:31:53 WARN]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:912)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1673)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1659)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:629)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
[02:31:53 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[02:31:53 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:31:53 WARN]: java.lang.NullPointerException
[02:31:53 WARN]: 	at test-plugin-1.0.0-SNAPSHOT.jar//io.papermc.paper.testplugin.TestPlugin.on(TestPlugin.java:17)
[02:31:53 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
[02:31:53 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[02:31:53 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:31:53 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:31:53 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:31:53 WARN]: 	at net.minecraft.world.level.block.piston.PistonBaseBlock.moveBlocks(PistonBaseBlock.java:388)
[02:31:53 WARN]: 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:272)
[02:31:53 WARN]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:912)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1673)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1659)
[02:31:53 WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:629)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
[02:31:53 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
[02:31:53 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[02:31:53 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
AFTER:
```
[02:34:13 WARN]: java.lang.NullPointerException
[02:34:13 WARN]: 	at test-plugin-1.0.0-SNAPSHOT.jar//io.papermc.paper.testplugin.TestPlugin.on(TestPlugin.java:17)
[02:34:13 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
[02:34:13 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[02:34:13 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:34:13 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:34:13 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:34:13 WARN]: 	at net.minecraft.world.level.block.piston.PistonBaseBlock.moveBlocks(PistonBaseBlock.java:400)
[02:34:13 WARN]: 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:275)
[02:34:13 WARN]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:912)
[02:34:13 WARN]: 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1673)
[02:34:13 WARN]: 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1659)
[02:34:13 WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:629)
[02:34:13 WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
[02:34:13 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
[02:34:13 WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
[02:34:13 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
[02:34:13 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[02:34:13 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Looks good!!

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
