### PR TITLE
consider enchants for destroy speed

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Comment by HexedHero** [comment]
I thought the API was only to get the blocks destroy speed and not consider whatever the player has, can't plugins do this check themself instead of breaking usage for just getting the blocks destroy speed of `that` block?

**Comment by Machine-Maker** [comment]
But this doesn't really have anything to do with the player. its just an itemstack which can be from a player or not.

**Comment by MrIvanPlays** [comment]
i feel like this should be done in a major release. because like now it returns 1 value, but after this gets merged it returns another value. this will probably break some plugins

**Comment by Machine-Maker** [comment]
I mean... I'd argue it was *bugged* before, and this is a fix. But yeah, idk.

**Review by Proximyst — CHANGES_REQUESTED** [review]
Definitely a hard no to breaking existing API on purpose: create a new method that take these changes as parameters and have the old just return new with new changes disabled.

**Comment by HexedHero** [comment]
Love the updated version

**Review by Proximyst — APPROVED** [review]

**Pull request merged**
