### PR TITLE
Re-add shear methods from bukkit Shearable

### LINKED ISSUE #11638: Sheep/Bogged/Snowman "regrow wool/mushroom/pumpkin" methods
### Is your feature request related to a problem?

With the deprecation of the bukkit `Shearable` API, we lost the ability to force regrow wool or mushrooms for sheep and bogged or "un-derp" snow golems

### Describe the solution you'd like.

Methods for those entities to regrow their "features"

### Describe alternatives you've considered.

Using the deprecated and marked for removal API from Bukkit

### Other

_No response_

### PR DESCRIPTION
**Pull request by HaHaWTH**
This pull request closes #11638.

### Changes made

Readd shear related methods to Sheep and Bogged from bukkit Shearable.

This is my first PR to Paper, sorry if i did something wrong.

### CODE REVIEW

**Comment by electronicboy** [comment]
We should expose what "sheared" represents, rather then just expanding the usage of flawed API; (and that should be added to the existing entity API patch)

**Comment by HaHaWTH** [comment]
> We should expose what "sheared" represents, rather then just expanding the usage of flawed API; (and that should be added to the existing entity API patch)

Thanks for explanation! Should I add this to Missing Entity API patch?

**Comment by electronicboy** [comment]
Yes

**Comment by electronicboy** [comment]
Oh, actually, both of them called the internal data shreared, so, this is fine; Snowmen already have their "derp"'d methods

**Pull request closed without merging**
