### PR TITLE
per world spawn limits

### LINKED ISSUE #2910: Add spawn-limits as per-world option
**Is your feature request related to a problem? Please describe.**
I don't want to see so many mobs in nether or in the end, but I can't deal with it without some third-party plugins.

**Describe the solution you'd like**
spawn-limits section(like in bukkit.yml) in world-settings section(paper.yml).

**Describe alternatives you've considered**
Do nothing.

### PR DESCRIPTION
**Pull request by Machine-Maker**
closes #2910

Taken from #2982

### CODE REVIEW

**Review by MiniDigger — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Oh stalebot, when will you learn?

**Comment by Machine-Maker** [comment]
`Rebased after the NMS repackage`

**Comment by Strahilchu** [comment]
Any progress?

**Review by electronicboy — APPROVED** [review]

**Review by kennytv — APPROVED** [review]
Pufferfish Seal of Approval
pufferfish

**Pull request merged**
