### PR TITLE
Added world settings for mobs picking up loot

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Review by MiniDigger — DISMISSED** [review]
not sure if we want a OBF helper for `difficultydamagescaler.d()` here (would be used in both checks), but looks good

**Review by Proximyst — DISMISSED** [review]
No obfhelper should be necessary :)

**Review by zachbr — DISMISSED** [review]

**Comment by Proximyst** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
