### PR TITLE
Fix player Y level on login

### LINKED ISSUE #6357: Player teleported back to Y level 257 when logged out above 300
### Expected behavior

Players should be at the same location when logging in as where they logged out.

### Observed/Actual behavior

When logging out with a position above Y level 300, the player is set back to Y level 257.

### Steps/models to reproduce

1. Log in to the server running paper software (tested on build 165)
2. Go to a location above Y level 300
3. Log out
4. Log back in
5. You will now be at Y level 257

### Plugin list

None

### Paper version

> version
[17:14:01 INFO]: Checking version, please wait...
[17:14:01 INFO]: This server is running Paper version git-Paper-165 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f261419)
You are running the latest version
Previous version: git-Paper-154 (MC: 1.17.1)
>

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This works correctly on the vanilla server

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes #6357

### CODE REVIEW

**Comment by electronicboy** [comment]
Doesn't look like the player is in the correct world at that point?

**Review by lynxplay — APPROVED** [review]

**Comment by lynxplay** [comment]
Oh yea, cat is right, the player only is assigned the level they are in, in PlayerList#placeNewPlayer (l235).

----

EDIT: To be honest, this entire logic block might fit better into the `placeNewPlayer` call anyway, concerning that logic like the fudgeSpawningLocation already resides there as well.

----

EDIT2: I am hitting all the wrong buttons, ignore my review clickings.

----

EDIT3: Probably didn't throw an NPE because players default to the overworld level when created 👌

**Comment by Machine-Maker** [comment]
Yeah, I knew the `ServerLevel` was a part of the `ServerPlayer` constructor but I didn't know that it just defaulted to the overworld until its set later in the process.

I went ahead and moved it to right after the ServerLevel is "parsed" from the player's NBT.

**Comment by Brokkonaut** [comment]
Has anyone tested if this patch is still needed at all? It's a long time since 2016..

**Comment by Machine-Maker** [comment]
> Has anyone tested if this patch is still needed at all? It's a long time since 2016..

I don't know exactly where the crash would've taken place as I wasnt around back then, I do know that the Y value is clamped to -2e7 to 2e7 when its loaded from the entities NBT.

**Comment by Brokkonaut** [comment]
The teleport command allows y from -30000000 to 30000000, but testing with that location caused issues, i could not move when i teleported up there.

a location of y = 20000000 or -20000000 worked without any issues, event rejoining the server did not cause issues (i removed the limitation patch for testing). so maybe that could be good limitations? - and maybe a change for the limits in the teleport command could be useful too.

**Review by electronicboy — APPROVED** [review]

**Pull request closed without merging**
