### PR TITLE
Deprecate public Timings classes for removal

### PR DESCRIPTION
**Pull request by kennytv**
First step of https://github.com/PaperMC/Paper/issues/8948, assuming we actually decide to remove timings entirely.

After an explicit announcement and some more time passes, we can also add runtime warnings.

### CODE REVIEW

**Review by olijeffers0n — APPROVED** [review]

**Comment by UntouchedOdin0** [comment]
I fully understand why you guys are removing timings, but as mentioned please bring in spark to replace it so we have something to use for timings.

**Comment by Warriorrrr** [comment]
Replacing timings with spark is the idea yeah, see the issue linked in the pr description.

**Comment by CodeByCam** [comment]
LGTM

**Comment by EterNityCH** [comment]
I am EterNity and I approve this message.

**Review by EterNityCH — APPROVED** [review]
LGTM 🍡

**Review by kashike — APPROVED** [review]
I am kashike and I approve this message.

**Comment by UntouchedOdin0** [comment]
> Replacing timings with spark is the idea yeah, see the issue linked in the pr description.

Sorry! Didn't see that part, forgot my glasses! 🧐😅

**Pull request merged**
