### PR TITLE
Don't be so noisy with debug messages

### PR DESCRIPTION
**Pull request by kashike**
diff: https://gist.github.com/kashike/f243eca890ecfba3c459e4644a10eaa6/revisions

### CODE REVIEW

**Comment by aikar** [comment]
eh i think the approach is a little off here.

one, the config stuff has to be done back in the first config patch.

maybe the better idea is to just make a paper.settings.silent-startup, that hides all world setting based stuff.

no need for an API on that, considering 1) its just startup logging, 2) the activity has happened by time plugins are loaded.

But honestly, i think the best solution is to simply ensure messages are all INFO, and then you can just set your log level to WARN

**Comment by kashike** [comment]
@aikar nope.

a) `PaperConfig` is loaded after `SpigotConfig`
b) `PaperConfig` and `SpigotConfig` are in the implementation
c) It's not whether someone wants to change their log level, it's if they don't want to have these useless messages around

**Comment by aikar** [comment]
I meant that you are modifying the PaperConfig class in a new patch file. Z does not want that. 

All of PaperConfig's code has to be done in the original patch. so split it into 2 changes, 1 that updates PaperConfig to what you want it to be, 

then another patch that adds checks into other patches 
edit those specific patches to add the check instead of adding the checks in a new patch

as if said patch you're modifying is removed, your patch then fails

but im not sure why startup log messages that are so small compared to the rest of the contents of the log matters?

it's not like these messages repeat.

But maybe instead of using paper.yml, just use a -D flag to control it to handle the SpigotConfig side of things.

That's really the better approach as this would not be used much and don't need to litter users configuration files with an option they will not need to ever change.

so just do if (System.getOption("silentDebug") == null) { }

**Comment by aikar** [comment]
sorry I missed that you didn't have this setting in paper.yml, looks like your using properties file for this? 

I guess that could work too.

**Comment by kashike** [comment]
I'll await @Zbob750's input.

**Comment by zachbr** [comment]
I have looked at this several times now, and each time I twitch just a little when trying to think up an appropriate response.

It just feels ugly, but I'm not aware of a good way to clean it up either.

**Comment by zachbr** [comment]
I don't hate these log messages enough that I think such an ugly solution is worth pulling.

I don't blame you, I'm not sure of any "pretty" way to do this. Thanks anyway.

**Pull request closed without merging**
