### PR TITLE
Add getServerProperties API

### PR DESCRIPTION
**Pull request by katekerllenevich**
This adds the Server#getServerProperties API method so people can get the server.properties file.

### CODE REVIEW

**Review by MiniDigger — COMMENTED** [review]
I would argue that this shouldn't be under spigots stuffed api extension whatever bullshit (and that we should move the other configs there to the proper bukkit and server interfaces)

**Comment by katekerllenevich** [comment]
The only reason I put it there is because all of the other config stuff is there. Ill move it to the Server interface.

**Comment by JRoy** [comment]
Is this even something that should be exposed as API? Seems like implementation detail leaking out to API. Would a better solution be having separate api for the items inside the properties file (that don't already have api). As this just leaves an exposed and undocumented Properties object.

**Comment by HexedHero** [comment]
I feel like the use-case of this would be super, super niche.

**Comment by Camotoy** [comment]
An example to keep in mind in terms of API and looking into the future - in 1.17, the `max-build-height` server property will be removed.

**Comment by zml2008** [comment]
Or, for example, glowstone might not use a server.properties and might instead store everything in a glowstone.yml

**Comment by kashike** [comment]
I am closing this - see @zml2008's comment for reasoning.

**Comment by Machine-Maker** [comment]
> An example to keep in mind in terms of API and looking into the future - in 1.17, the `max-build-height` server property will be removed.

This will probably just be a method on the World interface, so not really an issue.

**Pull request closed without merging**
