### PR TITLE
Fix lighting bugs

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Comment by Euphillya** [comment]
With this patch, my server has OVER 9000 TPS (Vegeta voice)

**Review by katekerllenevich — APPROVED** [review]
only 9000?? im getting closer to 405005

**Comment by Euphillya** [comment]
> only 9000?? im getting closer to 405005

But i am a pentium 2.0Ghz on my server :(

**Comment by JRoy** [comment]
See #3430

**Review by mbax — APPROVED** [review]

**Comment by Titaniumtown** [comment]
my mspt now doesn't go above 0.0001 with 100 players, This PR is epic!

**Pull request closed without merging**
