### PR TITLE
Fix Mob Goal Leak

### PR DESCRIPTION
**Pull request by MiniDigger**
literally free performance!

didn't test yet cause am busy, I wanna test this on dyescape since thats where we noticed this (is really nobody else using my api? :/)

image

### CODE REVIEW

**Comment by MiniDigger** [comment]
I blame all reviewers on https://github.com/PaperMC/Paper/pull/2619 btw 😂

**Comment by Doc94** [comment]
> (is really nobody else using my api? :/)

XD, i recently start using the API for not use NMS in make Rabbits attack all... (code: https://gist.github.com/Doc94/9054d2fc9314a7d9ef8d20f42d3c5ad7) i dont notice nothing strange (dont know if timings show this custom goals)

**Comment by MiniDigger** [comment]
> > (is really nobody else using my api? :/)
> 
> XD, i recently start using the API for not use NMS in make Rabbits attack all... (code: https://gist.github.com/Doc94/9054d2fc9314a7d9ef8d20f42d3c5ad7) i dont notice nothing strange (dont know if timings show this custom goals)

You wouldn't notice this in timings, this is a memory leak

Been running this in prod at dyescape for a while now and memory usage is back at sane values, so this is good to go

**Review by Machine-Maker — APPROVED** [review]

**Comment by MiniDigger** [comment]
before:

after:


beautiful zig zag!

**Review by me4502 — APPROVED** [review]

**Pull request merged**
