### PR TITLE
Add raw iron & raw copper blocks to anti xray defaults

### PR DESCRIPTION
**Pull request by Warriorrrr**
Raw iron and raw copper blocks can generate naturally but these seem to never have been added to the anti xray defaults

### CODE REVIEW

**Comment by Machine-Maker** [comment]
So the concern from @stonar96 with adding more blocks to the hidden list is the effect is has on performance under engine mode 2. But seeing as these blocks are always located in the super large ore veins of iron and copper, maybe it is worth it to have them included.

**Comment by Warriorrrr** [comment]
Could this PR be re-opened? Didn't notice it got stale'd

**Comment by lynxplay** [comment]
Got you :+1:

**Comment by Warriorrrr** [comment]
Rebased for 1.19

**Review by Owen1212055 — APPROVED** [review]

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
