### PR TITLE
track complex entity parts (fixes #3070)

### LINKED ISSUE #3070: PlayerInteractEntityEvent causes server exception when canceled for EnderDragon/EnderDragonPart
### Link/paste of stack trace
https://pastebin.com/ZgunHXmz

### Plugin list:
SpigotInteractBug, sourcecode can be found [here](https://gist.github.com/drunderscore/6d7f9042533af2327115708a346a55a0), or a direct download [here](https://github.com/PaperMC/Paper/files/4384648/SpigotInteractBug-1.0-container.zip)

### Actions to reproduce (if known):
Simply interact with the ender dragon, in any dimension (ex, by right clicking), and the above exception will be thrown. Most likely caused by some obscure bug when handling complex entities/complex entity parts, of which the ender dragon is the only one of it's kind. Additionally, `Entity#getType` on `PlayerInteractEntityEvent#getRightClicked` will return `UNKNOWN`, which isn't correct (however, this also occurs on Spigot, whereas the above exception does not). Even more additionally, the event is called twice (for the same entity), whereas the exception occurs once.

### Paper build number:
Paper-144
`git-Paper-144 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

### PR DESCRIPTION
**Pull request by Trigary**

### CODE REVIEW

**Comment by Trigary** [comment]
Spottedleaf says I will also need a null check on the usages of the entity#tracker field. More input needed in general regarding everything and then I will fix this PR.

**Comment by Spottedleaf** [comment]
bad change, complex parts are NEVER tracked

**Comment by BillyGalbreath** [comment]
Proper fix is to override `b(EntityHuman, EnumHand)` in `EntityComplexPart`. I had to do this in my fork to make dragons mountable in right click instead of throwing the NPE.

**Comment by Trigary** [comment]
> bad change, complex parts are NEVER tracked

Well, they aren't until now, but if you say that this change is bad, I shall revert it.

> Proper fix is to override `b(EntityHuman, EnumHand)` in `EntityComplexPart`. I had to do this in my fork to make dragons mountable in right click instead of throwing the NPE.

It would seem that fixing this issue is beyond my abilities. But while I am it at, I might as well complete the fix, even if it has nothing to do with what I originally had in mind. What did you change exactly? Or which patch of yours is it? I can't find it, unfortunately.

The third solution is, as Spottedleaf originally said, is to add null checks to the usages of the entity tracker field. He also said that entity trackers should be nuked due to dumm plugins.

**Pull request closed without merging**
