### PR TITLE
Fix EntityPortalExitEvent not being called

### LINKED ISSUE #5174: EntityPortalExitEvent is never called
### What behaviour is expected:
One of the following two:
 - `EntityPortalExitEvent` to be called
 - `EntityPortalExitEvent` to be deprecated and it's JavaDocs to explain that it is never called

### What behaviour is observed:
The event is never called by neither Paper-Server nor Paper-API.

### Steps/models to reproduce:
 - Running the following command in the Paper (workplace) root directory shows us that the event is never fired: `grep -r --include *.java EntityPortalExitEvent Paper-*`
 - No deprecation, etc can be observed in the JavaDocs: https://papermc.io/javadocs/paper/1.16/org/bukkit/event/entity/EntityPortalExitEvent.html

### Plugin list:
None / NA.

### Paper version:
[00:40:18 INFO]: This server is running Paper version git-Paper-"13a476e15" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[00:40:18 INFO]: Previous version: git-Paper-"d4dcc1a2e" (MC: 1.16.5)
[00:40:18 INFO]: You are running the latest version

### Anything else:
Nope

### PR DESCRIPTION
**Pull request by Machine-Maker**
Was removed here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a2d787f6ebeb72fa7d5750788221fb9a0d838ac4

Fixes #5174

### CODE REVIEW

**Comment by kennytv** [comment]
Wouldn't it be better to just report that to Spigot?

**Comment by Proximyst** [comment]
Why don't we just... call it?

**Comment by Machine-Maker** [comment]
Well that's totally what I tried to do first, cause yeah would make sense. The logic around all that seems to have totally changed tho, I will whip up something and if you think its fine, then sure, but I wasn't sure it was really possible to conform to exactly what the event did before.

**Comment by Machine-Maker** [comment]
Ok @Proximyst take a look and see if this is satisfactory for re-adding it

**Comment by Machine-Maker** [comment]
Rebased for 1.17.1

**Review by Proximyst — APPROVED** [review]

**Pull request merged**
