### PR TITLE
rename legacy dragon check config setting

### LINKED ISSUE #6991: Ender Dragon and Return Portal Don't Spawn in Brand-New World if Setting "scan-for-legacy-ender-dragon" is Set To False in paper.yml
### Expected behavior

I expect the ender dragon and the (unlit) return portal to spawn upon entering the end dimension. This was observed on multiple server members' computers **in Singleplayer mode.**

### Observed/Actual behavior

The dragon did not spawn and neither did the return portal.

This has been attempted multiple times. Results were identical for both 10 chunk and 12 chunk simulation distances.

### Steps/models to reproduce

Set `scan-for-legacy-ender-dragon` to `false` in paper.yml.

~~In server configuration, set simulation distance to 10 or 12 (I tested both) and set render distance to 18~~

Enter the end through any portal (constructed or naturally generated)

The dragon does not spawn and neither does the return portal.

### Plugin List

BetterConcrete

CoreProtect

EssentialsX

EssentialsChat

EssentialsProtect

LuckPerms

RHLeafDecay

### Datapack List

Vanilla (built-in)

file/bukkit (world)

### Paper version

[01:33:26 INFO]: Checking version, please wait...
[01:33:26 INFO]: This server is running Paper version git-Paper-21 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: a5a7782)
You are running the latest version

### Other

EssentialsX and all related plugins are up to date. EssentialsProtect's option to prevent the ender dragon from spawning is disabled.

### PR DESCRIPTION
**Pull request by Machine-Maker**
Closes https://github.com/PaperMC/Paper/issues/6991

The old name doesn't really reflect what this does anymore since Mojang added a `NeedsStateScanning` field to the dragon fight nbt structure. The setting might be useful still, but I think it should be renamed.

### CODE REVIEW

**Comment by e-im** [comment]
Have you found a proper use for it? The original issue mentioned in https://github.com/PaperMC/Paper/issues/941 that caused it to be added no longer exists.

**Comment by Machine-Maker** [comment]
Yeah, thats why I renamed it. Now it just disables the first spawn of the ender dragon.

**Comment by IAmEchino** [comment]
Sorry for bothering y'all, but is there any update on this? I'm the original reporter from #6991.

**Comment by Machine-Maker** [comment]
Superceeded by https://github.com/PaperMC/Paper/pull/11262

**Pull request closed without merging**
