### PR TITLE
Update CB and Spigot

### PR DESCRIPTION
**Pull request by CDAGaming**
Includes:
SPIGOT-3561: Fix selectors in SuccessCount
Spigot/da4297479a847aaf2efa60ff147a44345c6bd737: Fix Javadoc typo

### CODE REVIEW

**Comment by CDAGaming** [comment]
Travis Seems to be weird tonight (pom.xml doesn't exist, even though i neither removed or changed anything on it)

**Comment by kashike** [comment]
https://github.com/PaperMC/Paper/commit/2104c3a68373a9299fd0ed31672d5d49a3aa86da

**Comment by CDAGaming** [comment]
Oddly that didn't show up on my Fork as being behind on that commit. My Mistake.

**Comment by electronicboy** [comment]
I hadn't gotten around to pushing it to this repo (I don't like pushing to this upstream repo before I go to bed for obvious reasons), however it was on my private repo pending being pushed. Your issue here is that you didn't, and haven't been, rebuilding the patches, even if they apply cleanly they _need_ to be rebuilt and committed otherwise it causes various issues elsewhere

**Comment by CDAGaming** [comment]
I see, and will do so next time i make a pr like this.

**Pull request closed without merging**
