### PR TITLE
[Untested] Fix iteration speed in NavigationListener

### LINKED ISSUE #51: Chunk loading causing severe tick drop.
Using PaperSpigot dev 450. 

Chunk loading is severely crippling my server TPS, making it completely unplayable whenever someone walks around to load chunks. Even with just 2 players loading chunks, TPS drops drastically. This issue seems to affect both Spigot and Paper from my testing.

Map entirely pre-generated in 1.9.

Timings - http://timings.aikar.co/v2/?id=a3b32241911f45148d2a3c0ae711105a
Profiler - http://paste.enginehub.org/xJZbV.profile

Additional data dumps if needed..

Timings;
- http://timings.aikar.co/v2/?id=1b24b6ebabfe47cc89cc91e7c7fb64f8
- http://timings.aikar.co/v2/?id=f49165f956984fcba8e0d2dc677680b1
- http://timings.aikar.co/v2/?id=5ba0238607d7478ba81a0fd6c03be0a9

Profilers;  
- http://paste.enginehub.org/H76bx.profile
- http://paste.enginehub.org/fcRb2.profile

Relevant information from IRC.

```
[18:46] <TechDragon> mibby: Its caused by toArray() in
[18:46] <TechDragon> Collection.toArray() in NavagionListener.a()
[18:47] <Techcable> mibby: Is this for slow chunk generation?
[18:47] <mibby> No. Different issue.
[18:47] <mibby> Server TPS dying when players load chunks.
[18:47] <mibby> Walking around.
[18:47] <mibby> World is already pre-generated.
[18:47] <Puremin0rez> 1.9 is showing terrible TPS drops with chunk loading
[18:47] <Puremin0rez> Structures is one of the causes
[18:47] <Puremin0rez> but i dont know why structures is
[18:48] <Techcable> Puremin0rez: Might be this 'NavigationListener'
[18:48] <Techcable> Its taking up huge amounts of time in the profiler
[18:48] <Puremin0rez> yeah
[18:48] <Techcable> for setTypeAndData()
[18:49] <Techcable> Oh man, if toArray() is the issue, i'd see why
[18:52] <Techcable> the toArray() method in naviagtion listener is dog slow
```

Full IRC discussion with various timings and profilers.

```
[16:57] <mibby> 1.9 is terrible. :( Chunk load is killing my server's performance, even on raid ssds. http://timings.aikar.co/v2/?id=1b24b6ebabfe47cc89cc91e7c7fb64f8
[16:58] <Puremin0rez> mibby, getting the exact same problem
[16:58] <TheEVIL> me too..
[16:58] <Puremin0rez> Structures and doChunkUnload are killing me on 1.9
[16:58] <mibby> I'm getting it on Paper and Spigot, a bit worse on paper though.
[16:59] <mibby> Literally ripping my server's TPS to shreads.
[16:59] <TheEVIL> tell mojang ;) :D
[16:59] <Puremin0rez> your timings looks exactly like mine actually
[16:59] <Puremin0rez> but yeah, 1.9 problems
[16:59] <Puremin0rez> figured as much
[16:59] <Puremin0rez> every release is usually pretty poor in performance until stuff gets figured out
[16:59] <mibby> :( Hopefully stuff gets figured out sooner rather than later.
[17:05] <mibby> Is there anything that can be done in Paper to act as a bandaid fix?
[17:06] <TheEVIL> worldborder fill
[17:06] <mibby> But my world is already entirely pre-generated.
[17:06] <mibby> This lag comes from loading chunks.
[17:06] <mibby> Players walking around.
[17:07] <TheEVIL> clearlagg>config>limit moving chunk to chunk
[17:15] <mibby> Doesn't seem to be doing much good. :(
[17:15] <mibby> Something is fubar in 1.9.
[17:18] <Byteflux> Use a sampler, find what the hot spot is? Best way to get it fixed
[17:24] <mibby> http://paste.enginehub.org/rTGba.profile
[17:35] <mibby> Full thread profiler. http://paste.enginehub.org/H76bx.profile
[18:07] <Puremin0rez> mibby, we have the same player count and are suffering from the exact same issues in timings, so i can only assume 1.9 is doing bad things
[18:21] <mibby> Puremin0rez: Your console just full of 'moved too quickly!' spam from every player too?
[18:22] <Puremin0rez> not full of, but i've seen it a lot more then 1.8
[18:22] <Puremin0rez> thinkofdeath said mojang made movement much more restricted in 1.9
[18:23] <Techcable> :D
[18:23] <Techcable> thats good
[18:23] <Techcable> Well, arguably
[18:23] <Puremin0rez> yeah its good but there's some false positives now because of how tight they made it
[18:24] <Techcable> what happens when you 'move to quickly'?
[18:24] <Puremin0rez> rubberbands
[18:24] <Puremin0rez> they did the same thing for vehicles now too, movement is very restrictive
[18:24] <Puremin0rez> so seeing boat movement spam in console is common now
[18:25] <Puremin0rez> which is good, cause boats movement (and all vehicles) are client side now
[18:25] <Skull> The worst thing I get is building up lag.
[18:25] <Techcable> why is it good if its client side?
[18:26] <Puremin0rez> Techcable, significantly less lag when moving, especially for high ping players
[18:26] <Puremin0rez> horses were essentially unusable before this change
[18:27] <Puremin0rez> they lagged in SINGLE PLAYER
[18:27] <Puremin0rez> movement should almost always be done client side, and have the server side do the enforcement
[18:28] <Z750> ^ there was no good way to do server side vehicles
[18:28] <Z750> if player movement is client side so should vehicles
[18:30] <mibby> :( Well due to this chunk load issue causing low tps, I'm getting moved too quickly messages quite often.
[18:30] <mibby> This bug is aggravating.
[18:32] <prplz> set your tps a bit higher then
[18:32] <Puremin0rez> set it to 25 or maybe 30 to counteract the lower tps
[18:32] <Paper> [Paper] Zbob750 pushed 1 new commit to master: https://git.io/v2baP
[18:32] <Paper> Paper/master 4170173 Aikar: Chunk save queue improvements
[18:34] <mibby> Too bad this issue seems to be due to chunk load, not save. :P
[18:34] <Z750> its possible it will affect save as well
[18:34] <Z750> err load
[18:34] <Z750> because w/out it it ends up keeping a lot of data in memory
[18:34] <Z750> well, w/out the file thread sleep removal
[18:35] <Z750> much quicker to hit memory than disk
[18:35] <Puremin0rez> that's true
[18:35] <Puremin0rez> i'll have to try it out
[18:35] <mibby> ^ I'll give it a try too.
[18:36] <GodzillaCI> Project Paper build #450: SUCCESS in 3 min 13 sec: http://ci.destroystokyo.com/job/PaperSpigot/450/
[18:36] <Z750> there's also a toggle in there for your fileiothreadsleep
[18:36] <Z750> so if you wanna use your wam, more power to you
[18:36] <mibby> Except I'm experiencing this problem both on Spigot and Paper. :o
[18:36] <mibby> So a toggle for the setting won't do much good.
[18:37] <Z750> well then youre talking about a different issue ¯\_(ツ)_/¯
[18:37] <mibby> Still related to chunks, but more-so in regards to loading them.
[18:37] <Puremin0rez> i can already promise you 1.9 has brought new performance related issues to the table
[18:37] <Puremin0rez> its just a matter of figuring them out
[18:37] <mibby> I'll re-run a profiler for you just in case, on paper.
[18:38] <mibby> So you can see yourself. :P
[18:38] <mibby> In the meantime, a timings. http://timings.aikar.co/v2/?id=f49165f956984fcba8e0d2dc677680b1
[18:39] <Puremin0rez> ahahaha those graphs
[18:39] <Puremin0rez> i mean :(
[18:39] <Techcable> Mojang uses a map in the datawatcher
[18:39] <Techcable> *synchronized map
[18:40] <Techcable> The ids never exceed more than 16
[18:40] <Techcable> It could be simplified to an array access
[18:40] <Techcable> And would use the same amount of memory.
[18:41] <Techcable> What do you think about switching?
[18:41] <Techcable> It'd break bad NMS plugins that reflect on the internal NMS fields
[18:43] <mibby> Full profiler. http://paste.enginehub.org/fcRb2.profile
[18:44] <mibby> Puremin0rez: That graph isn't too bad. I mean look, it is getting worse. :P http://timings.aikar.co/v2/?id=5ba0238607d7478ba81a0fd6c03be0a9
[18:46] <TechDragon> mibby: Its caused by toArray() in
[18:46] <TechDragon> Collection.toArray() in NavagionListener.a()
[18:47] <Techcable> mibby: Is this for slow chunk generation?
[18:47] <mibby> No. Different issue.
[18:47] <mibby> Server TPS dying when players load chunks.
[18:47] <mibby> Walking around.
[18:47] <mibby> World is already pre-generated.
[18:47] <Puremin0rez> 1.9 is showing terrible TPS drops with chunk loading
[18:47] <Puremin0rez> Structures is one of the causes
[18:47] <Puremin0rez> but i dont know why structures is
[18:48] <Techcable> Puremin0rez: Might be this 'NavigationListener'
[18:48] <Techcable> Its taking up huge amounts of time in the profiler
[18:48] <Puremin0rez> yeah
[18:48] <Techcable> for setTypeAndData()
[18:48] <Puremin0rez> chunks and pathfinding have had huge changes in 1.9
[18:49] <Techcable> Oh man, if toArray() is the issue, i'd see whu
[18:49] <Techcable> *why
[18:49] <mibby> Hopefully patchable in paper. :(
[18:49] <Techcable> no
[18:49] <Techcable> Actually
[18:50] <Techcable> This navigation listener thing does look slow though
[18:50] <Techcable> Its doing pathfinding updates or something
[18:52] <Techcable> Yeah
[18:52] <Techcable> mibby: Yeah
[18:52] <Techcable> Its dog slow
[18:52] <mibby> Mhm
[18:52] <Techcable> the toArray() method in naviagtion listener is dog slow
[18:52] <mibby> I've even tried dropping render distance to 4.
[18:52] <mibby> Didn't even make a dent.
[18:52] <Techcable> mibby: Doesn't have to do with render distance
[18:52] <mibby> Wouldn't a smaller render distance = less chunk load?
[18:52] <Techcable> Its just that setting blocks is dog slow
[18:52] <Techcable> mibby: Not at this point
[18:53] <Techcable> Its generating chunks all tick long
[18:53] <mibby> Even with a pre-generated world?
[18:53] <Techcable> mibby: The world is pre-generated?
[18:54] <mibby> Yeah.
[18:54] <mibby> Fully
[18:54] <Techcable> Hmm, this might be loading chunk issue
[18:54] <Techcable> *a
[18:54] <mibby> That's what I've been saying. :)
[18:54] <Puremin0rez> same with mine, getting the exact same issues as mibby too
[18:54] <mibby> I've ran Worldborder 3 times to verify it is 100% pre-generated
[18:54] <Techcable> Puremin0rez: Realy?
[18:54] <mibby> Puremin0rez is literally me. He always has the same problems I do. :P
[18:54] <TechDragon> yeah, ChunkIOEXecutor is chunk loading
[18:54] <Techcable> I'll fix it
[18:54] <Puremin0rez> recreateStructures is what's really hammering me, and my entire map is pregenerated
[19:31] <mibby> Techcable: If you are looking into the issue, here's another timings and profiler on Paper 450.  http://paste.enginehub.org/xJZbV.profile http://timings.aikar.co/v2/?id=a3b32241911f45148d2a3c0ae711105a
```

Pinging relevant parties whom I discussed this issue with on IRC.
@Puremin0rez @Techcable

### PR DESCRIPTION
**Pull request by Techcable**
Should fix #51 if it works.

Mojang was iterating over a copy of a key set of a map. (quite a mouthful)
This was very slow, since maps are slow, and copies are pretty slow.
Mojang was using maps for their weak-key functionality, which we reimplement directly.

This is untested.
@mibby please test.

### CODE REVIEW

**Comment by mibby** [comment]
@Techcable Leaving this crash error on the PR just in case you lost it on IRC.

```
[23:01:35] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 255, Size: 255
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.IndexOutOfBoundsException: Index: 255, Size: 255
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_74]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:45) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notify(World.java:438) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notifyAndUpdatePhysics(World.java:400) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.setTypeAndData(World.java:388) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldGenerator.a(SourceFile:31) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldGenTaiga2.generate(SourceFile:89) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.BiomeDecorator.a(SourceFile:126) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.BiomeDecorator.a(SourceFile:87) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.BiomeBase.a(BiomeBase.java:159) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.BiomeTaiga.a(SourceFile:94) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:373) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at org.bukkit.craftbukkit.v1_9_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.a(Chunk.java:991) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.loadNearby(Chunk.java:971) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:207) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerChunk.<init>(PlayerChunk.java:40) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerChunkMap.c(PlayerChunkMap.java:220) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:351) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerList.d(PlayerList.java:388) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:611) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	... 5 more
[23:01:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:842) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.IndexOutOfBoundsException: Index: 255, Size: 255
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_74]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:45) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notify(World.java:438) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notifyAndUpdatePhysics(World.java:400) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.setTypeAndData(World.java:388) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldGenLakes.generate(SourceFile:88) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:351) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at org.bukkit.craftbukkit.v1_9_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.a(Chunk.java:991) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.loadNearby(Chunk.java:971) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:207) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:315) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:311) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getType(World.java:734) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:242) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:172) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:223) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:831) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	... 4 more
[23:01:35] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IndexOutOfBoundsException: Index: 255, Size: 255
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_74]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:45) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notify(World.java:438) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.notifyAndUpdatePhysics(World.java:400) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.setTypeAndData(World.java:388) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldGenLakes.generate(SourceFile:88) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:351) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at org.bukkit.craftbukkit.v1_9_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.a(Chunk.java:991) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.Chunk.loadNearby(Chunk.java:971) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:207) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:315) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:311) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.World.getType(World.java:734) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:242) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.SpawnerCreature.a(SpawnerCreature.java:172) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:223) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:831) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) ~[patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-1.8.8-R0.1-SNAPSHOT-26-gd2807f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by Puremin0rez** [comment]
Hey @Techcable 

I've been searching the internet for people getting related issues with "NavigationListener" and have found quite a few public pastebins of people getting hung up in 1.9 due to this.

These are all the public pastebins I've found for the most information possible:
http://pastebin.com/fUCpmkrk
http://pastebin.com/jq7CgJKw
http://pastebin.com/YJ0CdVcq
http://pastebin.com/MgrKc3de
http://pastebin.com/GscGSUB5

This very well could be the main cause for significant chunk related TPS problems.

**Comment by Techcable** [comment]
I'm working on it :D
Also, mojang is stupid.

**Comment by zachbr** [comment]
I am under the impression that, as we all discussed in IRC, the solution @aikar proposed, and we merged in 017c6f7, was the best solution at hand. If you feel differently, and that more optimizations are needed, or that changes to that commit are necessary , please do not hesitate to contact me directly in IRC or open a new PR.

**Pull request closed without merging**
