### PR TITLE
Add `AsyncTabCompleteEvent.IntCompletion`

### PR DESCRIPTION
**Pull request by emilyy-dev**
Add `AsyncTabCompleteEvent.IntCompletion` to allow for numerically sorted completion suggestions

Signed-off-by: emilyy-dev <35617540+emilyy-dev@users.noreply.github.com>

### CODE REVIEW

**Review by Proximyst — APPROVED** [review]
Code looks fine. Needs testing

**Comment by jpenilla** [comment]
When I originally implemented the rich completion API, I looked into this, and it seemed like whether the int or string completion was used did not actually get sent over the network. Is that not the case?

**Comment by emilyy-dev** [comment]
> When I originally implemented the rich completion API, I looked into this, and it seemed like whether the int or string completion was used did not actually get sent over the network. Is that not the case?

It is not (whether it's an int or string suggestion is not sent), but the brig `IntegerSuggestion#compareTo` puts it before `Suggestion`s and sorts numerically in the `SuggestionBuilder`, and it's sent in the packet like that

**Comment by zml2008** [comment]
I've looked into this again -- it appears that completions are sorted serverside using IntSuggestions, which should be maintained assuming that completions are not re-sorted on the client. You would hope that doesn't happen, but I imagine you've tested this PR to confirm it functions as intended?

**Comment by emilyy-dev** [comment]
> I've looked into this again -- it appears that completions are sorted serverside using IntSuggestions, which should be maintained assuming that completions are not re-sorted on the client. You would hope that doesn't happen, but I imagine you've tested this PR to confirm it functions as intended?

Tested and yes they are shown as intended, the client does not re-sort them, it just rebuilds the suggestions as they are streamed in

**Comment by jpenilla** [comment]
Is it possible to have both a suggestion for int `1` and String `1` in the same list of suggestions (as in, will the client respect this and show two distinct suggestions)? If not, it might be better/easier to just check if the suggestion is a number, and if so use the appropriate method when adding the suggestion with Brigadier. I know this is the approach Sponge [uses](https://github.com/SpongePowered/Sponge/blob/ef080f509ef42dc0447a6147b01bc1401ddd707b/src/main/java/org/spongepowered/common/util/CommandUtil.java#L64-L72) in their API. I'm not particularly attached to either solution, just giving my thoughts.

**Comment by emilyy-dev** [comment]
> Is it possible to have both a suggestion for int `1` and String `1` in the same list of suggestions (as in, will the client respect this and show two distinct suggestions)?

It is possible yeah; the client does not really re-order them, it just shows them as the server sent them, so if I `.suggest(1)` vs `.suggest("1")` they are sorted differently, server-side [by the suggestions builder](https://github.com/Mojang/brigadier/blob/cf754c4ef654160dca946889c11941634c5db3d5/src/main/java/com/mojang/brigadier/suggestion/Suggestions.java#L99)
[IntegerSuggestion::compareTo](https://github.com/Mojang/brigadier/blob/cf754c4ef654160dca946889c11941634c5db3d5/src/main/java/com/mojang/brigadier/suggestion/IntegerSuggestion.java#L54-L65)
[Suggestion::compareTo](https://github.com/Mojang/brigadier/blob/cf754c4ef654160dca946889c11941634c5db3d5/src/main/java/com/mojang/brigadier/suggestion/Suggestion.java#L79-L86)

**Comment by jpenilla** [comment]
I was referring to allowing of duplicates more than ordering, but it seems like your implying duplicates are allowed as well, in which case this PR looks fine.

**Comment by emilyy-dev** [comment]
Ah yes duplicates are allowed, it's a `List` in the end

**Comment by emilyy-dev** [comment]
> I was referring to allowing of duplicates more than ordering, but it seems like your implying duplicates are allowed as well, in which case this PR looks fine.

To clarify: they don't allow duplicates of the same type (int/int or string/string) (so long as the tooltip passed implements `hashCode` properly), suggestions are [put in a hash set](https://github.com/Mojang/brigadier/blob/cf754c4ef654160dca946889c11941634c5db3d5/src/main/java/com/mojang/brigadier/suggestion/Suggestions.java#L94-L99), but `IntegerSuggestion` and `Suggestion` produce different hash codes so for int/string duplicates they are "allowed".

**Comment by jpenilla** [comment]
Got around to testing this, and it doesn't seem like the int suggestions end up first.

image

test code:
```java
AsyncTabCompleteEvent event;

event.completions().addAll(List.of(
  completion("string", text("TEXT")),
  intCompletion(2, text("NUMBER")),
  intCompletion(3, text("NUMBER")),
  completion("1", text("TEXT")),
  completion("2", text("TEXT")),
  completion("2", text("TEXT")),
  completion("2", text("TEXT")),
  completion("word", text("TEXT"))
));
```

It appears int/string suggestions are treated the same, and suggestions which are valid integers get properly sorted and are put first regardless of whether the completion was an `IntCompletion` or not.

**Comment by emilyy-dev** [comment]
Oh then in that case it might just be simpler and better to take the same approach as Sponge

**Pull request closed without merging**
