### PR TITLE
Improve Version Checking

### PR DESCRIPTION
**Pull request by Techcable**
Check versions against github instead of CI
Works better with building from source

### CODE REVIEW

**Comment by zachbr** [comment]
I am interested in checking directly from source only after we try the existing system and that fails. I am not interested in a complete replacement of our versioning system as it exists today.

**Comment by zachbr** [comment]
Did this myself using a... well you'll probably think it bastardized, version of your code.
b4bf59de2e2ad907a14639ca55b262bbf5347423

Thanks

**Comment by Techcable** [comment]
Nah, it looks perfect :)

**Comment by Techcable** [comment]
OH MY GOD YOU REMOVED THE REGEX.
HOHW CAN YOHU CHAK VARSIOHNS WITHOHUT A RAGAX OMG LOL

**Pull request closed without merging**
