### PR TITLE
Keep trying keepalive ping

### PR DESCRIPTION
**Pull request by BillyGalbreath**
Mojang sends a single keepalive packet out and waits eternally for it's reply. If that packet gets dropped for any reason the player will get kicked, even if they are still connected and playing with all other packets working normally.

This change will keep sending the keepalive packet every 20 ticks until a response is received or the player is kicked.

### CODE REVIEW

**Comment by Spottedleaf** [comment]
There's no point in this given the underlying protocol is TCP. All this does is needlessly use bandwidth as the client cannot read and handle packets out of order.

**Comment by BillyGalbreath** [comment]
@Spottedleaf tell that to the thousands of disconnects that happen because of this during the middle of their normal non-laggy gameplay.

**Comment by RoboMWM** [comment]
fite fite fite!

But anyways, if keepalive packet is not acked by client wouldn't server resend anyways (via TCP protocol)? Or is the time period for this too short compared to when the server just hangs up on the client?

**Comment by Spottedleaf** [comment]
My point still stands. The client cannot read the keep alive packet out of order due to the limitations of the underlying TCP protocol. Thus, if the client cannot read the first one, it will not be able to read the most recently sent one.

**Comment by BillyGalbreath** [comment]
From reading the code, the packet is sent out 15 seconds after the last one was replied to. Once it's sent the server will never try again until a reply is received. Once a reply is received the keepalive counter is reset and it will try again in 15 seconds.

So, once the packet is sent if its dropped or ignored for any reason the server's counter will never reset and the player will get needlessly kicked after the timeout period has passed, even if the player is in the middle of playing the game normally without any lag at all.

I understand it's on the TCP protocol, but the packet can still get dropped/ignored for any number of reasons. And both the client and server make assumptions that its been received/sent correctly.

For normal gameplay (the packet is sent and received normally), this change will not have any effect or added overhead. But for the ones that get dropped it will try again every 20 ticks. Most of the timeouts will be fixed on this first retry attempt, and the packet is so small there wont be any noticeable overhead. For those players that _truly_ are timing out the server will only waste about 10-15 packets before the player is kicked anyway, so there's not even much overhead there either.

`My point still stands. The client cannot read the keep alive packet out of order due to the limitations of the underlying TCP protocol. Thus, if the client cannot read the first one, it will not be able to read the most recently sent one.`

This fix has nothing to do with out of order packet processing or laggy clients. There's nothing we can do to fix laggy clients/networks. What this fixes is the thousands of disconnects that happen because this packet is poorly handled by both the server _and_ the client.

**Comment by Spottedleaf** [comment]
The TCP protocol will ensure the client receives the packet. 
Unless you can point me to a known bug where the client **erroneously ignores** the keep alive packet, this change is useless.

**Comment by BillyGalbreath** [comment]
`The TCP protocol will ensure the client receives the packet. 
Unless you can point me to a known bug where the client erroneously ignores the keep alive packet, this change is useless.`

I guess you've been lucky and never been kicked for keepalive timeout in the middle of normal gameplay? Kinda hard to take your stance on relying on TCP when I get kicked for keepalive timeout with 30ms ping to the server in the middle playing the game normally while sending/receiving thousands of packets since that 1 keepalive was sent (and dropped) 30 seconds ago.

**Comment by 0xC1A551C** [comment]
Experienced this issue over the past months of being kicked due to timeouts with no real cause. Very much at random during  gameplay, or just idle over periods of time. Happened at least once or twice a week, 

Logged into one of my other paper instances & noticed I would be kicked by the same keepalive timeout issue every time I would edit a CMI hologram with the CMI in-game editor. I was able to reproduce this probably around 20 times even after reboots.

Cleared my spigot, bukkit, and paper.yml. The issue went away for a bit but 5 minutes later experienced the same thing.  

After using a dev build of this my issue went away. I do not know if over time this will fix the issue, but it did 100% solve the CMI hologram keepalive ping timeout. Now the only thing left to see is if it solved it on all my paper instances even when I am playing regularly along with idling for hours or days.

**Comment by BillyGalbreath** [comment]
Update:

The fix appears to have worked in that it is indeed losing the original keepalive packet somewhere. Re-sending the packet gets a reply and the player is able to go on their merry way.

However, all is not good..

There is more code elsewhere that looks to be keepalive spam prevention, and when a keepalive is replied to _after_ it is re-sent and _both_ are replied to, this part of the code triggers and kicks the player anyway.

We're digging deeper to either figure the reason why the packet seemingly gets lost, or maybe even a better fix that wont trigger the anti-packet spam trigger.

Log with added output using the proposed fix:

```
[07:37:05 INFO]: Player issued server command: /rtp
[07:37:09 WARN]: Player sent keepalive ping
[07:37:09 WARN]: Player re-sent keepalive ping
[07:37:09 WARN]: Player re-sent keepalive ping
[07:37:09 WARN]: Player re-sent keepalive ping
[07:37:10 WARN]: Player received keepalive ping 12678329
[07:37:10 WARN]: Player received keepalive ping when not expected
[07:37:10 WARN]: Player received keepalive ping when not expected
[07:37:10 WARN]: Player received keepalive ping when not expected
[07:37:10 INFO]: Player lost connection: Timed out
[07:37:10 WARN]: handleDisconnection() called twice
```

Log with added output with the original server code:

```
[08:11:58 WARN]: Player sent keepalive ping
[08:11:58 WARN]: Player received keepalive ping 14767658
[08:12:03 INFO]: Player issued server command: /npc select
[08:12:05 INFO]: Player issued server command: /npc name
[08:12:07 INFO]: ❈ Admin Player » sf
[08:12:09 INFO]: Player issued server command: /cmi hologram msk addline
[08:12:10 INFO]: Player issued server command: /cmi hologram msk addline
[08:12:13 WARN]: Player sent keepalive ping
[08:12:13 INFO]: Player issued server command: /cmi hologram msk gui
[08:12:32 INFO]: Player issued server command: /cmi hologram msk addline
[08:12:33 INFO]: Player issued server command: /cmi hologram msk addline
[08:12:33 INFO]: Player issued server command: /cmi hologram msk addline
[08:12:43 WARN]: Player was kicked due to keepalive timeout!
[08:12:43 INFO]: Player lost connection: Timed out
[08:12:43 INFO]: Teleported to spawn!
[08:12:43 WARN]: handleDisconnection() called twice
```

As you can see, the player's keepalive reply is never received, but the player is still able to play the game normally. Even issuing server commands which are sent and received normally by the server, up until the timeout period passes and the player is kicked without lagging.

**Comment by mibby** [comment]
For what it's worth, a band-aid patch was released here which allows increasing the keealive timeout past the default 30 seconds. 
https://github.com/PaperMC/Paper/issues/895 https://github.com/PaperMC/Paper/issues/921

I tend to force mine to 120 seconds since I also experience this issue quite frequently with many members, but having a proper fix for this issue would be nice to have.

**Comment by electronicboy** [comment]
The issues you've linked are primarily due to the client taking too long to
reply, not keepalive packets supposedly going missing, which is two
entirely different issues, the proposed solution here is missing how these
packets are processed and dealt with by the server, nor would this touch
#921 which is an issue where the packets are stuck in the queue, resending
would not effect anything here

Im adverse to any further changes around this logic, the code that is
already in the server is simple and does the job, keepalive packets cannot
go missing, that's the entire nature of the network stack, if any packets
are actually going missing in the server or client, then that is a bug
which needs to be looked into.

**Comment by BillyGalbreath** [comment]
Closing since this isn't a proper fix. Will open a new one with a better fix when (if) I'm able to locate the root cause of the missing keepalive response.

**Pull request closed without merging**
