### PR TITLE
Add support for Brigadier commands

### PR DESCRIPTION
**Pull request by limwa**
Hello! This is my first PR ever, so *please don't judge me* xD

This patch allows plugin developers to register commands that use [Mojang's Brigadier library](https://github.com/Mojang/brigadier) and all of its capabilities. This means that plugin developers will be able to specify the type of an argument (such as greedy strings, quoted strings, integers, booleans, etc.) and that the client is able to give real-time errors, regarding what the player has written in the input box. Also, colored syntax :)

This is achieved by, first of all, adding Brigadier as an API dependency and by creating a class (`BrigadierCommand`) that extends the normal `Command` class. Then, developers can create objects of that class and register them to the command map. By doing so, the server automatically registers the node to Brigadier's command dispatcher. After that, they need to call `Player#updateCommands`, in order to send the command node to the player's client.

Of course, we require a source for the commands, so a new interface has been created, which is 'CommandSource'. It provides basic command context information and is implemented in 'CommandListenerWrapper'. 

Currently, the API does not support any argument types, other than the ones provided by Brigadier.

Finally, I know that Paper already supports Brigadier commands, however, there is no support on the API side, which is what this patch aims to fix.

### CODE REVIEW

**Comment by wizjany** [comment]
iirc this was discussed on the waterfall repo and the big issue is that it exposes the implementation directly and the implementation is liable to change at mojang's whim.

**Comment by yannicklamprecht** [comment]
Why not finish adding support for Brigadier in Aikars Command Framework and add that as a Paper recommendation?

**Comment by yannicklamprecht** [comment]
Why not finish adding support for Brigadier in Aikars Command Framework and add that as a Paper recommendation?

**Comment by MiniDigger** [comment]
see https://github.com/aikar/commands/pull/153

I maybe have a reason to work on that like next month or so, if anyone want to pick up my work that would be appreciated too, you can reach me on discord/irc if you have questions.

**Pull request closed without merging**
