### PR TITLE
Add FurnaceSmeltStartEvent

### PR DESCRIPTION
**Pull request by JonMagon**
https://user-images.githubusercontent.com/31476952/107673557-2d488e00-6ca7-11eb-912c-10f1874c35b1.mp4

```java
@EventHandler
public void onFurnaceSmeltStart(FurnaceSmeltStartEvent e) {
    Material sourceMaterial = e.getSource().getType();

    if (sourceMaterial == Material.CHICKEN) {
        e.setCancelled(true);
    }
    else if (sourceMaterial == Material.GOLD_ORE) {
        e.setCookTimeTotal(20 * 3);
    }
}
```

### CODE REVIEW

**Comment by TheFruxz** [comment]
nice 👍

**Review by MiniDigger — APPROVED** [review]

**Review by jpenilla — CHANGES_REQUESTED** [review]
In my testing I noticed that if you cancel the event, fuel will still be consumed even though no smelting occurs.

**Comment by JonMagon** [comment]
> In my testing I noticed that if you cancel the event, fuel will still be consumed even if no smelting occurs.

You should use FurnaceBurnEvent. Canceling this event only cancels the block melting. No changes are required, it's the logic of a plugin.

**Comment by jpenilla** [comment]
> > In my testing I noticed that if you cancel the event, fuel will still be consumed even if no smelting occurs.
> 
> You should use FurnaceBurnEvent. Canceling this event only cancels the block melting. No changes are required, it's the logic of a plugin.

I understand it's possible to "fix" this by listening to an additional event, however this seems kind of unintuitive. In my opinion it makes sense that cancelling the item from smelting should also implicitly cancel the fuel from burning.

**Comment by JonMagon** [comment]
> > > In my testing I noticed that if you cancel the event, fuel will still be consumed even if no smelting occurs.
> > 
> > 
> > You should use FurnaceBurnEvent. Canceling this event only cancels the block melting. No changes are required, it's the logic of a plugin.
> 
> I understand it's possible to "fix" this by listening to an additional event, however this seems kind of unintuitive. In my opinion it makes sense that cancelling the item from smelting should also implicitly cancel the fuel from burning.

We should not let an event interfere with another one. FurnaceBurnEvent is fired every time the fuel burns, FurnaceSmeltStartEvent is fired every time the smelting starts. There's a lot of non-intuitive stuff in events in general. The only thing I can suggest is to add a little explanation to the javadoc. However, we can wait for someone else. Conflict of interest is always exciting.

**Comment by JonMagon** [comment]
"Rebased"

**Comment by Owen1212055** [comment]
This has been implemented by upstream already, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/636/overview

See: FurnaceStartSmeltEvent

**Comment by JonMagon** [comment]
Already 😂
I had **already** forgotten about this PR a long time ago.
You could have waited five more years.
I don't care anymore.

**Pull request closed without merging**
