### PR TITLE
Add get/set wait time for fish hooks.

### PR DESCRIPTION
**Pull request by Owen1212055**

### CODE REVIEW

**Review by kennytv — CHANGES_REQUESTED** [review]
The descriptions are incorrect. The value is *decreased* and represents how long it takes until the fish/whatever will bubble towards the hook

**Comment by Owen1212055** [comment]
Updated to 1.17, use access transformer on field.

**Comment by Owen1212055** [comment]
rebased

**Review by electronicboy — APPROVED** [review]

**Review by Proximyst — APPROVED** [review]

**Review by qixils — APPROVED** [review]

**Comment by Machine-Maker** [comment]
I'm thinking this is also missing entity API which can be placed in your missing entity API patch right?

**Comment by Owen1212055** [comment]
> I'm thinking this is also missing entity API which can be placed in your missing entity API patch right?

Sure, in which case I will wait for the cat api to be merged for this then.

**Comment by Owen1212055** [comment]
I am thinking that this can be in a separate patch as my patch is mostly for entity animations/behavior that are not exposed.

**Review by Machine-Maker — APPROVED** [review]
Needs a quick rebase, but looks fine

**Comment by Owen1212055** [comment]
Consider it done!

**Comment by Owen1212055** [comment]
Rebased

**Comment by Owen1212055** [comment]
Updated

**Comment by Owen1212055** [comment]
Rebased (also remove this tag too please <3)

**Comment by Owen1212055** [comment]
Rebased + merged into Projectile API patch

**Review by kennytv — APPROVED** [review]

**Comment by Owen1212055** [comment]
Having some issues here whoopsies.

**Comment by Owen1212055** [comment]
Should be ready, and rebased.

**Pull request merged**
