### PR TITLE
Fix command suggestion leak

### PR DESCRIPTION
**Pull request by stonar96**
The server sends a filtered command tree to the client on join. Command nodes for which the player doesn't meet the brigadier requirement (permissions) are filtered and non-literal command nodes are replaced by an "ask server" command node for suggestions. Usually the client only asks the server for those command nodes. However, modded or outdated clients can still request suggestions whenever they like.

The problem here is that the response isn't even filtered and it still works if tab-complete is disabled in the spigot.yml file.

The easiest way to demonstrate this is to install ViaVersion and ViaBackwards, join with 1.12.2 as non-op, enter `/tele` and press tab. It will complete with `/teleport`, although you don't have permissions. Then disable tab-complete and even then it will still work. If you do the same with 1.17.1, `/teleport` won't be suggested at all because it's already filtered from the command tree, which is sent on join.

This PR filters the requested suggestions and implements the tab-complete setting for those requests.

### CODE REVIEW

**Comment by deciduous-buffalo** [comment]
I'm wondering does this fix account for PlayerCommandSendEvent command filtering? That is how I filter the commands for 1.13+ and it works fine there. Will the command filter I add in PlayerCommandSendEvent then apply to connecting with older clients too?

Also I opened a new issue #6579 several days ago regarding this exact issue, which was closed for some reason. Can that be re-opened by any chance?

**Comment by electronicboy** [comment]
That issue is invalid because it's to do with different client versions, even if this fixes it

the command send event will not be factored in here, to do would require that we blow extra memory for that use case, better to actually fix the commands or fallback to setting a permission node on the commands where they don't exist to be able to support this properly

**Review by electronicboy — APPROVED** [review]

**Comment by Shevchik** [comment]
The issue is not invalid tho. Ability to request root command completion is a feature of current minecraft protocol and is possible to do that using a modded client. Using VIA/PS is just the easier way of demonstrating that.
However it's up to the plugin that does filter command suggestions to also filter ask server tab completions.

**Comment by electronicboy** [comment]
When your reproduction steps fall around a protocol hack, it's invalid, even if it is demonstrating a wider issue, create a report for the wider issue which doesn't involve protocol hacks

**Review by Machine-Maker — APPROVED** [review]

**Review by jpenilla — APPROVED** [review]
I split this into two patches as it felt like there were two different changes here.

Also I switched out manually checking the node requirement for `canUse`, this means vanilla command permissions are checked properly.

**Pull request merged**
