### PR TITLE
added missing default perms

### LINKED ISSUE #4774: /teammsg (or /tm) cannot be executed without OP
### What behaviour is expected:
___What you expected to see___
A message to the team

### What behaviour is observed:
___What you actually saw___
"I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
While in a team, execute the command /tm or /teammsg 

### Plugin list:
___A list of your plugins___
None

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-279 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

### PR DESCRIPTION
**Pull request by Machine-Maker**
fixes #4774 

It seems that a ton of commands were missing their default permissions, so I added those.

### CODE REVIEW

**Comment by kashike** [comment]
It seems the formatting changed on every single line - can you fix?

**Comment by Machine-Maker** [comment]
@kashike the CommandPermissions class has CRLF line endings. 
image

So when I make any changes, it updates them all to LF, replacing all the lines. What's the best course of action to fix this?

**Comment by nicegamer7** [comment]
I'm not sure I understand the problem, but you can change the line endings in the bottom right of IJ.

**Comment by Machine-Maker** [comment]
> I'm not sure I understand the problem, but you can change the line endings in the bottom right of IJ.

Yes, that's exactly the issue. It changes them to LF (which they should be) and that makes the patch file unnecessarily large.

**Comment by Machine-Maker** [comment]
Ok, so yeah, the original file when added back in [2014](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/33af6fbbbf1c1a8fee3ecc8d4cf79b4a2ba17c16) has CRLF endings. So I just forced this file to have them as well even though ALL the other files are LF.

**Comment by yannicklamprecht** [comment]
Why not patching the old file to have LF (diff should not differ in the first patch I guess)? So it'll be future proof.

**Comment by Prof-Bloodstone** [comment]
This would always cause patch conflicts, if any line is added with CRLF ending upstream. Maybe we could add a patch that adds '.gitattributes' file which marks this file explicitly as CRLF ending? Maybe this would be an acceptable bandaid solution which won't cause conflicts.

**Comment by yannicklamprecht** [comment]
> This would always cause patch conflicts, if any line is added with CRLF ending upstream. Maybe we could add a patch that adds '.gitattributes' file which marks this file explicitly as CRLF ending? Maybe this would be an acceptable bandaid solution which won't cause conflicts. 

Would do it the other way around -> everything added to git should be LF.

**Comment by Prof-Bloodstone** [comment]
Ideally I'd also do that. But if we don't want to have conflicts or as MM had whole files committed as patches because of line ending change, we need to use whatever ending upstream uses.
Also, pretty sure if we committed a big part of upstream/Mojang code in a patch file, it would cause performance issues and might cause legal problems.

**Comment by yannicklamprecht** [comment]
> Ideally I'd also do that. But if we don't want to have conflicts or as MM had whole files committed as patches because of line ending change, we need to use whatever ending upstream uses.
> Also, pretty sure if we committed a big part of upstream/Mojang code in a patch file, it would cause performance issues and might cause legal problems. 

So upstream uses CRLF? Then yeah. Assumed it was LF.

**Comment by Prof-Bloodstone** [comment]
As MM mentioned above, most files use LF, while at least this one uses CRLF: https://github.com/PaperMC/Paper/pull/4778#issuecomment-728589113

**Comment by MiniDigger** [comment]
having a full bukkit file in a patch shouldn't be that much of an issue, its small anyways. would have one patch to fix line endings and one for the actual change. but this could mean having to re do it manually when upstream changes stuff which is meh.

the real solution would be have our tooling handle such malformed upstream files (or well, upstream fixes it).

I opened an issue upstream: https://hub.spigotmc.org/jira/browse/SPIGOT-6242

**Comment by Machine-Maker** [comment]
I can go ahead and split it up into multiple patches, should I loop through all the files in the server/api and see if there are any others and put those in the patch for line endings as well?

**Comment by MiniDigger** [comment]
Not nessasary, md did it

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8b3b096d1a383777e0922686765ffbd18aebd28f

**Comment by Machine-Maker** [comment]
Ok, upstream's changes are in, so this patch is back to good ol' LF.

**Review by MiniDigger — DISMISSED** [review]

**Review by Proximyst — DISMISSED** [review]

**Review by electronicboy — DISMISSED** [review]

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
