### PR TITLE
Updated Upstream (Bukkit/CraftBukkit)

### LINKED ISSUE #8157: Goat Horn API
### Is your feature request related to a problem?

There is seemingly no class or method in the API to get the Type of a Goat Horn 

### Describe the solution you'd like.

Create a new subclass of ItemMeta which exposes a getter and setter for the goat horn "instrument" type

### Describe alternatives you've considered.

Janky NMS or NBT hacks? idk

### Other

_No response_

### PR DESCRIPTION
**Pull request by byquanton**
Removed 0956-Return-0-by-default-for-FireworkMeta Patch because it was fixed upstream.

### CODE REVIEW

**Comment by Machine-Maker** [comment]
You can just delete the patch, no need to move it to the removed folder. That folder is for other types of "removed" patches, like patches that only applied to previous versions, or patches that don't make sense on a codebase level anymore. Not simple patches like this which upstream fixed.

**Comment by byquanton** [comment]
Should I create a second commit or amend the commit?

**Comment by olijeffers0n** [comment]
Approve Workflow?

**Comment by Owen1212055** [comment]
Should be noted for future use that usually only the development team is responsible for pulling upstream. 👍

**Review by electronicboy — APPROVED** [review]

**Comment by electronicboy** [comment]
This PR was created improperly, i.e. the patches haven't been rebuilt, which will cause issues; given that this PR was created from master, that means that we can't easily fix this on our side

**Pull request closed without merging**
