### PR TITLE
abstract custom set tags

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Perhaps this should be done on the original patch where aikar added the MaterialSetTag class? Wasn't sure.

**Comment by MiniDigger** [comment]
yeah, this can be done in the OG patch. whats the rationale behind this? support tags for other types?
might as well add subclasses for entities then or smth

**Comment by Machine-Maker** [comment]
Yeah, so people can PR non-vanilla tags for other things.

**Review by aikar — DISMISSED** [review]
seems good to me

**Comment by MiniDigger** [comment]
@limbo-app ready

this turned out to be a bit controversial with the zombie tag, I replaced it with a undeads tag. also added a water-based tag.

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
