### PR TITLE
Added boolean hideInPlayerList to hidePlayer function.

### PR DESCRIPTION
**Pull request by JMBoy01**
#9045 Made changes to the hidePlayer function. You can chose if the player also disappears from the player list.

### CODE REVIEW

**Comment by lynxplay** [comment]
Presumably a partial duplicate of #8782, at least in what it aims to achive.

**Comment by dawon** [comment]
> Presumably a partial duplicate of #8782, at least in what it aims to achive.
> 
> //edit
> Welcome to paper and thanks for your first PR :)

I think it is good add-on to the pr you mentioned. There is no way on said PR to hide player while retaining them in player list. You need to hide player and then reshow them in the list. This will allow to do it in one step.

But it would be good to coordinate these to prs so there are not conflicts...

**Comment by JMBoy01** [comment]
Hello, is it normal that I'm still waiting on a review or isn't that going to happen since 1.20 came out in the mean time? I would just like to know.

**Comment by kforbro** [comment]
> Hello, is it normal that I'm still waiting on a review or isn't that going to happen since 1.20 came out in the mean time? I would just like to know.

image

**Comment by underscore11code** [comment]
Closing this as a duplicate of #8782. Thank you for your contributions.

**Pull request closed without merging**
