### PR TITLE
Make Anti-Xray multithreaded

### PR DESCRIPTION
**Pull request by stonar96**
Definitely needs testing.

### CODE REVIEW

**Comment by A248** [comment]
~~Is there a reason you removed the max book page size, or am I missing something?~~
Edit: I just realised, sorry

**Comment by wizjany** [comment]
He didn't, it's just not part of those diffs anymore.

**Comment by stonar96** [comment]
Rebased due to conflicts.

**Comment by aikar** [comment]
Thanks! I switched it to the server thread pool, as the pool isnt used enough as is, so we dont really need more thread pools.

**Comment by stonar96** [comment]
@aikar Thanks, I have also reviewed your changes and it's fine, I like it. The only thing to keep in mind is that a `FixedThreadPool` should be used (not a cached or something), ~~otherwise the `ThreadLocal`s will create memory leaks.~~ otherwise the `ThreadLocal`s will create new instances for every new thread. The server thread pool is created in `SystemUtils` with `new java.util.concurrent.ThreadPoolExecutor(i, i,0L, TimeUnit.MILLISECONDS, new java.util.concurrent.LinkedBlockingQueue<Runnable>(), ServerWorkerThread::new);`, which is basically the same as a `FixedThreadPool`. So everything is fine.

**Pull request merged**
