### PR TITLE
Fixes a couple issues with entity spawn reasons

### LINKED ISSUE #8389: DISPENSE_EGG condition isnt used for CreatureSpawnEvent
### Expected behavior

When a dispenser summons an entity because it had an egg in it this should set the events reason to DISPENSE_EGG.

### Observed/Actual behavior

When the event is fired the events reason is the generic SPAWNER_EGG reason.

### Steps/models to reproduce

1. Egg in dispenser
2. Trigger dispenser

### Plugin and Datapack List

Only a plugin to observe the event.

### Paper version

Current: git-Tentacles-"215faae" (MC: 1.19.2)*
Previous: git-Tentacles-"0bba12b" (MC: 1.19.2)
You are running the latest version

### Other

the server version is my fork of purpurmc, however i had a look at the code from just papermc and it seems like the issue persists

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes https://github.com/PaperMC/Paper/issues/8389

Merges the tadpole spawn reason patch with this one.

* Fixes the DISPENSER_EGG reason not being used for eggs from dispensers
* Uses the EXPLOSION reason for area effect clouds from dragon fireballs
* Fixes a javadoc issue with the EXPLOSION reason.

### CODE REVIEW

**Comment by Owen1212055** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0917-Add-SpawnReason-to-Tadpoles-spawned-by-Frogspawn.patch

Do we want to merge these patches?

**Comment by Machine-Maker** [comment]
Yeah, probably can. Now I'm gonna look for other places it was missed. I bet there is at least one other spot a SpawnReason can be added.

**Review by kennytv — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]

**Review by electronicboy — APPROVED** [review]

**Comment by antibitcoin** [comment]
This broke AdvancedCrates plugin cosmic crate effect somehow.

**Comment by electronicboy** [comment]
We can't really do much around premium plugins

**Comment by MiniDigger** [comment]
ask the author to report an issue with a minimal repro case, we cant help as we cant look at the code of said plugin, nor did you provide any details.

**Pull request merged**
