### PR TITLE
Update Alternate Current patch

### PR DESCRIPTION
**Pull request by SpaceWalkerRS**
- port to Minecraft 1.19
- update to v1.3, fixing some Vanilla parity issues (like #7852)

### CODE REVIEW

**Comment by kennytv** [comment]
Will just merge no questions asked for now, thank you <3

**Comment by molor** [comment]
(sorry if that's unneeded, but) can you backport this update/fix to current master/1.18.2 too, please? Thanks for your work!

**Comment by SpaceWalkerRS** [comment]
I don't know what the plan is for 1.18.2 Paper now that 1.19 development has begun, but I wouldn't mind updating the AC patch on 1.18.2.

**Comment by Machine-Maker** [comment]
We usually support bug fixes (and anything anyone else wants to take the time to PR) for a several weeks to months after a new release. So it'd be accepted.

**Pull request merged**
