### PR TITLE
ratelimited packet is logged to console on kick

### PR DESCRIPTION
**Pull request by bdotsamir**
First PR 🎉 Huge thanks to lynxplay for helping me out here

Hopefully fixes issue: #8747

### CODE REVIEW

**Comment by EternalHuman** [comment]
I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL I WAS HERE xqcL

**Review by yannicklamprecht — APPROVED** [review]

**Comment by lynxplay** [comment]
Welcome to paper :tada: thank you for your first PR.

Things we should discuss here are

- [ ] Should this be behind a configuration option ?
- [ ] This should probably also explicitly mention the user kicked

**Comment by olijeffers0n** [comment]
I don't think this needs to be behind a config option as it is, arguably, very useful information. But yeah, the user / UUID in suspect should be logged IMO

**Comment by cosmohdx** [comment]
I don‘t see any case this is not needed. In every case i have in my mind, it would be thankful to have the reason and the user logged.

**Comment by electronicboy** [comment]
depends on how easy it is to trip, flooding logs is one of the many fun DDoS style attacks you can do, especially for servers running in janky wrapper processes; this is probably not a concern here, but it's not like log messages are 100% free

**Comment by MachineBreaker** [comment]
This should be under a configuration option considering what electronicboy said

**Review by Owen1212055 — APPROVED** [review]
I see no huge reason for a config, especially since kicking the player already has some logging in itself. This just makes it a bit more descriptive.

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
