### PR TITLE
Itemstack Glint API

### LINKED ISSUE #5274: API to make ItemStacks glowing (without adding real enchants)
**Is your feature request related to a problem? Please describe.**
I want to make items (`ItemStack` / `ItemMeta`) glowing without changing anything else.

**Describe the solution you'd like**
Addition of two methods: `ItemMeta#setShiny(boolean)` and `ItemMeta#isShiny()`.
The setter shouldn't apply any real enchantments and definitely shouldn't add `ItemFlag.HIDE_ENCHANTS`: the item might already have enchantments (or if not, it might have enchantments in the future), so adding that flag would be bad. Adding a real enchantment is also bad since I don't want enchantments to show up under `#getEnchantments()` just because I called `.setShiny(true)`.
The return value of `isShiny()` should stay the same prior to and after serialization/deserialization, whatever that value might be. So in other words, this feature should support serialization.

**Describe alternatives you've considered**
Solutions that rely on `ItemFlag#HIDE_ENCHANTS` are possible but are complicated if we want to do it right: we have to keep in mind that items can get enchanted via commands, via enchanting tables, by other plugins. So we have to remove the `ItemFlag` when necessary, etc.
@HexedHero claims to achieve this by registering a custom `Enchantment`, but that's not supported by the Bukkit API, therefore is a non-solution.

**Additional context**
kashike believes implementing this is possible.

### PR DESCRIPTION
**Pull request by Machine-Maker**
Closes #5274

First time touching item meta stuff

Unsure of a few things, mainly the behavior of this elsewhere in the codebase, like anvils/grindstones. Currently you can remove the glint with the grindstone (and get no xp), and you can put enchanted books on the item, *BUT* that removes the empty NBTTagCompound, so removing that enchant will make the item lose it's glint.

Issue relating to this: #5723

### CODE REVIEW

**Comment by JRoy** [comment]
Not sure how I feel about this because all this seems like is a helper method for adding enchantments while making it seem like an inherent property an ItemStack can have. 

Also, has this been tested with items that already have enchantments on them?

**Comment by Machine-Maker** [comment]
I didn’t specifically test that JRoy, but the result would be an Enchantments nbt list with a normal tagcompound and an empty one. I don’t see how that would behave differently from a list with just an empty one

**Review by Proximyst — CHANGES_REQUESTED** [review]
Uh... just add an empty enchantment? Like a proper one with proper NMS implementation?

**Comment by Machine-Maker** [comment]
Won't that still show up on the item? I dont know how the client determines what shows up or not if its missing an equivalent on the client side.

**Comment by kennytv** [comment]
You can easily create "invisible" enchantments, even with API (with no hide tag required).

**Comment by kennytv** [comment]
Aside from Bukkit, the most basic format a client accepts perfectly fine is something along the lines of this (just some Via code stuffed somewhere to get the gist of it):
```java
            // Add dummy enchant for the glow effect if there are no actual enchantments left
            if (!storedEnchant && enchantments.size() == 0) {
                CompoundTag dummyEnchantment = new CompoundTag();
                dummyEnchantment.put("id", new StringTag()); // String value empty = ""
                dummyEnchantment.put("lvl", new ShortTag((short) 0));
                enchantments.add(dummyEnchantment);
            }
```

**Comment by HexedHero** [comment]
Curious, how does normal items have the enchantment glint without any enchantments such as the golden apple?

**Comment by Machine-Maker** [comment]
Pretty sure those are hardcoded by on the client.

**Comment by Owen1212055** [comment]
image
(yarn mappings)

**Comment by Machine-Maker** [comment]
> image
> (yarn mappings)

Yes, exactly, I don’t think that is ever passed between the client and server, hence, hardcoded.

**Comment by HexedHero** [comment]
Can we just ask Mojang for an NBT flag it seems super easy.

**Comment by electronicboy** [comment]
I've dropped that suggestion in a place where we often speak to mojang devs, will see if they have any comments on this as the general handling of this always feels a bit icky, so I'd love to avoid having to do something like this as supported API

**Comment by nicolasvac** [comment]
@electronicboy Do you have any news on it ?

**Comment by Owen1212055** [comment]
In general, this can prolly be closed? Hopefully waiting on mojang for this, but with my item property API these types of items will work just fine in the future due to no item meta processing being done.

**Comment by Owen1212055** [comment]
Closing in favor of the item property api.

**Comment by enqorman** [comment]
in 1.20.5, we will be getting components, and one is override_enchantment_glint

**Pull request closed without merging**
