### PR TITLE
Add BlockBreakNaturallyEvent

### PR DESCRIPTION
**Pull request by Cryptite**
This is admittedly a messy PR that should be separate pieces, but because the new event relied on the more base-level commit: https://github.com/PaperMC/Paper/commit/881052595d18bd69847206d18d764e5a34aa387f

That commit sets the groundwork for other future patches that can add Player references to events that currently do not have them. So the PR basically needed to be all-in-one.

_Ultimately_, this PR exists to add the BlockBreakNaturallyEvent. This event fires whenever a block is broken due to a Physics Update propagated from another block break (Breaking vines, or a block with a torch attached, etc). This is meant to be a better way to detect block breaks than trying to evaluate the very heavy BlockPhysicsEvent.

The storage of `currentBlockEventPlayer` and `currentBlockEventBlock` is perhaps wonky but mimics other similar patterns like `capturedBlockStates` for event handling.

### CODE REVIEW

**Comment by Cryptite** [comment]
It appears I didn't know about `BlockFertilizeEvent`, so can probably rip out all of the `BlockGrowEvent` changes.

**Comment by Cryptite** [comment]
Removed the unnecessary patch for `BlockGrowEvent` as `BlockFertilizeEvent` does all that is needed. PR should be ready now pending review.

**Review by aikar — CHANGES_REQUESTED** [review]
this is not right name.

BlockBreakNaturally is not really proper for physics related events. 

this i think would be more appropriately named BlockDestroyedByNeighborEvent

I ended up working around this code a lot last night, and this area seems only related to physics.

The iblockdata1 is the neighboring blockstate that triggered the physics to destroy this, and should be exposed.

**Comment by Cryptite** [comment]
It's nice to know what the source block TYPE _was_, so we have two options I guess. Should there be `sourceBlock` which would likely be AIR or the `sourceBlock` original version which, say, is a VINE. 

Alternatively we could have `getSourceBlockData()` which represents the `iblockdata1`. Unsure what's the common convention here.

**Comment by aikar** [comment]
BlockState already has .getMaterial() which is what your asking for.

**Comment by Cryptite** [comment]
Closing this as I implemented this entirely differently and will just create a new PR for it later.

**Pull request closed without merging**
