### PR TITLE
Add support for io_uring

### PR DESCRIPTION
**Pull request by skbeh**
This only works when not using unix domain socket
and compression is disabled because
the netty io_uring transport does not support
unix domain socket and the client can not decode
compressed packets sent with io_uring.

### CODE REVIEW

**Comment by clrxbl** [comment]
arm64 support should also be added

**Comment by electronicboy** [comment]
having to disable compression is a huge red flag that something is wrong somewhere, and we shouldn't really be glossing over that

Also, this *really* needs to be configurable, I don't think that we should be pushing unstable linux features and netty incubator projects, especially without any form of sane opt-out

**Comment by skbeh** [comment]
@electronicboy I added the option to make it configurable.

**Comment by skbeh** [comment]
@olijeffers0n I think it should be opt-in now, because it is still relatively experimental.

**Comment by skbeh** [comment]
Also bump netty so that the versions of dependencies match.

**Comment by toinouH** [comment]
About #paper-contrib discussion on netty io_uring here is my opinion:
- I like the idea to disable it by default.
- I think the security concerns (and the experimental natur of netty-io_uring) could be mentioned with a WARN message when enabling this mode on every startup.
-We might also need a WARN or INFO message about the compression issue.

- I also think (as mentioned if I remember) you don't really need to maintain it so it's "free performance".

**Comment by Sytm** [comment]
I am just gonna leave [this Google Blog post](https://security.googleblog.com/2023/06/learnings-from-kctf-vrps-42-linux.html?m=1) here regarding the security state of io_uring as a resource for further discussion if it is still desired to add this into paper.

For me this gives me more "free vulnerabilities" than "free performance" vibes, but I digress.

**Comment by xymb-endcrystalme** [comment]
I ported that patch to my Folia fork and the total throughput of clientbound packets on 4 Netty threads increased from about 120k to about 500k per second.

io_uring is definitely worth implementing in Paper & Velocity. 👍

**Comment by kennytv** [comment]
Ofc throughput is going to increase if you disable compression as well (at the cost of clients and your networking bill), but another problem is that io uring is that, in a funny twist, many big companies have completely blocked io_uring due to being prone to tons of security vulnerabilities

**Comment by xymb-endcrystalme** [comment]
Compression had nothing to do with it. My tests were with compression disabled for epool.

**Pull request closed without merging**
