### PR TITLE
Fix lead dupe

### PR DESCRIPTION
**Pull request by webcrawls**
This patch fixes the Paper lead dupe. ok pls give contrib role now plsthxty (NOT /s.)

### CODE REVIEW

**Comment by tadhgboyle** [comment]
LGTM,  thanks.

**Review by JRoy — DISMISSED** [review]

**Review by Titaniumtown — DISMISSED** [review]
LGTM

**Review by Titaniumtown — DISMISSED** [review]

**Comment by Toshimichi0915** [comment]
Did you test your code yourself?

**Comment by webcrawls** [comment]
https://discord.com/channels/289587909051416579/555469074080202765/791914607711092766

**Comment by Toshimichi0915** [comment]
So, you tested your code?
All you did was to copy & paste my code. And you didn't even try to test the code you submitted

**Comment by webcrawls** [comment]
> So, you tested your code?
> All you did was to copy & paste my code. And you didn't even try to test the code you submitted

I don't feel like getting in a stupid quarrel over this - jroy asked me to resubmit this PR, so I did. I am happy to close this if you'd like me to.

**Review by Proximyst — DISMISSED** [review]
LGTM. Tested & works. Will fixup upon merge

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
