### PR TITLE
Optimise removeQueue

### PR DESCRIPTION
**Pull request by AlfieC**
Brings removeQueue operations back to O(n) instead of O(n^2).

### CODE REVIEW

**Comment by AlfieC** [comment]
For some reason, EntityPlayers are being copied to themselves on respawn/world switch. The LinkedList masked this issue, but the ArrayDeque threw a CME. I've updated to patch to ensure that the removeQueue is never copied to itself, but why was this happening in the first place? 

**EDIT:** If anyone wants to see the exception, it is http://hastebin.com/belulilofu.vbs

**Comment by Black-Hole** [comment]
I think it's was easier to keep track of the same EntityPlayer object instead of creating a new one. But now you can't change it because plugins might hold references to those objects.

**Comment by AlfieC** [comment]
Nonono, it's using the same EntityPlayer object. It's literally calling entityplayer.copyTo(entityplayer). I see why in the case of resending health and such, but for some things it's completely unnecessary.

**Comment by Black-Hole** [comment]
Yes, this change was done by CraftBukkit many years ago. We now have to live with it. :)

**Comment by Techcable** [comment]
This is an awesome optimization, and I have no idea why Mojang wrote this code with such a ridiculous choice of data set.
Kudos to you for noticing the quadratic complexity and fixing it. Hopefully, this should provide a major improvement to the removeQueue performance.

**Comment by AlfieC** [comment]
Credit to vemacs for the data set idea :D

**Comment by Spottedleaf** [comment]
This could be optimized further if we used a deque implementation which uses int as its element rather than the boxed type Integer.

**Comment by AlfieC** [comment]
That's really getting into the micro, though. If it shows as an issue on timings I'll amend this patch with an IntDeque.

**Comment by zachbr** [comment]
Merged via a0fce850864fe73545376d83fa670143169990e8

**Pull request closed without merging**
