### PR TITLE
Add EntityInsideBlockEvent

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Comment by kennytv** [comment]
A better name would be `EntityInsideCauldronEvent` since it's not just called when you "enter" it

**Comment by Machine-Maker** [comment]
Yeah, ok. renamed to `EntityInsideCauldronEvent`.

**Comment by kashike** [comment]
Why not make this a more generic "entity inside block" event?

**Comment by Machine-Maker** [comment]
Yeah, I thought about that. There are a bunch of blocks with implement that method on `BlockBase`. Could put it in the method in `BlockBase` itself, and make sure its `super`'d everywhere. I just wasnt sure what the best way to do that was. I just know I needed it for cauldrons.

EDIT: Really, a whole different kind of event system would be great for listening to all the various method on `BlockBase`, and only for specific blocks and what not, but that's a WHOLE other can of worms.

**Comment by kashike** [comment]
Well, I mainly meant with the event name itself - we can add more cases where it's actually called for sure, but having a more generic event name is good when we can.

**Comment by Machine-Maker** [comment]
Ok, I generalized the event, and adding callers to all blocks that overrode that method on BlockBase

**Review by MiniDigger — APPROVED** [review]
this developed into a pretty useful event for all kind of things, I like it!

sadly its not easy to know which blocks are affected without looking at the code, but I can't think of a better description either, without listing everything (which is hard to maintain), so am fine with it as is

**Comment by Machine-Maker** [comment]
One comment I had, was in `BlockWaterLily`, there is a call to super#a. For some reason, it's the only one that does, that may mess something up if that method is ever overriden in `BlockPlant` (event would be called twice). May have to to instanceof checks in the future to ensure the event is only called once, id.

**Comment by kennytv** [comment]
Hmm specifically for lilies and crops I'm a bit unsure whether this should actually be called for *every single* entity calling the inside block function of a block, since from the point of a plugin dev it's basically random for what kind of blocks it is called, and also very much useless if you call the event for any random entity standing inside of a crop or a lilypad (or for example an item in a berry bush).

So imo the event should only be called if it actually affects whatever is inside the block.

**Comment by Machine-Maker** [comment]
That defeats the whole reason I made this PR in the first place, I wanted to know when an item entity was inside a cauldron, normally, that wouldn't do anything, but only because its called for every entity inside does this work.

**Comment by kennytv** [comment]
Then you should definitely at least document every single block this will be called for, otherwise this is just fully arbitrary/unpredictable API for anyone looking at the docs

**Comment by Machine-Maker** [comment]
I mean its not fully unpredictable API, any block that has any functionality from any entity being inside of it triggers this event.

**Comment by kennytv** [comment]
But how would anyone know blocks that have "functionality with an entity inside them"? I'd be surprised if you had any idea of crops implementing that to check for ravagers, or that this is the exact function used for boats hitting lilypads :p (before adding this event ofc)

**Comment by Machine-Maker** [comment]
Ok @KennyTV, added that massive list you wanted.

**Review by kennytv — APPROVED** [review]
Thank you. Obviously not *ideal*, but I don't think the premise of the event is either, so the docs will help people not to bonk their head everytime they want to know where the event can be used

**Pull request merged**
