### PR TITLE
Added Support for Unix Domain Socket.

### PR DESCRIPTION
**Pull request by 0xIO32**
Added Support for Unix Domain Socket.

I already have a Pull Request on Velocity to add also support for this:
https://github.com/PaperMC/Velocity/pull/991

### CODE REVIEW

**Comment by Camotoy** [comment]
There's already a patch for Unix domain sockets; you should probably re-use that one, assuming this PR fixes up some missed changes for that patch. https://github.com/PaperMC/Paper/blob/9893e2b73438034246f79e57e7efb29757e9661e/patches/server/0623-Add-Unix-domain-socket-support.patch

**Comment by MarkusTieger** [comment]
Yes, but only with that patch, there comes an exception on login, so it requires also this patch:
[21:30:08 WARN]: Exception verifying MarkusTieger
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "io.netty.channel.Channel.remoteAddress()" is null
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:385) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleCustomQueryPacket$2(ServerLoginPacketListenerImpl.java:463) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:30:08 INFO]: com.mojang.authlib.GameProfile@776ab335[id=15a9b0a3-b679-44a6-a08c-b37428aafa07,name=MarkusTieger,properties={textures=[com.mojang.authlib.properties.Property@36bffd10]},legacy=false] (/127.0.0.1:0) lost connection: Failed to verify username!
[21:36:44 INFO]: Disconnecting com.mojang.authlib.GameProfile@4bd7fb55[id=15a9b0a3-b679-44a6-a08c-b37428aafa07,name=MarkusTieger,properties={textures=[com.mojang.authlib.properties.Property@57a87c5e]},legacy=false] (/127.0.0.1:0): Failed to verify username!

**Comment by jpenilla** [comment]
Fixes for earlier patches are generally squashed into the earlier patch rather than adding a patch for every fix. They were suggesting you squash your changes into the original patch.

**Comment by MarkusTieger** [comment]
I opened a new Pull Request: https://github.com/PaperMC/Paper/pull/9086, where i edited the patch instead of making a new one.

**Pull request closed without merging**
