### PR TITLE
Disable sending CommandMap on world changes

### PR DESCRIPTION
**Pull request by Cryptite**
Step one. Unsure if this is something we should gate behind a configuration option or not. I defer to you guys to help make that determination

### CODE REVIEW

**Comment by Brokkonaut** [comment]
Yes, I think a config option would be great

**Comment by SecretlyJealous** [comment]
I know this patch is for world change but could something similar be done for when players respawn? PacketPlayInClientCommand gets pretty bad as well in that scenario.

**Comment by zachbr** [comment]
This is going to need a config option.
May need to default to false and be an opt-in thing depending on the scope of plugin breakage.

I think @BillyGalbreath  has a version of this somewhere so perhaps he can tell us what he's seen?

**Comment by electronicboy** [comment]
This could probably do with being partially exposed in the API, I know that
I was planning to expose it for the setOp method which plugins abuse

**Review by zachbr — CHANGES_REQUESTED** [review]
Needs the configuration option

**Comment by electronicboy** [comment]
Superceeded by #2938

**Pull request closed without merging**
