### PR TITLE
Call ServerCommandEvent on Bukkit#dispatchCommand

### LINKED ISSUE #9644: Bukkit.dispatchCommand does not launch a ServerCommandEvent
### Expected behavior

Bukkit.dispatchCommand should launch a ServerCommandEvent as when typing in the console.

### Observed/Actual behavior

It doesn't launch the event.

### Steps/models to reproduce

Use Bukkit.dispatchCommand in a plugin and listen for the ServerCommandEvent. 

### Plugin and Datapack List

Server Plugins (84):
[18:26:56 INFO]: Bukkit Plugins:
- AdvancedAchievements, AfkTitle, *AntiAFK, AntiDecoCombat, AreaShop, ArmorStandTools, ASReplace, BlockLocker, BlockVillagersEnteringBoats, ChatCore
 ChatItem, ChatPing, ChestCommands, ChestShop, Citizens, CitizensText, CMILib, *CompteGroupe, CoreProtect, CrazyAuctions
CrazyCrates, CreateRank, *DabCore, DeACoudre, EffectItems, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FastAsyncVoxelSniper
FastAsyncWorldEdit, *Fe, ForceIgnore, GadgetsMenu, Grades, HolographicDisplays, IllegalStack, Insights, Jobs, LevelKeeper
Lift, LoadForce, LobbyPlayerCounter, LuckPerms, MayorRegions, MinewebBridge, MobEggDrops, ModPerms, *ModReq, MoncubeCore
Multiverse-Core, MyPet, *NaruseAPI, NoCollision, OnTime, OpenInv, *OpGuard, Plan, PlanningsEvents, PlayerHeads
PlugManX, PreventEnderChestUseBug, ProtocolLib, SchematicMover, ScoreboardHelper, *SecondThreadAPI, Shopkeepers, Skript, spark, TAB
TokenManager, Vault, Vehicles, VehiclesFlags, ViaBackwards, ViaVersion, *VillesSemi, VoidGen, VoteMoncube, WGEFixer
WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-158 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fcc5f23)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-393 (MC: 1.19.3)

### Other

I did not mark this issue as a feature request because in my opinion, it should launch an event.

### PR DESCRIPTION
**Pull request by PapiCapi**
Patches #9644 
Supersedes #9646 

I used the same plugin i used for my issue ( https://github.com/PaperMC/Paper/issues/9644 ) and now it works fine.
This is my first PR so i don't really know if i made these things right :)

### CODE REVIEW

**Comment by olijeffers0n** [comment]
Thanks for your contribution, however why are we superseding this 2 day old PR?

**Comment by A248** [comment]
An important note: this is a potentially breaking API change. Some plugins may rely on the behavior that ServerCommandEvent is *not* called by using `dispatchCommand`.

**Comment by A248** [comment]
Mhm, yes, I was considering pinging @4drian3d whose plugin SignedVelocity relies on command and chat events. However, this PR is only for the ServerCommandEvent, so that plugin will not be affected.

Other plugins might. Really, dispatching a console command is something of a universal interface between plugins, and *lots* of plugins implement features that use `dispatchCommand` to call into other plugins in certain places when timing is appropriate: shop plugins when granting purchases, skyblock plugins when completing rewards, rank plugins upon promotion or role granting, punishments with additional actions, proxy command bridging solutions, hub selector plugins when items are clicked, plus personal Skript scripts, anything. Whether any of these would rely on ServerCommandEvent not being called is unknown, but it is possible. Maybe some servers implement rate limiting or logging for console commands executed from the console, but not by other plugins.

**Comment by electronicboy** [comment]
For years theres been a general contract that API calls, outside of niche cases, will not fire events; I fail to see the argument for breaking this assertion here

**Comment by lynxplay** [comment]
Ended up closing the original issue as it right now isn't feasible to implement this way.
Thank you so much anyway for your contribution, it is greatly appreciated.

I hope we see more contributions from you in the future :)

**Pull request closed without merging**
