### PR TITLE
Only check for spooky season once an hour

### PR DESCRIPTION
**Pull request by Titaniumtown**
(This patch is from [AirplaneLite](https://github.com/Technove/AirplaneLite))
Minecraft checks to see if it's halloween pretty often, this patch makes it so "spooky season" is only checked for every hour. This is a micro optimization, but (imo) it wouldn't hurt having.

### CODE REVIEW

**Review by Proximyst — DISMISSED** [review]
LGTM. Squash & commit author will be fixed under merge.

**Comment by PaulBGD** [comment]
There should be a notice that it's GPL 3.0.

It's definitely a bigger patch than it looks, mob spawning calls this method every single time it tries to decide whether it should try to spawn a bat. When you get to >50,000 chunks this causes a lot of needless garbage due to the new instance of the LocalDate, as well as the performance hit of even calculating the localdate (which iirc has to do a bunch of weird calendar stuff.)

I also don't know what the standard is, but if you're taking copy/pasted patches from other forks maybe at least a link to them would be nice?

**Comment by Titaniumtown** [comment]
@PaulBGD I have given you proper credit now and a notice of where the patch originally came from and that it's licensed under GPLv3.

**Comment by PaulBGD** [comment]
Looks good!

**Comment by VADemon** [comment]
Good find, but there's more than just Bats. I'm probably going to also make it an event while at it. I had no idea before there're actually "two different" helloween seasons.

**Review by electronicboy — APPROVED** [review]
The patch itself looks fine, however, we've never linked to forks before as there is the expectation that they're provided on merit rather than "check us out", especially not too comfortable linking towards what appears to be a potentially paid product...

**Comment by HexedHero** [comment]
Don't skeletons also check for Halloween on spawn too? It's not just bats IIRC.
Edit: Turns out most mobs do?

**Comment by VADemon** [comment]
> Don't skeletons also check for Halloween on spawn too? It's not just bats IIRC.
Edit: Turns out most mobs do?

SkeletonsAbstract, Zombies (and all inheritances) and Bats. I'll push the patch in a few to get comments

**Comment by PaulBGD** [comment]
> The patch itself looks fine, however, we've never linked to forks before as there is the expectation that they're provided on merit rather than "check us out", especially not too comfortable linking towards what appears to be a potentially paid product...

Just to start, it's a free fork under GPL 3 and always will be. I obviously can't require you to include a link to it, but it would be annoying to see a patch copy/pasted from my fork that doesn't even credit the fork it's copied from.


> > Don't skeletons also check for Halloween on spawn too? It's not just bats IIRC.
> > Edit: Turns out most mobs do?
> 
> SkeletonsAbstract, Zombies (and all inheritances) and Bats. I'll push the patch in a few to get comments

Nice PR! That's probably the preferred PR, although I can't say I've ever seen the checks in zombies/skeletons to show up in the profiler. I imagine bats are mostly bad because of how often it tries to spawn them.

**Comment by Titaniumtown** [comment]
I will close this PR in favor of #4947

**Pull request closed without merging**
