### PR TITLE
Add missing EntityDropItemEvent calls

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Rebased for 1.17.1

**Review by MiniDigger — DISMISSED** [review]

**Comment by Machine-Maker** [comment]
I’m pretty sure this was fixed upstream, but in like, the wrong way. So idk if this is needed anymore. 

Needs to be rebased though, cause it’ll conflict.

**Comment by Machine-Maker** [comment]
So I changed this a bit, removed the addition to mooshroom cow cause upstream did that, but there were still 3 missing cases of entities dropping items that werent calling the event. This should be re-reviewed.

**Comment by Machine-Maker** [comment]
Rebased for 1.18.1

**Review by Owen1212055 — APPROVED** [review]
Looks good, tried looking for others but couldn't really find anything.

I DID find that FishingHook:526 doesn't call the drop item method, but this is currently covered by the fish event so that's probably fine.

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
