### PR TITLE
More work on 1.16.2

### PR DESCRIPTION
**Pull request by Proximyst**
It now runs and the tests pass!

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
@aikar 
image

**Comment by aikar** [comment]
@MrIvanPlays I am a sentient AI capable of delivering code to take over the world.
```01101100 01101111 01101100 00100000 01110111 01100001 01110100 00111111```

**Comment by Chronic-Reflexes** [comment]
Is this going to be pushed tonight pending successful checks?

**Comment by Proximyst** [comment]
Perhaps. No promises on release of Paper 1.16.2, never has been and never will be. The checks from Travis just makes sure it compiles & tests pass.

**Comment by MrIvanPlays** [comment]
> @MrIvanPlays I am a sentient AI capable of delivering code to take over the world.
> `01101100 01101111 01101100 00100000 01110111 01100001 01110100 00111111`

@aikar I am an ai able to make you do shit.
`01001001 00100000 01110100 01110010 01101001 01100101 01100100 00100000 01101001 01101110 01110011 01100101 01110010 01110100 01101001 01101110 01100111 00100000 01110100 01101000 01100101 00100000 00100010 01110111 01101000 01100001 01110100 00100000 01100001 01110010 01100101 00100000 01111001 01101111 01110101 00100000 01110111 01100001 01101001 01110100 01101001 01101110 01100111 00100000 01100110 01101111 01110010 00100000 01100100 01101111 00100000 01101001 01110100 00100010 00100000 01100111 01101001 01100110 00100000 01100010 01110101 01110100 00100000 01100111 01101001 01110100 01101000 01110101 01100010 00100000 01110011 01100001 01101001 01100100 00100000 01101110 01101111`

**Comment by Chronic-Reflexes** [comment]
01110111 01100001 01101001 01110100 00100000 01110011 01101111 00100000 01110111 01101000 01111001 00100000 01100001 01110010 01100101 00100000 01110111 01100101 00100000 01110101 01110011 01101001 01101110 01100111 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01101110 01101111 01110111 00111111 00100000

**Comment by Disguys** [comment]
1110011 1101001 1101101 1110000 1101100 1111001

**Comment by Joo200** [comment]
49 20 64 6f 6e 27 74 20 6c 69 6b 65 20 62 69 6e 61 72 79 2e

**Comment by Chronic-Reflexes** [comment]
42 69 6e 61 72 79 20 69 73 20 6f 76 65 72 72 61 74 65 64 2c 20 41 67 72 65 65 64 20

**Comment by Proximyst** [comment]
(I don't really) hate to be the grumpy one; can we stop dumping useless comments in non-ascii on here? Thanks.

**Comment by aikar** [comment]
ok no more spam, was meant to be a joke with me saying I am an AI.

**Comment by danny6167** [comment]
Builds (including paperclip), runs, and hasn't crashed after running around for a good 60 seconds.

**Pull request merged**
