### PR TITLE
Add history file for terminal

### PR DESCRIPTION
**Pull request by mio-19**

### CODE REVIEW

**Review by aikar — APPROVED** [review]
Oh that's cool idea! I've always wanted this, no idea it was so easy!

I would prefer it merge into the Terminal Appender patch, but I can handle that at merge.

**Comment by mikroskeem** [comment]
Probably should use .paper_history as file name, similar to what e.g shells or other repl programs do (.bash_history etc)

**Comment by mio-19** [comment]
@mikroskeem Those files are named like that because they are in the `$HOME` directory

**Comment by Proximyst** [comment]
There is no reason not to adhere to the norm nonetheless, no?

**Comment by aikar** [comment]
Manually merged https://github.com/PaperMC/Paper/commit/b2afcf1194f673c6609e793895aaa20d60433dcd

In future please use a personal repo and not org repo for PR's
see: https://github.com/PaperMC/Paper/commit/ab2e8a853c58ed3f4a3ab2a41368adfaf073d8ac

**Pull request closed without merging**
