### PR TITLE
Fix long loading screen when refreshing skins

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
The main necessary change was to send:
```java
new ClientboundGameEventPacket(ClientboundGameEventPacket.LEVEL_CHUNKS_LOAD_START, 0.0F)
```
to do this I call `sendLevelInfo`, which is called by respawn and dimension teleport and has also this packet as a side-effect.

I also made the respawn packet code smaller.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
Now it also resends the right permission level set in ops.json for the few people that actually use that "feature".

**Review by Machine-Maker — APPROVED** [review]

**Comment by envizar** [comment]
Merge this please, this long loading screen is so annoying

**Comment by Fedeasd** [comment]
it happens to me

**Review by Owen1212055 — APPROVED** [review]

**Comment by Xemorr** [comment]
Is there a known way to completely mitigate the loading screen like pre 1.20.4 behaviour?

**Pull request merged**
