### PR TITLE
Fix calling Player#chat asynchronously

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Review by Spottedleaf — CHANGES_REQUESTED** [review]
This changes command handling behaviour.

You need to clarify what fixing this is even supposed to do

**Comment by electronicboy** [comment]
This fixes an issue where tryna chat off the main thread in a plugin causes an exception down the chain, that async boolean in retrospect is kinda dumb, maybe make it so that async is only set to true if off the main thread and the string doesn't start with a "/" is the "quick" fix for this i think

**Comment by Spottedleaf** [comment]
The correct fix to that is to throw an exception immediately. The async chat event is defined to be synchronous for the fake player chat calls, so there's no option here to make this work.

**Comment by Machine-Maker** [comment]
Oh that's described on the old deprecated javadoc for AsyncPlayerChatEvent. That should probably be put on the adventure event as well...

**Pull request closed without merging**
