### PR TITLE
Updated Upstream (Bukkit/CraftBukkit/Spigot)

### PR DESCRIPTION
**Pull request by Machine-Maker**
Upstream has released updates that appear to apply and compile correctly. This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
96340858 PR-938: Various Sound API improvements
cbfe0ff0 PR-937: Minor improvements to World#rayTrace documentation
e979ee95 PR-935: Change Consumer and Predicates to super
27ae46dc SPIGOT-3641, SPIGOT-7479, PR-931: Add missing values to EntityEffect
0616ec8b Add eclipse .factorypath file to .gitignore

CraftBukkit Changes:
8e162d008 PR-1301: Various Sound API improvements
eeb7dfc2d SPIGOT-7520: Attribute LootTableSeed missing for generated containers with attached LootTable d433f086d PR-1297: Change Consumer and Predicates to super
864f616da SPIGOT-7518: Fix NullPointerException when calling Block#applyBoneMeal()
5a2d905af Add eclipse .factorypath file to .gitignore
7c6bf15d4 Fix SkullMeta configuration serialization / deserialization with note block sound

Spigot Changes:
7de1049b Rebuild patches

### CODE REVIEW

**Comment by Phoenix616** [comment]
Spigot has merged the virtual entity API now. Any chance this can be updated to directly include it or do you want to keep that separate?

**Comment by Machine-Maker** [comment]
> Any chance this can be updated to directly include it or do you want to keep that separate?

I really want to wait as long as possible before adding this. It is a poorly designed system with many flaws. It exposes "not-in-world" entities in new event calls that will be unexpected to plugins, the API itself does not care at all about cancelled spawn events, and I'm sure a dozen other problems with specific entity events that will not throw exceptions, but have bad behavior if called on a not-in-world entity.

**Comment by Phoenix616** [comment]
I see. Kinda sad that wasn't put forward on the original PR :S

**Review by kennytv — APPROVED** [review]

**Comment by MiniDigger** [comment]
> I see. Kinda sad that wasn't put forward on the original PR :S

thats what happens if you close PRs to the public 🤷

**Comment by Phoenix616** [comment]
> > I see. Kinda sad that wasn't put forward on the original PR :S
> 
> thats what happens if you close PRs to the public 🤷 

Don't say it as if you don't know that it's not intentionally like that. (For anyone who doesn't know: It's a limitation with Stash's permission system, it was not a choice to not make them publicly visible)

And I am sure most relevant people have access anyways...

**Comment by MiniDigger** [comment]
> > > I see. Kinda sad that wasn't put forward on the original PR :S
> > 
> > 
> > thats what happens if you close PRs to the public 🤷
> 
> Don't say it as if you don't know that it's not intentionally like that. (For anyone who doesn't know: It's a limitation with Stash's permission system, it was not a choice to not make them publicly visible)
> 
> And I am sure most relevant people have access anyways...

I always have and always will disagree with that argument. Any organization on github (which has the same limitation) that enforces CLAs just has a bot to check CLAs

but this is offtopic

**Pull request merged**
