### PR TITLE
Houston, we got a patch

### PR DESCRIPTION
**Pull request by MiniDigger**
another ~50 done
next up is oversized chunks stuff so I rather have somebody else look at that

plus, my boss is yelling that he wants me at work 😂

### CODE REVIEW

**Comment by MiniDigger** [comment]
(includes #2730)

**Comment by WesleyVanNeck** [comment]
When does it compile ? Or at least not fail

**Comment by Draycia** [comment]
when all of the patches are either dropped or fixed

**Comment by MiniDigger** [comment]
just because all patches apply doesnt mean that it will compile. I bet there will be still work needed because of locX -> locX() changes that might apply cleanly without us noticing. 

no eta ;)

**Review by electronicboy — APPROVED** [review]

**Comment by MiniDigger** [comment]
had to drop a bunch of chunk related patches still we figure out how to deal with oversized stuff

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
