### PR TITLE
shellcheck testServer.sh

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by MiniDigger** [comment]
have you tested this on multiple different systems?

**Review by Proximyst — APPROVED** [review]
LGTM.

@MiniDigger: All of the changes are POSIX compatible, so *any* UNIX-based system (Linux, BSD, macOS, probably MinGW) should be 100% okay with them.

**Comment by electronicboy** [comment]
Still needs testing, we've had many cases where stuff "should" be okay and isn't for varying reasons, e.g. one distro using a 10 year old version of something *looks at macOS*

**Comment by Machine-Maker** [comment]
Well the change's don't cause any errors on my mac, but the original doesn't seem to work either. tmux/screen just exit out right after running their respective commands. idk what's going on there, but it doesn't have anything to do with the changes.

**Comment by Chew** [comment]
Tested on my "10 year old version of something" device.

Issues (not related to PR):

When prompted to accept EULA, this was the formatting:
```
\e[32m  It appears you have not agreed to Mojangs EULA yet! Press \e[1;33my\e[m \e[32mto confirm agreement to
  Mojangs EULA found at:\e[1;32m https://account.mojang.com/documents/minecraft_eula \e[m 
```
After hitting Y, it loads for a second then the screen just terminates...

To be fair, this is exactly what happens on other the current script anyway.

Don't mind us Mac users, no *new* issues arised.

**Comment by electronicboy** [comment]
This file no longer exist

**Pull request closed without merging**
