### PR TITLE
Fix PotionSplashEvent for water splash potions

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes [SPIGOT-6221](https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6221)

Splash water bottles do affect some entities that take damage from water, like enderman, snow golems, blazes, etc.

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]
approving so that somebody else can merge in the future, as this generally looks fine

only concern I have is over the intensity, that's defined as 0-1 in the event so that value given is wrong in this event, I would probably just use the existing logic or maybe hardcode 0 for intensity given that water has no effects otherwise

**Comment by Machine-Maker** [comment]
@electronicboy I think I disagree with that. The intensity is 1, because any entity regardless of distance from the actual splash, if affected by the water potion will be affected the same amount. Setting it to 0 means it wont be affected at all which isn't true for the entities in the event.

**Comment by electronicboy** [comment]
there's no side-effect of being impacted by this was my thing, e.g. no enchants added, etc

**Comment by Machine-Maker** [comment]
But this potion does affect entities, and setting it to 0 suggests that it doesn't affect entities which isn't true.

**Comment by electronicboy** [comment]
There is no potion effects from a water potion is what I'm saying, 0 was just what I thought given that there are no real impacts bar the damage that it triggers? Beyond that, copy the code from below which calculates the amplifier so that it sticks in the 0-1 range

**Review by kennytv — APPROVED** [review]
Fixed the intensity for you (forgot to rebase tho),
pufferfish

**Pull request merged**
