### PR TITLE
[ci skip] fix run dev

### PR DESCRIPTION
**Pull request by MiniDigger**
🤷‍♂️

### CODE REVIEW

**Comment by MiniDigger** [comment]
(also turned filterpatches back on)

**Review by jpenilla — CHANGES_REQUESTED** [review]
we should fix FilterProjectDir on windows instead

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/paperweight/pull/214

**Comment by Leguan16** [comment]
Shouldn't this happen anyway? 
```diff
-tasks.withType<io.papermc.paperweight.tasks.RebuildGitPatches> {
-    filterPatches.set(false)
-}
+// tasks.withType<io.papermc.paperweight.tasks.RebuildGitPatches> {
+//     filterPatches.set(false)    
+// }
```

**Pull request closed without merging**
