### PR TITLE
Reduce snow sync loads

### PR DESCRIPTION
**Pull request by MiniDigger**

### CODE REVIEW

**Comment by kickash32** [comment]
Will this actually reduce sync loads? Its just trying to get a block above, which shouldn't load the chunk since it should be loaded already?

**Comment by ninja-** [comment]
@kickash32 PR suggests he found it from sync load logs, which would be even more weird

**Comment by electronicboy** [comment]
would need to see said sync load log, this shouldn't be possible to induce a load unless it's going on in some oddball phase maybe

**Comment by electronicboy** [comment]
Closing, this shouldn't be inducing chunk loads whatsoever, if it somehow is, a full report would be needed as this would more describe a deeper issue somewhere, not something this would actually address

**Pull request closed without merging**
