### PR TITLE
Resolve Plugin Dependency Issues, Improve PluginLoading Compat, Small Loading Issues

### LINKED ISSUE #8971: Paper fails to load plugins with dependencies through API
### Expected behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) the plugin's dependencies should be checked against the plugins that are currently loaded on the server, and be permitted to enable if present.

### Observed/Actual behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) paper says the dependencies of the plugin being loaded are missing (even if they are not) and fails to enable the plugin. 

### Steps/models to reproduce

1. Create a plugin that can load another plugin from an addons folder
2. Create another plugin that depends on the first plugin
3. Place the second plugin in the first plugins addon folder
4. Load the second plugin from the addons folder (through a command or something) using Bukkit.getPluginManager().loadPlugin(file)
5. You will receive an error like this https://pastebin.com/DLYc6Q6n

### Plugin and Datapack List

- MBedwars (Our plugin)
- ExtraSpectialItems (The plugin being loaded from an addons folder of MBedwars)
- PlaceholderAPI

### Paper version

[23:40:59 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36) You are running the latest version
Previous version: git-Paper-399 (MC: 1.19.3)

### Other

We have been using this API for close to a year now, and was working great until a fairly recent Paper update. I believe the API was broken in Paper's move to their own plugin system, as it works fine on the latest spigot version. Let me know if you would like me to test anything, or need more detailed info. Thanks everyone!

### PR DESCRIPTION
**Pull request by Owen1212055**
Supercedes: https://github.com/PaperMC/Paper/pull/9005
Fixes: https://github.com/PaperMC/Paper/issues/8971, https://github.com/PaperMC/Paper/issues/9057

Pass dependency tree when loading, this allows us to correctly resolve dependencies when loading while plugins already in the plugin manager.

---
Download the paperclip jar for this pull request: [paper-9068.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/632461220.zip)

### CODE REVIEW

**Comment by Owen1212055** [comment]
This is now ready for review.

This now fixes symbolic link issues + dotted prefixes loading.
For those who had issues with dynamically loading plugins during runtimes throwing dependency errors, PLEASE test this PR.

**Comment by MetallicGoat** [comment]
Test build posted in this pr works like a charm! Addons for our plugin now load without any issues. Thanks @Owen1212055 !

**Comment by pabloalba16** [comment]
thanks for the pr! now mbedwars loads fine for me

**Review by electronicboy — APPROVED** [review]

**Comment by CloudeLecaw** [comment]
https://github.com/TheBlackEntity/PlugMan/pull/10

**Comment by Owen1212055** [comment]
This has been tested to confirm that this does resolve issues related to plugman.

**Comment by SlimeDog** [comment]
Might have broken something. See https://github.com/Andre601/AdvancedServerList/issues/81

**Comment by CloudeLecaw** [comment]
> Might have broken something. See [Andre601/AdvancedServerList#81](https://github.com/Andre601/AdvancedServerList/issues/81)

na this logs more like a placeholder api issie

**Comment by bergerkiller** [comment]
Yes this broke my plugin loading a protocollib class, too.

**Comment by Owen1212055** [comment]
This caused some issues with paper plugin dependency loading and will propetly looked into in a future PR. 👍

**Comment by SlimeDog** [comment]
Verified fixed with reversion of the changes in Paper 1.19.4-507. Thanks.

**Comment by MiniDigger** [comment]
that CMI error is unrelated to plugin loading, upstream changed internals, plugin that use internals to respawn stuff instead of the api will break because of that, the fix is to no longer use internals

**Comment by Owen1212055** [comment]
The skin list not showing and the CMI issues are not related to this PR in any way.

**Comment by CloudeLecaw** [comment]
i still hope the find a solution in current build the issue is back Build 509

```
[22:46:58] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/MobFarmManager_2.0.4.2.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [CMILib]. Please download and install these plugins to run 'MobFarmManager'.
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:80) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[paper-1.19.4.jar:git-Paper-509]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:355) ~[PlugManX_2.3.2.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX_2.3.2.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX_2.3.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-509]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2250) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:46:58] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/MobFarmManager_2.0.4.2.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [CMILib]. Please download and install these plugins to run 'MobFarmManager'.
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:80) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[paper-1.19.4.jar:git-Paper-509]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.19.4.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:367) ~[PlugManX_2.3.2.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX_2.3.2.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX_2.3.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-509]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2250) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-509]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:46:58] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?
[22:46:58] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:127)
[22:46:58] [Server thread/WARN]: 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[22:46:58] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:127)
[22:46:58] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)
[22:46:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406)
[22:46:58] [Server thread/WARN]: 	at PlugManX_2.3.2.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:367)
[22:46:58] [Server thread/WARN]: 	at PlugManX_2.3.2.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116)
[22:46:58] [Server thread/WARN]: 	at PlugManX_2.3.2.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98)
[22:46:58] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:46:58] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[22:46:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906)
[22:46:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[22:46:58] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2290)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2250)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[22:46:58] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[22:46:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[22:46:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by CloudeLecaw** [comment]
so will there be a new "fix" that we could load aggain the plugins? or do we need to stay at the Build 506 now? ;O

**Comment by MiniDigger** [comment]
yes, we obviously still want to fix the issue that this PR aimed to address (notice how the issue was reopened after the revert of this PR), but due to the complicated nature of all this, we will not rush it. 
once we have a new solution, we will present test builds and will ask for feedback again.

**Pull request merged**
