### PR TITLE
Remove "Don't tick Skulls" patch

### PR DESCRIPTION
**Pull request by phase**
This patch removes ITickable from TileEntitySkull, which looks unneeded, when it is actually used for Dragon Heads. Without ITickable, Dragon Heads aren't affected by redstone like they are in Vanilla.

### CODE REVIEW

**Comment by willies952002** [comment]
for me the dragon head is still affected by redstone even without ITickable :|

**Comment by phase** [comment]
And so it does... I think it's ticking it client-side or something. If the server is sending the updates to the client, then removing ITickable should affect custom clients. Closing this for now, as no one actually uses custom clients.

**Comment by aikar** [comment]
the code never does anything on the server. the logic to do the animation is purely client side. So this server change wouldn't even affect custom clients.

**Comment by phase** [comment]
Ah, gotcha.

**Pull request closed without merging**
