### PR TITLE
Add disable-usercache-saving setting

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by aikar** [comment]
What condition would you ever want to turn this off? Note for performance paper has fixed saving causing lag by moving it to be async.

**Comment by sgdc3** [comment]
Scenario:
offline mode server that restarts after every game (minigame server) with tons of different players playing.
It's useless in this situation. :)

**Comment by aikar** [comment]
the cache shouldnt be used in offline mode i dont think. The cache is all about cacheing lookups for online mode

does something make you believe this is being utilized a lot in offline mode? those uuids are based on player name

**Comment by sgdc3** [comment]
xD Spigot even if in offline mode creates and USES the file to store useless UUIDs. I think you known that.

**Comment by sgdc3** [comment]
Wait, i think this cache is still there in order to allow caching uuid requests from bungeecord in the case bungee is in online mode.

**Comment by sgdc3** [comment]
So the only solution is to keep this configurable.

**Comment by sgdc3** [comment]
How quick is the username to UUID hashing?

**Comment by aikar** [comment]
This isn't going to really achieve anything, since an offline server shouldn't even be making lookups.

This isnt going to stop the look ups, only abort saving them, which if it is looking up like I think it is, not saving them will hurt your performance as the point of the cache.

So if anything needs to be changed, its to ensure offline mode doesn't actually do lookups (and therefor doesnt cache), not anything to do with aborting the save.

**Comment by sgdc3** [comment]
I'm sure that an offline-mode server doesn't contact mojang api but i'm also sure that the usercache.json file is still being used to store offline uuids (UUIDs generated using the player name). My question now is: could we disable the usercache completely on offline mode servers or it would cause performance issues (due to the username to offline UUID convertion)?

**Comment by aikar** [comment]
Why do you perceive it as a problem? It only saves a limited # of entries to disk. 

What problem are you experiencing, so we can tackle that correctly.

This feels like the wrong solution to what ever problem you are seeing, and id rather us not clutter up the config file with a setting that will very likely only be changed by you.
When we add something to a config file, it makes people wonder if they change it ,and we could end up with misinformation spreading telling people to disable it with bad consequences.

**Comment by aikar** [comment]
another thing Z750 just mentioned, this is already doable by setting spigot.yml user cache cap to 0.

So im going to close this, but feel free to join us on IRC to discuss other ideas for improvements around whatever issue made you think this would help.

There may be room for improvement, but this doesn't seem to help anything.

**Comment by jiongjionger** [comment]
One more question, usercache is no help to offine mode? @aikar

**Comment by sgdc3** [comment]
@aikar I didn't know that, thank you ;)

@jiongjionger It seems to be useless in offline mode, yes.

**Pull request closed without merging**
