### PR TITLE
Actually fire GS4QueryEvent

### LINKED ISSUE #4864: GS4QueryEvent doesn't get called
Hello, it seems the GS4QueryEvent doesn't get called

### Steps/models to reproduce:
```kotlin
override fun onEnable() {
  super.onEnable()

  server.pluginManager.registerEvents(this, this)
}

@EventHandler
fun onquery(e: GS4QueryEvent) {
  println("queried")
}
```

    $ pip install mcstatus
    $ mcstatus localhost query

### What behaviour is expected:
See a debug message

### What behaviour is observed:
Nothing

### Plugin list:
Only my test plugin

### Paper version:
latest (1.16.4 b318)

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Fixes #4864

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Should this go back in somewhat the same order? Idk what the policy of re-adding in removed commits.

**Comment by MrIvanPlays** [comment]
> Should this go back in somewhat the same order? Idk what the policy of re-adding in removed commits.

it doesn't matter.

**Review by JRoy — CHANGES_REQUESTED** [review]
this adds obfhelpers for a reason, please use them

**Comment by electronicboy** [comment]
Ideally, we keep patches near one another, it doesn't matter until it does

**Comment by MrIvanPlays** [comment]
> this adds obfhelpers for a reason, please use them

wdym they are used

**Comment by Machine-Maker** [comment]
> wdym they are used

Think you are missing some uses of `getCachedFullResponse`

or actually maybe not? I was looking at the diff and it was kinda hard to read. idk

**Comment by MrIvanPlays** [comment]
um do you both know how diffs work? if its not prefixed with + its the original mojang code. why should i modify something when it doesnt need to be modified?

**Comment by Machine-Maker** [comment]
It's possible JRoy is talking about using obfhelpers in the big commented out section where paper just adds the block comment symbols before and after it minimizing diff. just guessing tho

for instance, [this line](https://github.com/PaperMC/Paper/pull/4874/files#diff-5149563289bdfeb940406d57c1967d0c14ad6bb8e8bc4efcd68c71de6bb18c15R78)

**Comment by JRoy** [comment]
> It's possible JRoy is talking about using obfhelpers in the big commented out section where paper just adds the block comment symbols before and after it minimizing diff. just guessing tho
> 
> for instance, [this line](https://github.com/PaperMC/Paper/pull/4874/files#diff-5149563289bdfeb940406d57c1967d0c14ad6bb8e8bc4efcd68c71de6bb18c15R78)

was half awake making that comment, didn't see it was commented, my bad. 

Also, thanks for the pro tip about diffs ivan, if you have any more pro tips please forward them to to mail@devnull-as-a-service.com

**Comment by TheDevMinerTV** [comment]
LGTM

Please patch this back in, we need to remove some plugins from the query results.

**Review by zachbr — DISMISSED** [review]

**Review by MiniDigger — DISMISSED** [review]

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
