### PR TITLE
Add API for retreiving the itemstack used to launch a projectile

### LINKED ISSUE #1937: Obtain ItemStack from Trident entity
**Is your feature request related to a problem? Please describe.**
I would like to make it so loyalty tridents return to the player when they fall in the void or are destroyed by other possible means. Currently, it's difficult to obtain the ItemStack of the Trident entity and seemingly impossible without using NMS. Reflection may also be required to gain visibility of required methods.

**Describe the solution you'd like**
Add a method `getItemStack()` to the Trident entity or an alternate method to obtain the thrown Trident's original ItemStack.

**Describe alternatives you've considered**
N/A

**Additional context**
Was told to file the request by @BillyGalbreath so he can implement it

### PR DESCRIPTION
**Pull request by Spottedleaf**
Note that we will have to watch out for new projectiles / new code to launch projectiles on updates. 

Should resolve #1937

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
Dude, you are terminator! So much PRs

**Comment by Cryptite** [comment]
It may be beyond the scope of this PR, but it would be very nice (and also consistent) if the equivalent of `PlayerElytraBoostEvent`'s `setShouldConsume()` method was brought over to ProjectileLaunchEvent. Very useful if you want things like infinite enderpearling, etc.

**Comment by Spottedleaf** [comment]
That is beyond the scope of this patch

**Review by aikar — CHANGES_REQUESTED** [review]
since bukkits projectile doesnt match nms's, i rather us not put it on abstract, and use an interface instead and just tack it on the ones it is actually applicable to.

**Comment by aikar** [comment]
Maybe something like LaunchedProjectile? and getLaunchingItem

**Pull request closed without merging**
