### PR TITLE
Add option to flush region files on save

### PR DESCRIPTION
**Pull request by Redned235**
Solves #9142. 

I added a config option for this in the event the existing behavior is preferred, however I'm not entirely if this is the best option given vanilla by default will call this same method to flush the region files. Feedback welcome!

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by BillyGalbreath** [comment]
Ok, I can confirm this fixes the problem as reported (fixes `/save-all flush`).

However, there still is no FileWatcher activity on the autosave interval, until I open another terminal and `ls` the region directory again. Possibly this is one of the 3 spots I mentioned above?

**Comment by Redned235** [comment]
> About to give this a run to see if it fixes the problem.
> 
> Any reason you only added the extra flush to this one spot and not the other 3 spots where `RegionFileIOThread.flush();` are present? ([here](https://github.com/PaperMC/Paper/blob/master/patches/server/0018-Rewrite-chunk-system.patch#L3719), [here](https://github.com/PaperMC/Paper/blob/master/patches/server/0018-Rewrite-chunk-system.patch#L5638), and [here](https://github.com/PaperMC/Paper/blob/master/patches/server/0018-Rewrite-chunk-system.patch#L17175))

For the first two, the region files are already calling the RegionFile#close method which flushes to disk as well (first one also has no world context available as it’s static). The third method is unused within the codebase so I didn’t see it necessary to add this code there. 

I’ll double check the auto saving since I’m not sure if it flushes by default in vanilla.

**Comment by Redned235** [comment]
After checking vanilla, it does not appear the auto saving flushes there either.

**Comment by BillyGalbreath** [comment]
Interesting, I didn't know vanilla had auto saving now. I thought that was a Bukkit thing.

I wonder if we should add an option to flush on autosaves since we're here.

**Comment by Redned235** [comment]
Yea an option for flushing on auto save wouldn't be a bad idea. On second thought I'm wondering if it's best to remove the current flushing option and have it always flush the region files when `flush` is true (i.e. in `/save-all flush`), since this is consistent with vanilla & Spigot. Then we can have a different option for flushing on auto saves. Curious on what others think about this.

**Review by Owen1212055 — APPROVED** [review]

**Pull request merged**
