### PR TITLE
Fix Important Crash Issue With Custom Generator World (Datapack/Plugins)

### LINKED ISSUE #6028: TreeFeature crash
### Expected behavior

Chunky just generates world properly.

### Observed/Actual behavior

Chunky crashes server after a while.

### Steps/models to reproduce

1. Get Terra as new world generator.
2. Start server
3. Start chunky
4. Wait (5-10 minutes)
5. Server crashes

### Plugin list

Terra, Chunky

### Paper version

Build #55

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Crash log: https://hastebin.com/wapanopuwo.yaml

### PR DESCRIPTION
**Pull request by Euphillya**
Fix PaperMC#6028

### CODE REVIEW

**Comment by electronicboy** [comment]
That is only one of the several dozen of these, and I question why we're getting an empty list here, this doesn't seem like a real fix?

**Comment by Euphillya** [comment]
In fact, in the TreeFeacture.java file, the condition: 
```Java
if (bl && (!set.isEmpty() || !set2.isEmpty())) {
```
asks if one or the other is empty, set2 is not empty but "set " happens to be. We can limit ask to check the 2 at the same time.

**Comment by electronicboy** [comment]
Yarn shows that as
```java
        if (!bl || set.isEmpty() && set2.isEmpty()) {
            return false;
        }
```
Which looks more accurate to the intent there, yay decompilers...

I'm somewhat confused on this one, are there any "trees" without leaves? Some of the populators seem to care about that though, which makes me wonder about some of the reports, is something borking up the chain I wonder

**Comment by Euphillya** [comment]
With datapacks and plugins that change the generation of biomes, it is possible to have trees without leaves as in my case that I had with my server (datapack).

**Comment by Euphillya** [comment]
I discovered that the bug is also on the file: CocoaDecorator, therefore changing the condition is much better directly.

**Comment by Euphillya** [comment]
up

**Comment by electronicboy** [comment]
I'm still not sure that this is actually a correct fix, does tree gen still work properly with this? For me, this screams that it would prevent generation in cases for trees which don't have leaves and logs, which while it would fix the crash, it would prevent those things from generating

(Standard vanilla trees would be fine, but, the trees which trigger this crash won't be generated as the logic is not being ran, the sad truth here is that the best option is probs to fix the actual issues)

**Comment by Euphillya** [comment]
Since apparently this is not the right solution, I close this PR.

**Pull request closed without merging**
