### PR TITLE
Add BANNERS Material Tag

### PR DESCRIPTION
**Pull request by Insprill**

### CODE REVIEW

**Comment by lynxplay** [comment]
https://jd.papermc.io/paper/1.19/org/bukkit/Tag.html#BANNERS and https://jd.papermc.io/paper/1.19/org/bukkit/Tag.html#ITEMS_BANNERS already exist.

I don't see a point in this PR.

**Comment by Insprill** [comment]
There are quite a few MaterialTags that also exist in Bukkit's Tag like beds, signs, and coral.
But, I suppose it's just me being a bit too picky and wanting my tags to be from one place haha.

**Comment by lynxplay** [comment]
Those exist because paper was faster than spigot/mojang 😛 So paper basically added the BEDS tags and stuff when spigot hasn't/minecraft didn't have those as tags in the first place.

Spigot or mojang then caught up leading to the doubled tags.

**Comment by Insprill** [comment]
I see, thank you!

**Pull request closed without merging**
