### PR TITLE
Maded Title-Objects directy sendable to receivers

### PR DESCRIPTION
**Pull request by TheFruxz**
Hey, I closed my old ACTIVE PR and I opened this new PR to fix my errors and corrections from the last one and thus add the feature. From the last PR ( #4628 ):

> Hey!
> 
> This is my first submission of a change to PaperMC/Paper (API).
> 
> I myself think that title objects should also be sent by themselves (like in ParticleBuilder). Therefore I made this suggestion for improvement.

Thank you very much for your support and thank you for the feedback as these are my first PRs.

With kind regards
Fruxz (@TheFruxz)

_Special thanks to @Proximyst_

### CODE REVIEW

**Comment by TheFruxz** [comment]
Hey, I hope it was okay to close the old PR and create a new PR with revised commits, since the previous repo no longer existed, so this was the easiest fix for me.

**Comment by electronicboy** [comment]
This would need to go in the patch which added the Title class, no reason this needs to be a separate patch

**Review by Proximyst — DISMISSED** [review]
We can handle fixup when merging (cc. @MiniDigger).

**Comment by TheFruxz** [comment]
> We can handle fixup when merging (cc. @MiniDigger).

I would be very happy, thank you very much for your assistance.

**Review by electronicboy — DISMISSED** [review]

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Comment by MiniDigger** [comment]
thank you for your contribution!

**Pull request merged**
