### PR TITLE
Updated Paper Config

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Updated Paper Config, removed redundant Patrol Spawning Option and added 2 more, 1 combat related and another Survival Related

Note: This Commit also involves the associated implementations aside from just patching the PaperWorldConfig class

### CODE REVIEW

**Comment by electronicboy** [comment]
Please read the contribution guide
1) patches should be singular purpose and describe their intent
2) Modifications to older patches should be done in older patches, no modifying stuff in the latest patches
3) Attributes are really not something we should be blindly stuffing data into, there are already plugins to mangle this for you
4) `enhanced-survival-mode` in no way clarifies what the intent here is

**Comment by TheShermanTanker** [comment]
@electronicboy 
1. Wasn't the patch only changing 1 thing this time?
2. Alright, it's sort of a bad habit to just change older commits with new commits, won't do that again
3. I've experimented with that before and it works without any issues (In fact it's the only way without messing with Base Attribute values which results in nasty and broken item descriptions in game, or the ticksSinceLastSwing field, which disables the cooldown mechanic but not the cooldown animation), I just felt that it would be nice to have Paper include that as an option straight off the bat rather than needing a Plugin
4. This is actually sort of complicated since I thought it would be interesting for Paper to have a beefed up Survival Mode that could be turned on or off that gave a much better experience than normal Survival did, but since it's preferrable to not add so much in one patch I thought I would circumvent this by implementing this over the course of incremental PRs; The patch that I added included one of the features I had in mind

I will read the contribution guide again, rest assured, thanks for the feedback

**Comment by electronicboy** [comment]
1] You added two completely unrelated settings into a singular patch, (and fell into 2 there in a singular patch as well)
3] It works but it's gross, personally, this is more plugin territory as it's basically just blindly modifying items, there is no logic to say "hey, this item has a custom value, we shouldn't touch it", which is why this is not really something that's implementable in a manner that I'd consider super amazing as a config option
4] behavioral changes are murky water, having a large set of changes under one config option is also highly counterproductive, prefer singular config options/events

The nature of "too much in one patch" is subjective, 1 PR = 1 change/feature, essentially, we don't want to have 20 dozen added patch sets in one, it means everything holds everything and complicates the merge process

**Comment by TheShermanTanker** [comment]
1. Understood, I just thought Updating the Config itself counted as just one feature, lesson learnt
3. Sigh. If only Mojang made the cooldown animation able to be handled server side as well... (I guess I'll just stick to datapacks for this, should be ok)
4. Not exactly sure what you mean by behavioural changes? Although as for the one option it was kind of supposed to be a mini hardcore version, I guess I'll find another workaround then

I do have a question though can reverting parts of a previous patch be joined into one PR or does it need another PR?

**Pull request closed without merging**
