### PR TITLE
Fix jline with git builds under Windows

### PR DESCRIPTION
**Pull request by astei**

### CODE REVIEW

**Comment by VADemon** [comment]
Why not fix the underlying OS choice?

**Comment by Spottedleaf** [comment]
internally we've been aware that the quotation marks introduced by the current git describe maven plugin are an issue because jline will extract libraries using the implementation version
windows doesn't like quotation marks and the library extraction fails

this is only an issue for jars we don't distribute (so building your own unless you explicitly tag will result in issues on windows file systems)

the real issue is that the library extraction should be careful in choosing its path, but this solution works just fine

**Review by Spottedleaf — APPROVED** [review]

**Comment by astei** [comment]
@VADemon I use macOS and Linux myself, but we can't really control our users. And if you want to believe [bStats](https://bstats.org/plugin/server-implementation/Paper), then we're looking at 10.5% of our userbase, which is not insignificant.

**Comment by zachbr** [comment]
Still consider this to be a workaround, but it is a workaround that fixes the problem and should reduce the overall diff once merged back into the original patch file.

Will review this against our build processes and operating systems and go from there.

**Comment by zachbr** [comment]
Another fun fact on this issue, if you build the jars on Windows it isn't present.
> [11:18 PM] Z750: git-Paper-e8c82f4e (MC: 1.14.4)
> [11:18 PM] Z750: time to build on not windows I guess
> [11:19 PM] Z750: git-Paper-"e8c82f4e" (MC: 1.14.4)
> [11:19 PM] Z750: Java really is write once, debug everywhere

**Review by zachbr — APPROVED** [review]

**Comment by zachbr** [comment]
Happy that someone dug into this. Thanks!

**Pull request merged**
