### PR TITLE
Add Zstd/LZ4 support for region files (1.16 edition)

### LINKED ISSUE #4735: Feature Request: Disabling world compression
There should be an option that lets you disable compression on the world. This would be useful in scenarios where ZFS (or similar) compression is used on the filesystem the world/server is stored on. Both the world and filesystem being compressed is redundant and unnecessary in those scenarios, and I would imagine would cause the machine to attempt to compress the already compressed world files, using more cpu without any benefits.

**Describe the solution you'd like**
A config option in paper.yml to disable world compression. This could possibly tie into #4715 where the config option that would specify compression type in that PR could be set to either `off`, `disabled`, or `none`.

### PR DESCRIPTION
**Pull request by egg82**
Zstd using zstd-jni: https://github.com/luben/zstd-jni
LZ4 using lz4-java: https://github.com/lz4/lz4-java

Added new command-line option, --forceWrite, which will forcibly write the chunk/flush to disk regardless of whether or not the chunk has actually changed in a --forceUpgrade.
New compression only happens when a chunk is saved, so running a --forceUpgrade AND --forceWrite may be desirable.

New (hidden) config option for the compression method to use.
There's a new option in PaperConfig (compression level) for Zstd which defaults to 6.
There's a new option in PaperConfig (compression level) for Zlib which defaults to 5.
Added a getter to the API to retrieve the current chunk compression method being used.

Since the patch hooks Mojang's versioning system for new compression methods, it
should be internally consistent, easily-updatable, and reversible with a --forceUpgrade AND a --forceWrite.

This will likely conflict with plugins and programs expecting region files to be compressed using the current standard.

Supercedes #2814

**TODO**
- [x] Test it to make sure it actually works
- [x] Add API getter for current Zstd dict version
- [x] Update to 1.16.4 (why does this happen every time?)

### CODE REVIEW

**Comment by schoentoon** [comment]
Perhaps it'd be an idea to have another look at #4192 around the same time this would get merged, as these two pull requests would likely benefit from each other.

**Comment by Titaniumtown** [comment]
Bump! Is there going to be more work on this any time soon? I'm really excited for the benefits a patch like this could add! Of course no rush, you guys are doing this for free of course, but I just wanted to check in and see if anything has changed :)

**Comment by egg82** [comment]
School took priority so it had to wait a bit, but yes there's plans to finish that to-do list.

**Comment by Titaniumtown** [comment]
@egg82 ok! Keep us posted :)

**Comment by mechoriet** [comment]
@egg82
maybe a not related question to this pr,
how much more compression/storage benefit will you get compared to extra processing power needed if any?
how would one generate a dict for zstd for minecraft? if there is a example for that, that your willing to share?
context:
looking into making a gamemode with lots of small worlds that could possibly benefit from this to lower storage and/or network traffic

thanks for the response in advance

**Comment by Proximyst** [comment]
You can generate the dictionary using the guide on another repository of his: https://github.com/egg82/CompressionTests

**Comment by egg82** [comment]
Closed in favor of #5029

**Pull request closed without merging**
