### PR TITLE
WIP Implement daemon mode to interop with paperd

### PR DESCRIPTION
**Pull request by DenWav**
This commit adds the necessary logic so Paper can communicate with [paperd](https://github.com/PaperMC/paperd).

[paperd's 1.0.0 release](https://github.com/PaperMC/paperd/tree/1.0.0) marks the first release and compatible version with this PR.

[Documentation on usage can be found here.](https://github.com/PaperMC/paperd/blob/master/usage.md)

[Documentation on the internals of the communication system can be found here.](https://github.com/PaperMC/paperd/blob/master/protocol.md)

---
### Build Changes

[This change also requires updates to `paperclip-maven-plugin` which were done here.](https://github.com/PaperMC/PaperclipMavenPlugin/commit/2c36e4b16c6ab074a103c4d708aaa15791ae1bb2)

[And the change to Paperclip to incorporate that Maven plugin update is here.](https://github.com/PaperMC/Paperclip/commit/707e3703cda460b069eaf04bd0294da7904890c2)

Both `paperclip-maven-plugin` and Paperclip itself were moved to the `io.papermc` package as well as a normal `SNAPSHOT` version bump.

---

### Necessary steps before merging:
 - [x] Implement a protocol versioning system
 - [x] Implement base command set
   - [x] Start
   - [x] Stop
   - [x] Restart
   - [x] Status
   - [x] Send Command
   - [x] Timings
   - [x] Console
 - [x] Command option features (PaperMC/paperd#1 & PaperMC/paperd#2)
 - [ ] Third party testing -- _in progress_

### CODE REVIEW

**Comment by DenWav** [comment]
It dawned on me just now that for safety reasons there should be versioning for the protocol, which will need a little bit more work, so this is WIP for now.

**Comment by DenWav** [comment]
This is now ready for review.

**Comment by MiniDigger** [comment]
applied these patches to my fork, I seem to have issues running under wsl in daemon mode (run works).
is there anything I can do to debug this? 
https://i.imgur.com/0YEefiE.png
https://i.imgur.com/6zTKgG6.png

**Comment by DenWav** [comment]
It's a Rust project, run the Rust debugger somehow on WSL I guess. I don't know :)

WSL is obviously not supported at all, but if you can find the issue and it's simple to apply then I would take a PR.

**Comment by MiniDigger** [comment]
Ok, spend some time on it today and after I fixed my patch (fail to apply a part...) it now works as expected....

**Comment by DenWav** [comment]
This change will need to be PRed into `master` intead of `ver/1.14`.

**Pull request closed without merging**
