### PR TITLE
Port Optimize-Hoppers.patch to 1.15

### PR DESCRIPTION
**Pull request by kickash32**
PR in progress

### CODE REVIEW

**Comment by kickash32** [comment]
https://drive.google.com/open?id=1W_OCzocemLv7h8RT37ObkrJwtFfc8vdZ
Download for paperclip. Will need to sufficiently test it to ensure the bugs are gone. Any volunteers would be appreciated.

**Comment by perseus5** [comment]
Added this patch into my current jar ~12ish hours ago, has worked wonders. TileEntityHopper would always show up in timings, but that's disappeared now. No issues so far, and I haven't heard any complaints (avg player count ~30), either.

**Comment by Huskehhh** [comment]
Can also vouch, have had great success with this!

**Comment by zachbr** [comment]
Thanks for testing everyone. We’re still looking for feedback on this. Especially looking out for behavioral bugs. 

So all you lurkers out there with hopper performance issues on 1.15, give this a try please. More feedback means a faster merge into master.

**Comment by Aurelien30000** [comment]
Tested during 2 days on my server, no issue, perfectly working ! Thanks :)

**Review by electronicboy — CHANGES_REQUESTED** [review]
.

**Comment by lukeeexd** [comment]
I'll try it out and report back

**Comment by ChanceSD** [comment]
I also didn't notice any issues so far, been using it for 2-3 days. Just not a big server, avg of like 5 players.

**Review by electronicboy — APPROVED** [review]

**Comment by HexedHero** [comment]
Seems good from my limited testing

**Review by zachbr — APPROVED** [review]

**Comment by electronicboy** [comment]
You able to rebase this?

**Comment by kickash32** [comment]
> You able to rebase this?

done

**Comment by Menzani** [comment]
Build #26 cannot be downloaded from [papermc.io](https://papermc.io/downloads).

Moreover, hoppers are broken when many are next to each other (for example after using /fill).
When some items are into one, they are processed faster than they should (for example, two items are moved each time).

**Comment by Menzani** [comment]
Build 26 cannot be downloaded from [papermc.io](https://papermc.io/downloads).

Moreover, hoppers are broken when many are next to each other (for example after using /fill).
When some items are into one, they are processed faster than they should (for example, two items are moved each time).

**Comment by kickash32** [comment]
The website sometimes runs into caching issues, try force refreshing the page and clearing cache.

Can we get some more information about the exact command you used? Was it a plugin command or Minecraft command, a picture of the configuration would help too.

**Comment by Menzani** [comment]
For the website, I tried disabling cache in Firefox and sometimes it works, sometimes it doesn't.

The bug can be reproduced easily by putting two hoppers one over the other, and putting a stack of items into the one to the top.

**Comment by Menzani** [comment]
For the website, I tried disabling cache in Firefox and sometimes it works, sometimes it doesn't.

The bug can be reproduced easily by putting two hoppers one over the other, and putting a stack of items into the first one.

**Comment by Menzani** [comment]
Did you manage to reproduce the bug?

**Pull request merged**
