### PR TITLE
Actually set the header for tablist

### PR DESCRIPTION
**Pull request by ghost**
I don't know why this had to be fixed, but there ya go

### CODE REVIEW

**Comment by chickeneer** [comment]
As indicated in Discord. This commit needs to change the following patch. Not create 
 a new patch.
https://github.com/PaperMC/Paper/blob/b62dfa0bf95ac27ba0fbb3fae18c064e4bb61d50/Spigot-Server-Patches/0050-Player-Tab-List-and-Title-APIs.patch

**Review by aikar — APPROVED** [review]

**Review by aikar — CHANGES_REQUESTED** [review]
As chicken said, please use git rebase -i upstream/master and move this patch to the target one and change action to fixup

**Comment by chickeneer** [comment]
If convenient. It would be nice to change the local variable `headerJson` in the footer section of the code to accurately reflect that is the footerJson. No change in behavior there though.

**Comment by ghost** [comment]
All better now

**Review by zachbr — APPROVED** [review]

**Comment by zachbr** [comment]
Thanks
Builds 367+

**Pull request merged**
