### PR TITLE
Add a toggle for the java 11 startup message

### PR DESCRIPTION
**Pull request by HexedHero**
Pointless warnings if the owner has already seen the message and knows about it

### CODE REVIEW

**Comment by JRoy** [comment]
no :)

**Comment by Machine-Maker** [comment]
You already can toggle it. Change to Java 11 and it goes away. go back to pre java 11 and its back. See? its already a toggle.

Any way to prevent the message from being seen probably shouldn't be considered. All it does is increase the chance someone will forget about it.

**Comment by DenWav** [comment]
This defeats the purpose of the message - which only prints once / startup anyways.

If people see a warning in their log and look up how to get rid of it and find a way to just get rid of the warning without actually addressing what the message is warning them about, that's not good. People _will_ simply enable that config option and people _will_ proceed to forget about it, or not understand the message and not look into it any further after that. This _is_ an issue that server owners need to address sooner rather than later so it doesn't sneak up on them. 

The fix is simple, just upgrade to Java 11. If there are issues, it's absolutely okay for you to not upgrade, you have several months for you to sort those issues out before we make the switch. A one time per startup warning message isn't _that_ annoying. Not upgrading just because it's annoying to do so and complaining about an annoying message because you refuse to upgrade is not a valid argument.

**Comment by DenWav** [comment]
Also if we were going to allow the message to be hidden - which we aren't - it would probably be via system property, not via config value.

**Pull request closed without merging**
