### PR TITLE
Change name and id to get from profile in AsyncPlayerPreLoginEvent

### PR DESCRIPTION
**Pull request by oxygencraft**
This patch changes the name and uuid getters to get from the player
profile because the event's name and uuid fields won't update. This
patch also removes the event's name and uuid fields.

This patch was made because when you set a new player profile, it does
not update the name and uuid in the event. This cause problems when the
event is passed to other listeners that use getName and getUniqueId
which will return the old name and uuid.

### CODE REVIEW

**Comment by electronicboy** [comment]
Should just read the name/UUID from the profile instead of tryna mangle that all together, imho

**Comment by aikar** [comment]
yeah that's what I was going to say. Can you merge it back into the original patch, then looks good to me.

**Comment by oxygencraft** [comment]
Which patch and how do I merge my patch into that patch?

**Comment by aikar** [comment]
PlayerProfile patch, but i can merge it for you. just held up atm finishing the light work.

can pull once I'm back in master.

but contributing.md details about how to rebase patches. 
that commit is "Ability to change PlayerProfile in AsyncPreLoginEvent"

**Comment by oxygencraft** [comment]
I have now merged the patch into the original patch.

**Pull request merged**
