### PR TITLE
Fix Anti-Xray

### PR DESCRIPTION
**Pull request by stonar96**
@Spottedleaf's branch was nuked, so I PR here. If you want I can also PR to @Spottedleaf. Or can you revert your Anti-Xray changes @Spottedleaf?

Note that these changes will probably also slightly improve the Anti-Xray performance.

### CODE REVIEW

**Comment by Spottedleaf** [comment]
Does this fix the issues with mode 2 where it would not properly recognize whether a block was exposed to air?

**Comment by stonar96** [comment]
Yes

**Comment by stonar96** [comment]
You almost did it right but it is necessary to first check if the current block to read or write is completely included in the current long. In pre 1.16 the logic was "reversed". There it was first read the rest of the current long and if it the index exceeds 63 prepare the next long.

That's also the reason why all the checks are `> 64` now and not `> 63` anymore, just in case you are wondering why.

**Comment by Spottedleaf** [comment]
can confirm this fixes

**Comment by aikar** [comment]
leaf has this merged in his pr for 1.16

**Pull request closed without merging**
