### PR TITLE
Don't print new chunk system prefix

### LINKED ISSUE #8391: Full qualifier output by the chunk system
### Expected behavior

The console output should look like that:

```
ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:05:00 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:05:00 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[12:05:00 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[12:05:00 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[12:05:00 INFO]: [ChunkHolderManager] Saved 529 chunks in world 'world_the_end' in 0s
[12:05:00 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:05:00 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Observed/Actual behavior

It currently looks like this:
```
ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:05:00 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:05:00 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[12:05:00 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Halted chunk system for world 'world_the_end'
[12:05:00 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[12:05:00 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Saved 529 chunks in world 'world_the_end' in 0s
[12:05:00 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:05:00 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Steps/models to reproduce

- Start/Stop the server
- Look inside the console

### Plugin and Datapack List

-/-

### Paper version

This server is running Paper version git-Paper-174 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 01a1387)
You are running the latest version
Previous version: git-Paper-"7978c8e" (MC: 1.19.2)

### Other

I think it is related to the chunk-commit (01a13871deefa50e186a10b63f71c5e0459e7d30) and already mentioned at https://github.com/PaperMC/Paper/pull/8177#issuecomment-1235121248

### PR DESCRIPTION
**Pull request by irochidesu**
Fixes https://github.com/PaperMC/Paper/issues/8391

This is my first pr and still unsure that make this patch sperately or merge into somewhere like 0016-Rewrite-chunk-system.patch

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by electronicboy** [comment]
Oh, wait, premature approval; That should be merged into the patch which generally adds those exclusions in the first place

**Comment by lynxplay** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0157-Improve-Log4J-Configuration-Plugin-Loggers.patch I'd presume

**Comment by irochidesu** [comment]
This should work I think

**Comment by lynxplay** [comment]
As pointed out by billy (thanks btw :heart:) this PR has the following effect when testing:

Old
```
[20:26:50 INFO]: Saving players
[20:26:51 INFO]: Saving worlds
[20:26:51 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:26:51 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[20:26:51 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Halted chunk system for world 'world'
[20:26:51 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Saving all chunkholders for world 'world'
[20:26:51 INFO]: [io.papermc.paper.chunk.system.scheduling.ChunkHolderManager] Saved 529 chunks in world 'world' in 0s
[20:26:51 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
```

New
```
[20:24:56 INFO]: Saving players
[20:24:56 INFO]: Saving worlds
[20:24:56 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:24:56 INFO]: Waiting 60s for chunk system to halt for world 'world'
[20:24:56 INFO]: Halted chunk system for world 'world'
[20:24:56 INFO]: Saving all chunkholders for world 'world'
[20:24:57 INFO]: Saved 529 chunks in world 'world' in 0s
[20:24:57 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
```

I am unsure if we want to completely remove the prefix here, as we are printing a lot of messages here which just starts to look very cluttered without some form of prefix.

**Comment by Lulu13022002** [comment]
Yea that's the purpose of this patch, i have some doubt if these messages shouldn't be printed only in debug (at least for the saving message).

**Comment by kennytv** [comment]
https://github.com/PaperMC/Paper/commit/f5fa69173cb59bf9fb4420163a25e305c7218b6b

**Pull request closed without merging**
