### PR TITLE
Items Merge Through Walls Fix (fixes #5204)

### LINKED ISSUE #5204: Items group through wall
### What behaviour is expected:
When a item is droped to the left of a wall of blocks and one to the right off the wall, both items should remain there.

### What behaviour is observed:
The items group together and both items end up on one side of the wall.

### Steps/models to reproduce:
Build a 1 wide wall of any block, drop an item on the left side of the wall, drop one on the right side.

### Plugin list:
Chunkmaster, SAML, VillagerOptimizer

### Paper version:
This server is running Paper version git-Paper-"088fa6f28" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
(I cloned the repo and built it from source)

### PR DESCRIPTION
**Pull request by GioSDA**
Fixed item entities merging through walls by raytracing between the two item entities and checking if there is a collision. As stated in the original issue, this should most likely be something behind a configuration option, however I'm not quite sure how to implement that.

### CODE REVIEW

**Review by MiniDigger — DISMISSED** [review]
for config option stuff, we a have a small example here: https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md#configuration-files

if you need more help, be sure to ask in discord.

other than that, I would add a "fix item merging through walls" comment to the // Paper start, so its easy to see what that code is supposed to do

**Comment by imDaniX** [comment]
Shouldn't it be true by default? As stated in https://github.com/PaperMC/Paper/issues/5204#issuecomment-786356993, it will definitely hit _some_ performance, and usually this check isn't needed.

**Comment by Trigary** [comment]
I agree with the previous comment and I would also rather suggest a name like "fix-items-merging-through-walls" to hint at what the vanilla default is.

**Comment by electronicboy** [comment]
defaulting on true to something which will be a performance hit for something most people likely don't really care about is honestly something I'm not fond of, I also honestly agree with the comments on the original issue, the better option here is really to not use a large merge radius, having a high merge radius and this check on to prevent merging through walls just seems like a 'not so smart' performance setup

**Comment by kashike** [comment]
Does this fix a vanilla bug? If so, please include the Mojira bug ID in the PR description and the patch description.

**Comment by PaulBGD** [comment]
Pulling #4958 and using `rayTraceDirect` would make this check significantly (3-4x) faster.

**Review by electronicboy — APPROVED** [review]
Approving, needs rebasing, left a comment on the linked PR as I feel that there is potentially some easy wins in general for performance with this type of stuff based on that comment

**Review by kennytv — APPROVED** [review]
Thank you!

**Pull request merged**
