### PR TITLE
Couple fixes/improvements to PlayerSetSpawnEvent

### PR DESCRIPTION
**Pull request by Machine-Maker**
Makes the setspawn command handle cancellation of the event.
Adds missing reasons for setting (clearing) spawn on player respawn if obstructed.
Adds missing plugin reason on api use.
Handles interaction result failure if event is cancelled for respawn anchors.

### CODE REVIEW

**Comment by Strahilchu** [comment]
This looks good honestly, currently my new joins are facing the wrong way although I've set spawn with every command possible facing the direction it still keeps facing new joins the wrong way but anyone doing /spawn is facing the correct way.

**Comment by jpenilla** [comment]
> This looks good honestly, currently my new joins are facing the wrong way although I've set spawn with every command possible facing the direction it still keeps facing new joins the wrong way but anyone doing /spawn is facing the correct way.

Are you having this issue in testing this PR, or in the latest Paper build?

**Comment by Strahilchu** [comment]
> > This looks good honestly, currently my new joins are facing the wrong way although I've set spawn with every command possible facing the direction it still keeps facing new joins the wrong way but anyone doing /spawn is facing the correct way.
> 
> Are you having this issue in testing this PR, or in the latest Paper build?

Latest paper build

**Comment by Machine-Maker** [comment]
> This looks good honestly, currently my new joins are facing the wrong way although I've set spawn with every command possible facing the direction it still keeps facing new joins the wrong way but anyone doing /spawn is facing the correct way.

I don't think this has anything to do with this PR. `/spawnpoint @s ~ ~ ~ -45` spawns myself at the correct (-45) angle. Same with `/setworldspawn ~ ~ ~ -45`

**Comment by Machine-Maker** [comment]
Rebased for 1.18

**Review by Owen1212055 — APPROVED** [review]
Tested, although the only thing is now /spawnpoint returns no feedback if it's canceled.. might it be nice to have a little error or something? I am not sure.

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
