### PR TITLE
Optimise processQueue

### PR DESCRIPTION
**Pull request by AlfieC**

### CODE REVIEW

**Comment by aikar** [comment]
Patch and commit needs a different name, to optimize Minecraft Network Queue

This is not the tick loop.

**Comment by aikar** [comment]
Oh sorry wrong queue, just name it "Optimize Process Queue"

**Comment by aikar** [comment]
@AlfieC we just need the commit and patch file renamed and we can merge it. I don't want to merge it in current state with the completely wrong commit name and if i fix it myself, github wont recognize it as merging your PR.

**Comment by AlfieC** [comment]
done

**Comment by Spottedleaf** [comment]
Patch number is behind by 3.

**Comment by aikar** [comment]
based on feedback with others, I don't think we need micro optimizations on this level unless it was extremely hot code and a known hotspot was because of this type of code.

changes like this add to the project maintenance. it's just not worth it for us.

**Pull request closed without merging**
