### PR TITLE
Add missing effects

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Fixes [SPIGOT-6249](https://hub.spigotmc.org/jira/browse/SPIGOT-6249)

### CODE REVIEW

**Comment by MiniDigger** [comment]
I actually planned upstreaming that (hence why I opened the issue upstream).
do you mind PRing that upstream? since its just bukkit is should be painless.

**Comment by MrIvanPlays** [comment]
guess ill sign the cla and attempt upstreaming...
if it works ill close this

EDIT: ok no im definitely not signing that shit... getting my phone number and address doxed... no thanks

**Comment by MiniDigger** [comment]
would you mind me taking this upstream? (keeping commit author and shit)

**Comment by Proximyst** [comment]
md_5 has previously stated he would not accept that. Ivan would need to give you the rights to the code.

**Comment by MrIvanPlays** [comment]
> would you mind me taking this upstream? (keeping commit author and shit)

no problem. it goes without asking 🤣

**Comment by MiniDigger** [comment]
what so I can't commit under ivans name cause clearly MIT isn't permissive enough?

**Comment by MrIvanPlays** [comment]
@MiniDigger whats the progress on porting this to spigot? 
if there's none you can always merge this :)

**Comment by MiniDigger** [comment]
md told me to not submit that contribution 🤷

**Comment by MrIvanPlays** [comment]
then just merge that

**Comment by MiniDigger** [comment]
thanks!

**Pull request merged**
