### PR TITLE
Catch async usage of playsound

### PR DESCRIPTION
**Pull request by Owen1212055**
This causes the world random to scream due to multi-thread acces

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Do we also need catchers for the adventure sound methods? Should be added to the adventure patch if so.

**Review by Machine-Maker — APPROVED** [review]
Looks good. This was expanded to catch any use of World#playSound off the main thread as none of the 3 methods are thread-safe. It does more specific checks for Server#playSound methods as there are some cases where the use is thread-safe.

**Review by kennytv — APPROVED** [review]

**Comment by Machine-Maker** [comment]
> .playSound is just sending a packet

Very much not true on World and Server. On `Player`, playSound is as simple as sending a packet. But not on those other types. They either iterate over a thread-unsafe list of players in a world or use the vanilla packet broadcasting system based on location which contains thread-unsafe logic. 

The "world random" aspect is just one part of this. If a sound isn't provided a seed, a seed must be generated from the world's random instance which is a thread-unsafe instance.

As to your second post, I'm not sure what you are "wat"ing? THat diff is just changing some hunk line numbers and index hashes.

**Comment by Machine-Maker** [comment]
> It appears the line
lighning.isSilent = isSilent
was removed, I could be mistaken though.

That's correct. That line was removed. But not as a part of this PR. That is just part of an existing patch that removes that line.
image
These 3 spots are the lines in that patch that changed as a result of this PR.

**Pull request merged**
