### PR TITLE
Log IOException in plugin update

### LINKED ISSUE #7958: Papers plugin updater should log an exception if IO operations fail
### Is your feature request related to a problem?

As of right now, the plugin update logic uses a rather questionable spigot-made method to copy the updated plugin jar into the plugin folder: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/util/FileUtil.java#22

As a side effect of this, IOExceptions that occure while copying the updated plugin jar into the plugin folder are quietly ignored.
This makes error tracing a lot harder than it has to be.

While paper uses its own refined plugin update logic, introduced in #7687, this issue persists on paper.
### Describe the solution you'd like.

There is not much need for the `FileUtil#copy` method, when [Files.copy](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/nio/file/Files.html#copy(java.nio.file.Path,java.nio.file.Path,java.nio.file.CopyOption...)) exists. The method throws an IOException, so the update logic should to catch said exception and properly log it to the console, allowing administrators to identify the error.

A server shutdown is not required, a single plugin failing should generally not fail the server.

### Describe alternatives you've considered.

None, this is a rather straight forward feature request.

### Other

_No response_

### PR DESCRIPTION
**Pull request by Doc94**
Yeah im a stalking... this handle to fix #7958 

This PR change the Bukkit util for copy things to the native java things and add a LOG when a issue is found, this not change the current behaviour where if the copy fails pass to another file.

Not sure if this is better o can be better add the log in the Bukkit util...

### CODE REVIEW

**Review by jpenilla — DISMISSED** [review]
Use proper logging templates and pass the exception instead of string concatenation. ie `LOGGER.info("Hello {}, an {} happened!", username, "exception", ex);`

**Comment by Doc94** [comment]
> Use proper logging templates and pass the exception instead of string concatenation. ie `LOGGER.info("Hello {}, an {} happened!", username, "exception", ex);`

i based in another patchs and the whole file where this is the logger used, in the code i see like 3 types of logger.
- Bukkit.getLogger
- org.apache.logging.log4j.LogManager.getLogger()
- logger in plugin manager class used in another methods to show error in update plugin
image

What logger need to use?

**Comment by kennytv** [comment]
The Bukkit logger is a dumb logger and doesnt support replacement parameters nicely, and since all the other usages in that class are the same, should be fine, meh

**Comment by Doc94** [comment]
Rebased.

**Review by kennytv — APPROVED** [review]

**Pull request merged**
