### PR TITLE
Add company details for MIT license list.

### PR DESCRIPTION
**Pull request by DevonThome**

### CODE REVIEW

**Review by aikar — CHANGES_REQUESTED** [review]
I would rather keep it to a list of individuals.

By writing a company name, it essentially says 'anyone who is a part of my company'. But that is vague on who is part of your company and when.

Please change this to your name instead

**Comment by DevonThome** [comment]
Hey @aikar There are multiple team members who are working on this fork. Would you like the name of the individual (myself) who owns the company or the one who does the most with it?

**Comment by MiniDigger** [comment]
add the names of the ppl who plan on contributing to upstream

**Comment by DevonThome** [comment]
Will do

**Comment by aikar** [comment]
Each person should submit their own PR.

**Pull request closed without merging**
