### PR TITLE
Fix hopper optimized bug

### PR DESCRIPTION
**Pull request by lg-Cat73**
64 items 5 seconds to transfer.  ↓

### CODE REVIEW

**Comment by Postremus** [comment]
What exactly is the bug in the current implementation? How does it behave now?

**Comment by lg-Cat73** [comment]
@Postremus 64 items 5 seconds to transfer.

**Comment by lg-Cat73** [comment]
Sorry English is not my native language, this is Google Translate

**Comment by lg-Cat73** [comment]
Please set hopper.push-based to true
And then follow the picture to test

**Comment by lg-Cat73** [comment]
Please do not merge, this does not solve the problem

**Pull request closed without merging**
