### PR TITLE
Fix idle usage

### PR DESCRIPTION
**Pull request by Spottedleaf**
Vanilla's sleep behaviour was to use LockSupport#parkNanos, however
they never backed off and entered a full park, so the scheduler
could potentially keep the server thread running when we really
did not want that.

We also introduce a method to wait for a completable future, which
is common when waiting for sync loads to complete.

This is specifically aiming to resolve https://github.com/PaperMC/Paper/issues/2336 and https://bugs.mojang.com/browse/MC-149018.

### CODE REVIEW

**Comment by HexedHero** [comment]
Thank you Leaf <3

**Comment by Spottedleaf** [comment]
I have not been able to produce this issue locally so you should test and report back results once this gets pulled

**Comment by Wqrld** [comment]
If you can build a paperclip jar with this i'm willing to test it.

**Comment by Spottedleaf** [comment]
Based off build 147/148
https://cdn.discordapp.com/attachments/602031644919988236/604724570649264135/paperclip.jar
SHA1: a9c97c35c59813a019787083f1bd1eb484bd8117

**Comment by Spottedleaf** [comment]
I've updated the jar to be based off build 147/148

**Comment by RikoDEV** [comment]
Great fix <3

**Comment by Wqrld** [comment]
The paper jar of the discordapp.com seems to be broken, I am getting sub .5% cpu but the server also just hangs after `>.... [09:42:49 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms` it hangs at 362/1024MB of ram, the cpu overhead is probably from the docker container that it runs in

**Comment by Spottedleaf** [comment]
please provide a jstack of the process after a minute of it hanging

**Comment by Wqrld** [comment]
it hung on nerfing mob spawners now:
jstack: https://paste.imluc.ga/apemefukur.cs

**Comment by Spottedleaf** [comment]
can confirm deadlocking

**Comment by Spottedleaf** [comment]
I've updated the jar to include a fix

**Comment by HexedHero** [comment]
Normal Paper:
http://cdn.hexedhero.com/u/7WlQxEwNsv.jpg

Leaf's Idle CPU Fix:
http://cdn.hexedhero.com/u/L7ahpCobYv.jpg

**Comment by sirlinium** [comment]
hello,
just tried, same, doesnt fix anything =/

**Comment by sirlinium** [comment]
Hi,

Just tried, works very well !
My server went from approx 56%charge to 22% while idling

**Comment by Spottedleaf** [comment]
Other testing elsewhere shows this patch is a cause for chunks not loading.

I suspect it has to do with something along the lines that https://github.com/PaperMC/Paper/pull/2342/commits/6f21bed4c0a9219a1e4264c001fd253b908d8804 addressed.

There's a rabbit hole to go down and that will likely have more changes than just an idle fix.

**Comment by LoneDev6** [comment]
Will this ever be implemented in PaperSpigot? :D

**Comment by HexedHero** [comment]
"PaperSpigot"
It was discontinued due to bugs

**Comment by LoneDev6** [comment]
What do you mean with 
> "PaperSpigot"

Yes I know it was discontinued due to bugs, I wanted to know if they'll try to implement it in the future or if it's something impossible.

**Comment by HexedHero** [comment]
PaperSpigot isn't a thing anymore, we are just Paper

**Comment by LoneDev6** [comment]
Okay, so 
> It was discontinued due to bugs

=  Paperspigot is discontinued due to bugs, or the feature to limit idle usage is discontinued due to bugs?
Thanks what I can't understand.

**Comment by HexedHero** [comment]
This PR is discontinued, for now, whether it'll come back in the future is unknown and Paper = PaperSpigot, we rebranded.

**Comment by Spottedleaf** [comment]
`There's a rabbit hole to go down and that will likely have more changes than just an idle fix.`

**Comment by LoneDev6** [comment]
Okay thanks!

**Comment by 0-x-2-2** [comment]
> Will this ever be implemented in PaperSpigot? :D

This was fixed in 1.14.4. https://minecraft.gamepedia.com/Java_Edition_1.14.4_Pre-Release_6

**Comment by Spottedleaf** [comment]
no it was not fixed

**Comment by 0-x-2-2** [comment]
Lmao.

**Comment by ramirilyasov999** [comment]
how to downoload it...

**Comment by ramirilyasov999** [comment]
i have this error https://pastebin.com/MWKwUVQR
when i try to use this link Based off build 147/148
https://cdn.discordapp.com/attachments/602031644919988236/604724570649264135/paperclip.jar
SHA1: a9c97c35c59813a019787083f1bd1eb484bd8117

**Comment by electronicboy** [comment]
The build is no longer available, and this PR was closed due to known issues.

**Pull request closed without merging**
