### PR TITLE
Add PlayerItemCooldownEvent

### LINKED ISSUE #2504: Option to remove enderpearl item cooldown
**Is your feature request related to a problem? Please describe.**
Currently there is no simple way of setting/preventing item cooldowns (e.g. enderpearl and shield usage), as all applicable events for that specific case (like interact, projectilelaunch) happen before the cooldown is set.

**Describe the solution you'd like**
One of two possibilities:
- have a config option to not start a cooldown on the enderpearl throw
- have an PlayerItemCooldownEvent you can customize/cancel yourself

The first would be to just have the boolean check in `ItemEnderpearl` right before the `entityhuman.getCooldownTracker().setCooldown(this, 20);`,
the latter would (probably) be done by calling a cancellable event (with another setter to set the time) either in `ItemCooldown`, or just `ItemCooldownPlayer` to actually have the entityplayer object, in the `setCooldown` method

The second one would also open it up for a little more customization, but I'm fine with either one 🤷‍♀️

### PR DESCRIPTION
**Pull request by kennytv**
Two times' the charm.
Closes #2504

### CODE REVIEW

**Comment by kennytv** [comment]
Rebased 😎

**Review by Proximyst — DISMISSED** [review]

**Review by electronicboy — DISMISSED** [review]

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Comment by MiniDigger** [comment]
thanks!

**Pull request merged**
