### PR TITLE
 Improve per player mob spawning 

### PR DESCRIPTION
**Pull request by Spottedleaf**

### CODE REVIEW

**Comment by bespeland** [comment]
seems to fix the problem in #3963

**Comment by imperium13** [comment]
seems to fix the problems in #3963
(apologies for double comment. used wrong account)

**Comment by WonderDave** [comment]
Since this was merged (build 111), my mob spawns are much lower than my config values.  In bukkit.yml, under spawn-limits, I have monsters set to 36, and in paper.yml I have per-player-mob-spawns set to 'true'.  Up through build 110, at my End farm, I would always get almost exactly 36 endermen spawning.  But with build 111, I'm getting only around 10 to 12.  This is on my test server with no other players.  I tried increasing the monsters value to 108, expecting maybe three times as many mobs, but then I got only 30 endermen.

Am I doing something wrong?

**Comment by Spottedleaf** [comment]
provide full spigot/bukkit/paper config

**Comment by WonderDave** [comment]
bukkit.yml:  https://pastebin.com/23Jxrn5T
spigot.yml:  https://pastebin.com/QQFVyP7g
paper.yml:  https://pastebin.com/7540gxV7

**Comment by Spottedleaf** [comment]
it looks like I mixed up 1.12 spawning mechanics and 1.14+ spawning mechanics; spawn range is only relevant for counts in 1.12 but shouldn't be for 1.14+
this patch made per player correctly account for spawn range, but as I said above it shouldn't
so that aspect of the patch should be reverted

**Pull request merged**
