### PR TITLE
Add option to disable fast regeneration

### PR DESCRIPTION
**Pull request by kamcio96**

### CODE REVIEW

**Comment by Techcable** [comment]
Can't this be done with a gamerule? It looks like it can.

**Comment by zachbr** [comment]
At present there is no way to tell whether regeneration is "normal" or a result of "fast regen" via the API (that I'm aware of). Instead of a configuration option, we should probably be adding something to the existing health regen events to cover this case.

**Comment by kamcio96** [comment]
@Techcable all options can be done with gamerule, but config is more safe, you cannot change ingame it.

@Zbob750 I don't have idea how do it with event

**Comment by Techcable** [comment]
@kamcio96 Only ops can change gamerules.........

**Comment by zachbr** [comment]
The ugliest API draft in history
https://gist.github.com/Zbob750/8e3584b962b743976bdc291c2cf228c8

[12:43:24] < Z750 > this just feels dirty
[12:45:50] < DemonWav > jesus
[12:45:55] < DemonWav > Z750 what are you doing
[12:46:22] < Z750 > terrible things
[12:46:24] < DemonWav > that seems wrong. why is fast regen not a reason?
[12:46:35] < Z750 > because they didnt make one
[12:46:43] < DemonWav > omg
[12:46:51] < Z750 > and if I add it, I have to change the API implementation
[12:47:04] < DemonWav > fine, stick with the ugly
[12:47:09] < Z750 > and then some plugins checking for the old reason wont get it anymore

**Comment by kamcio96** [comment]
Hmm, api looks good. Both solutions are good.

Config option should be avalible for servers owner. Not everyone knows how to write/edit plugins.

**Comment by zachbr** [comment]
The whole point of the API was to avoid the config option. They aren't both going to be added.

It's a stupid tiny plugin, if need be I'll write the thing shortly after if needed.

**Comment by zachbr** [comment]
Added an API to do this in a6536804fdc9aca4b82aec4d1574c934ae8a0e3a

And here is a plugin, with source code, to stop this behavior. https://github.com/Zbob750/StopFastRegen/releases/tag/1.0.0

EDIT: err you'll need to update and use build 693 or higher for it to actually work though :p

**Pull request closed without merging**
