### PR TITLE
Readd 0414 use distance map to optimise entity tracker

### LINKED ISSUE #9794: CraftPlayer#canSee() causing extreme MSPT increases / TPS drops
### Timings or Profile link

https://spark.lucko.me/IIftkvHeLc

### Description of issue

The new Entity visibility API is causing significant performance issues since my server's upgrade from 1.19.2 to 1.20.2. We were previously able to handle around 50 online around 20tps most of the time.

Since updating to 1.20.2, we've been unable to achieve this same level of performance or anywhere close. CraftPlayer#canSee() is adding an extreme amount of tick time to the server with our entity and player count that makes the server essentially freeze with 100 players online, running poorly with 50. We haven't touched our plugins outside of updating for compatibility, so there haven't been any major changes in that regard.

### Plugin and Datapack List

```
[15:47:57 INFO]: Server Plugins (56):
[15:47:57 INFO]: Bukkit Plugins:
[15:47:57 INFO]:  - *Analyse, AreaShop, ChangeSlots, ChatItem, Chunky, ChunkyBorder, ClearLag, CMCEvents, CMCLinkManager, CoreProtect
[15:47:57 INFO]:  CrashClaim, CrashPayment, CreativeManager, DecentHolograms, dynmap, DynmapWaystones, Essentials, EssentialsSpawn, FancyWaystones, FastAsyncWorldEdit
[15:47:57 INFO]:  GSit, HatCosmetics, HeadDatabase, HeadHunter, helper, helper-sql, HubParkour, HuskyPatch, HuskyScreen, *HuskyTest
[15:47:57 INFO]:  ImageMaps, InventoryRollbackPlus, InvSeePlusPlus, LiteBans, LitebansAntiMuteBypass, LPC, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI
[15:47:57 INFO]:  PlasmoVoice, PlugManX, ProtocolLib, pv-addon-lavaplayer-lib, QSFindItemAddOn, QuickShop, ServerSigns, spark, SubserverTools, TAB
[15:47:57 INFO]:  UltimateAutoRestart, Vault, ViaVersion, VillagerTradeLimiter, WitherSound, WorldGuard

```

### Server config files

Configs are included in the spark profile - here's a DL to a zip with ours.
[cfg.zip](https://drive.google.com/file/d/18UiimwYTjOcUjzk3MF_wkngMqtXZ3jri/view?usp=sharing)

### Paper version

```
> ver
[15:50:56 INFO]: Checking version, please wait...
[15:50:57 INFO]: This server is running Paper version git-Paper-214 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 02cfaa8)
You are running the latest version
Previous version: git-Paper-212 (MC: 1.20.2)

```

### Other

Additional profile: https://spark.lucko.me/JnmFU5zTpF
Already reached out in #paper-help about this and it seemed best to report this here.
Worth note that simply asking everyone in the server to "stop moving" brought the TPS from 7 to 15.

### PR DESCRIPTION
**Pull request by AverageGithub**
Resolves: #9794 

I'm not sure what to do about the patch number, don't know if it's fine as-is, or if it should be changed, so I just left it and let rebuildPatches handle it.

Tested it, and it seems to be working just fine!

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Brokkonaut** [comment]
We are using this patch on our servers for a few days now and I could not find any issues. And the performance is much better.

**Comment by electronicboy** [comment]
I'm currently dead, but, if this can be rebased I'll slap the button

**Comment by AverageGithub** [comment]
Should be rebased (first time doing a rebase, so let's hope it worked)

**Comment by electronicboy** [comment]
and slapped

**Pull request merged**
