### PR TITLE
Fix double lock in ServerConnection

### PR DESCRIPTION
**Pull request by AlfieC**
Miniscule fix but it adds up

### CODE REVIEW

**Comment by Techcable** [comment]
How do we know this is safe?

**Comment by AlfieC** [comment]
This method is called once - in a method that already synchronises around `this.h`.

**EDIT:** By double lock, I don't mean lock-inside-lock as to imply that two locks on different objects are bad - but in this instance one of the enclosing methods already locks properly.

**Comment by Techcable** [comment]
It's still a relatively unsafe oprimization, since ensure this method remains safe.
I'd expect the JVM to inline a method this small anyways, and optimize away the synchronization overhead.
Before continuing, can you please give us an [assembly dump]() of the callingn method to show that both:
1. This method is _not_ being inlined, preventing the JVM from eliminating the unessicary locking.
  - A method this small should meet the inlining threshold even in the baseline compiler, unless something unexpected is happening.
  - If it is being inlined, the JIT should easilyeliminate the redundant lock.
2. Even if the method isn't being inlined, can you show that biased locking isn't being triggered?
  - A biased lock should be extremely cheap, negating most of the overhead of the locks.

If neither of these optimjzations are being triggered, you can show this is a major performance hotspot, then I'd support this patch if the maintaoners agree to accepting rhe maitenece burden.

**Comment by AlfieC** [comment]
The JVM does not "inline away" synchronisation. That is not inlining. Eliminating locking is NOT inlining.

We can ensure the method remains safe as it's a non-default method that aikar added - not stock NMS code. It's called once per tick, inside a block of code that ALREADY HAS `this.h` synchronized. The inline threshold is pretty high anyway - expecting JIT to do all work for you isn't a good habit. 

No matter how cheap a lock is, as Aikar likes to say, "it adds up".

**Comment by Techcable** [comment]
> The JVM does not "inline away" synchronisation.  That is not inlining. Eliminating locking is NOT inlining.

Let me clarify, the JVM will eliminate any unnecessary and duplicate locking within a method.
For example, if I do
````java
synchronized (this) {
    synchronized (this) {
        this.a += 15;
    }
}
````
The C2 compiler will determine that the second lock is unnecessary, and automatically eliminate it.
However, this optimization can't be performed across method boundaries, as the JIT doesn't know whether or not the caller actually performed the redundant lock, and has to be safe.
For example, let's say I call `put()` on a synchronized map, while inside a synchronized block.
````java
synchronized (this.synchronizedMap) {
    this.synchronizedMap.put("taco", null);
    this.synchronizedMap.forEach((key, value) -> {
        // I am doing very important things here
    });
}
````
Although the synchronization in 'SynchronizedMap.put' and 'SynchronizedMap.forEach', the JVM can't eliminate it, since although it's redundant here, it's not necessarily redundant in all the other places `SynchronizedMap` is called.

However, when it's inlined, the JVM copies the contents of the method to the caller, making the code look like this:
````java
synchronized (this.synchronizedMap) {
    synchronized (this.synchronizedMap) {
        this.synchronizedMap.backingMap.put("taco", null);
    }
    synchronized (this.synchronizedMap) {
        this.synchronizedMap.backingMap.forEach((key, value) -> {
            // I am doing very important things here
        });
    }
}
````
Now the JVM can safely optimize away the duplicate synchronization in the inlined copy, without affecting the original code.
This is the fundamental reason why inlining is so important, as it allows the JIT's optimization to 'see' across method boundaries and perform optimizations like this one.
This is also the reason why lambdas are still significantly slower than a hand-rolled loop, as the JVM doesn't like to inline them, and so they can't get the critical optimizations that traditional loops enjoy.

**EDIT:** Turns out this method is only used by paper code, and so there's no reason not to pull this. I'm still leaving this comment here because it's a good explanation of the importance of inlining and the JVM's synchronization optimization.

**Comment by zachbr** [comment]
The idea is sound, but it will not be pulled as is.

We do not add new patch files to make changes to things introduced in older patch files. We fix the old patch files themselves.

I can do that easily and amend you as the author, just letting you know. By all means though good change. :+1:

**Comment by Spottedleaf** [comment]
While the JIT will eliminate unnecessary synchronization, it's still unnecessary. Why there is unnecessary synchronization written into the code is beyond me.


This method is private - there is no need for it to be safe. We know where it will be invoked.

**Comment by zachbr** [comment]
Added via ed90e5b3a6c1c90e202afebbc9429578b09dd3c3
Thanks

**Pull request closed without merging**
