### PR TITLE
Updated Upstream (Bukkit/CraftBukkit)

### PR DESCRIPTION
**Pull request by electronicboy**
Upstream has released updates that appear to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
31514774 SPIGOT-6949: Configuration sections that are nested within Maps or Lists are not properly serialized.
1bebebfb SPIGOT-6992: Add LimitedLife/LifeTicks/Bound APIs to Vex

CraftBukkit Changes:
9cc7d766d SPIGOT-7010: Changing dropper item results in using dispensing behaviour
e87f2e3ed SPIGOT-6992: Add LimitedLife/LifeTicks/Bound APIs to Vex
cf391b51c Pass in SpawnReason rather than boolean
098aecb04 SPIGOT-7001: Fix entity already exists in CraftWorld#spawnFallingBlock
911bde181 SPIGOT-6972: Root command nodes can leak to client

### CODE REVIEW

**Comment by electronicboy** [comment]
I brained out just as I pushed this more or less (gh cli thing is nice, btw)

1) vex now has dupe methods, prefer spigots or ours? ours have been there for a year and line up with vanilla naming more so are more preferable vs breaking stuff here
2) Two fixes for the same issue in CommandDispatcher, not sure what's preferable here

**Comment by Owen1212055** [comment]
The methods that spigot added to vexes are recent, being added in this PR:  https://github.com/PaperMC/Paper/pull/7592

it seems spigot didn’t add a setter for if has unlimited lifetime or not, only a getter.

**Comment by Doc94** [comment]
> The methods that spigot added to vexes are recent, being added in this PR: #7592
> 
> it seems spigot didn’t add a setter for if has unlimited lifetime or not, only a getter.

yeah the set was maked but using negative ticks in the set ticks... based in comments for the PR maked for the JIRA issue (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/738/overview?commentId=9123)

i think its better keep the paper methods (?

**Review by kennytv — APPROVED** [review]

**Comment by electronicboy** [comment]
Deprecated spigots methods given that the ones in paper expose a bit more stuff and use names which line up better within the internals

Also, accepted our fix for the command stuff given that it, given that it's been there for longer and seems to potentially cover something upstream doesn't

**Pull request merged**
