### PR TITLE
fix enderman universal anger

### LINKED ISSUE #5155: Endermen lose retaliation AI when attacked with specific gamerules set
### What behaviour is expected:
Enderman retaliates when being attacked with specific gamerules set.

### What behaviour is observed:
Endermen does not retaliate when being attacked with specific gamerules set.

### Steps/models to reproduce:
Set `forgiveDeadPlayers` to false, set `universalAnger` to true, punch enderman in the legs.

### Plugin list:
none

### Paper version:
This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
This was reported by a user in Discord that refused to make a ticket here, I tested it and it appears to cause this issue. It seems to work differently in Vanilla (endermen retaliates there).

### PR DESCRIPTION
**Pull request by Trigary**
Other entities that had a `PathfinderGoalUniversalAngerReset` also had a `PathfinderGoalNearestAttackableTarget`, so I added it. I did a lot of testing, it seems to work. It's definitely better than not being attacked at all, hopefully it doesn't break something else.

I changed the priority on the selectors. That's all I changed about them. The extra diff is a shame, let me know if there's a better way. :/

Fixes #5155. Oh GitHub, why isn't it enough if I have it in the title?

### CODE REVIEW

**Comment by Trigary** [comment]
"rebased" and retested

**Review by Machine-Maker — CHANGES_REQUESTED** [review]
Needs to be rebased for 1.17.1

**Comment by Trigary** [comment]
"rebased" and retested

**Review by Machine-Maker — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]
Tested and works, but appears to be alittle "delayed". As in, the enderman still takes a little bit before it actually starts to attack you.

Probably fine tho? Better than not attacking them at all.

I would add https://bugs.mojang.com/browse/MC-195278 to the patch as well, useful for tracking.

**Pull request closed without merging**
