### PR TITLE
Check 'bukkit.broadcast.user' permission for Server#broadcast overload without permission argument

### PR DESCRIPTION
**Pull request by jpenilla**

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by BillyGalbreath** [comment]
#5477  covers this already

**Comment by electronicboy** [comment]
Billy you're drunk

**Comment by BillyGalbreath** [comment]
> Billy you're drunk

sorry, linked to wrong PR :P

**Comment by jpenilla** [comment]
Closed in favor of #5477

**Pull request closed without merging**
