### PR TITLE
Add doors to material tags

### PR DESCRIPTION
**Pull request by Malfrador**
Doors were missing from MaterialTags. This PR adds them.

Its my first Paper-PR, so I hope I got the patches right. Its a bit confusing

### CODE REVIEW

**Review by Proximyst — DISMISSED** [review]

**Review by HexedHero — COMMENTED** [review]
I think it'll be best to follow what was already done with Trapdoors.

Make a "WOODEN_DOORS" that have the 8 wooden doors then add a "DOORS" tag that includes the iron door, this will follow how the trap doors are tagged.

See: https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0153-Add-Material-Tags.patch#L555
and https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0153-Add-Material-Tags.patch#L540

Other than this suggested change, well done on your first PR! :D

**Review by zachbr — DISMISSED** [review]
May as well add wooden doors as well I suppose. We can do that on merge if you're uncomfortable with the patch editing workflow. Everything one step at a time.

Thanks

**Comment by Malfrador** [comment]
Added the extra tag for WOODEN_DOORS. I hope I did it correctly, thanks to MiniDigger for the explanation ^^

**Review by Proximyst — APPROVED** [review]

**Comment by Proximyst** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Pull request merged**
