### PR TITLE
Improve behavior of filter-nbt-data-from-spawn-eggs-and-related config

### PR DESCRIPTION
**Pull request by Owen1212055**
This patch seemed to no longer work exactly anymore, as at least the behavior of filtering is no longer in this patch.

This readds it, and also instead of completely making blocks like command blocks turn to stone instead just wipe all tile entity data (opinion wanted on this).

Other nbt tags to remove can be suggested!

### CODE REVIEW

**Comment by Machine-Maker** [comment]
This kinda sorta duplicates an already existing PR https://github.com/PaperMC/Paper/pull/6613

**Comment by Owen1212055** [comment]
> This kinda sorta duplicates an already existing PR #6613

I mean this is just adding onto something that already exists and wasn’t updated. The original patch would also remove tags, but it got removed sometime. Does it hurt to have both? I don’t know, because this is just supposed to remove tags that we consider “dangerous”. You can have the decision here however, tbh.

**Comment by Machine-Maker** [comment]
I this the configurability of #6613 is better, leaves it open to server owners with sane defaults.

However I do think it's better to wipe tile entity data instead of setting to stone which is the other thing your PR does.

**Comment by Owen1212055** [comment]
> I this the configurability of #6613 is better, leaves it open to server owners with sane defaults.
> 
> 
> 
> However I do think it's better to wipe tile entity data instead of setting to stone which is the other thing your PR does.

What do I do with the patch then? This adds a config option that only half works, and only prevents special falling sand blocks. Should I just rename it?

**Comment by Owen1212055** [comment]
@Machine-Maker Do you have any update on how you want this handled? This PR is a bit different, and tbh, this option seems a bit pointless to me anyways with ur PR.

But it leaves the question if we were to go with ur PR instead should the config option just be removed then?

**Comment by Machine-Maker** [comment]
Handled in https://github.com/PaperMC/Paper/pull/6613 (Owen said to)

**Pull request closed without merging**
