### PR TITLE
Fix occasional light gen issues for neighbor blocks

### PR DESCRIPTION
**Pull request by MiniDigger**
thanks @Spottedleaf

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Qveshn** [comment]
This issue also occures in latest paper versions:
paper-1.15.2-391
paper-1.16.1-138
paper-1.16.2-189
paper-1.16.3-253
paper-1.16.4-416
Could you apply this fix to them as well?

PS. You can use  `SectionPosition.e(j1)` directly instead `SectionPosition.blockToSection(j1)` to get around unnecessary nested function call (as in the original code).

**Comment by emielderckx** [comment]
No only the latest Minecraft version is supported

**Comment by Qveshn** [comment]
It's a shame! 😟
We'll have to take note that the final version 1.15.2 (https://papermc.io/api/v1/paper/1.15.2/latest) contains a bug and will never be fixed.

**Comment by aurorasmiles** [comment]
grafik

**Pull request merged**
