### PR TITLE
Changed curl to wget

### PR DESCRIPTION
**Pull request by vik1395**
I thought it would be simpler to just use wget instead of curl. Saves the need to install curl for some folks out there.

### CODE REVIEW

**Comment by Ichbinjoe** [comment]
In all honesty these are functionally equivalent, and unless I am mistaken, most systems have both wget and curl installed on them. Is there anyone out there who this actually effects?

**Comment by willies952002** [comment]
Not all operating systems come w/ wget by default whereas most, if not all, have cURL.
**_-cough- WINDOWS -cough-_**

Edit: I have been informed it's the other way around. Seems that every windows install I've ever had was bugged (didn't have wget) :/

**Comment by vik1395** [comment]
Well this is a bash script, and to have it work on windows, you're gonna have to install either one of them along with something like cygwin.

I also have had issues with curl when automating the building process. But wget seems to work fine

**Comment by zachbr** [comment]
iirc the choice of curl specifically was purely for compat, as every POSIX machine typically has both, or easy access to both, but Windows users that use Git Bash to run these will only have curl. Unless that's changed since we released these.

**Comment by zachbr** [comment]
Git Bash on Windows comes only with curl. On the majority of POSIX systems, and the few without curl by default, installing curl is a simple matter, much simpler than doing so on Windows. So we must cater  to the lowest common denominator and decline this PR.

**Pull request closed without merging**
