### PR TITLE
Deprecate TargetBlock/EntityInfo and assocated methods

### LINKED ISSUE #7340: Missing documentation of enum TargetBlockInfo.FluidMode
### Is your feature request related to a problem?

There is no documentation about the enum `com.destroystokyo.paper.block.TargetBlockInfo.FluidMode`, especially the meaning of its values when using them as parameter of `LivingEntity.getTargetBlock(int, FluidMode)`.

Doc : https://papermc.io/javadocs/paper/1.18/com/destroystokyo/paper/block/TargetBlockInfo.FluidMode.html

### Describe the solution you'd like.

Document that enum to make its usage clearer

### Describe alternatives you've considered.

Dig into the implementation of `LivingEntity.getTargetBlock(int, FluidMode)` to see how the FluidMode enum is used.

### Other

_No response_

### PR DESCRIPTION
**Pull request by Machine-Maker**
Closes https://github.com/PaperMC/Paper/issues/7340

### CODE REVIEW

**Comment by jpenilla** [comment]
Should maybe deprecate that enum, I would guess it was added before `org.bukkit.FluidCollisionMode` existed.

**Comment by skellatore2** [comment]
Is this possibly why a player in survival dies when using a tnt player cannon? 
—Player on a smp that runs on paper version 126

**Comment by electronicboy** [comment]
this is API, not internal code stuff, so, probably 1000% unrelated to what you're talking about

**Review by electronicboy — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Rebased for 1.19

**Review by Owen1212055 — APPROVED** [review]

**Pull request merged**
