### PR TITLE
[CI-SKIP] Fix Contributing TOC links

### PR DESCRIPTION
**Pull request by Janmm14**

### CODE REVIEW

**Comment by Proximyst** [comment]
This breaks them.

**Comment by Janmm14** [comment]
~~I checked with two different browsers (Firefox & Chromium) and for me this fixes it.~~

Seems like its not working only in firefox for me like its now. I guess thats more of a github problem than a problem of the md file then I guess.

**Comment by Proximyst** [comment]
It's not fixing anything; it works fine as-is in stable Firefox v89.0.

**Comment by electronicboy** [comment]
works with and without these here 🤷

**Pull request closed without merging**
