### PR TITLE
Entity#fromMobSpawner

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Comment by kashike** [comment]
What's wrong with the `fromMobSpawner` field on `net.minecraft.server.Entity`?

**Comment by BillyGalbreath** [comment]
It is labeled wrong. It is only set to true if a mob is from a mob spawner AND is nerfed from spigot.yml settings.

I even have an open ticket to MD about his naming choice there, but it's going ignored same as countless times I've mentioned it to him on IRC. https://hub.spigotmc.org/jira/browse/SPIGOT-3344

**Comment by zachbr** [comment]
Would rather investigate altering the implementation of that nerf and always setting the original field, rather than adding another one.

**Comment by zachbr** [comment]
Hmm, I did as I suggested and made the nerf use the original field but the resulting diff is larger. May be best not to do that, will have to think more on it.

**Comment by zachbr** [comment]
Added w/ minor change to make it persistent across server restarts (and I changed the field name)

Thanks

**Pull request closed without merging**
