### PR TITLE
Add exploded block state to BlockExplodeEvent

### PR DESCRIPTION
**Pull request by Machine-Maker**
Ability to differentiate between explosions caused by beds and respawn anchors, or other explosions that just take place at a location where a non-air block is present.

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Rebased for 1.18.1

**Comment by Machine-Maker** [comment]
Rebased for 1.18.2

**Comment by Machine-Maker** [comment]
Rebased & updated

**Comment by Machine-Maker** [comment]
Rebased for 1.19.3

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
