### PR TITLE
 Port mid tick and chunkmap changes from tuinity 

### PR DESCRIPTION
**Pull request by Spottedleaf**
Replaces old logic (tuinity's was first and should have been ported)

Old mid tick is inferior because it refuses to run mid tick logic if we're over 50ms for current tick

Old chunk map was incorrect as it failed to properly handle the chunk map downsizing

### CODE REVIEW

**Comment by aikar** [comment]
I would rather us stick with the current implementations.
I apologize for not putting full details on why in the initial reply.

Downsizing thing was 100% intentional and desired. The reason for this is to avoid memory allocations, as we have seen numerous issues with Humongous Allocations due to this. 

Downsizing and then re-upsizing will continuously trigger these allocations.

My solution also avoids all main-thread full copies, keeping those allocations at bay. Only off thread accesses from plugins touching NMS would invoke the copy.

This greatly stabilized large allocations. We will only get them now as the map size scales up each time.

For Mid Tick, we want to give all worlds a chance, not just the currently ticking world, otherwise you still have other worlds deprived of the benefit while larger worlds are being ticked.

Additionally, if the server is falling behind, we don't want to continue to put pressure on the current tick by continuously executing more tasks. 

By doing it this way, we then can let it fall back to the Oversleep System to finish processing the rest of the Tasks. If the server is super behind, then we simply wont process more at all to allow it to catch up.

This is closer to how vanilla treats it, processing these tasks in sleep and oversleep.

We are simply giving it a speed push by processing some of them mid tick, but our goal is to try to not over burden the server with additional tick cost.

With the proposed version, even capping to a % of the tick can still put us over if the ticks are already running +20ms over every few ticks.

**Comment by Spottedleaf** [comment]
I'm not porting further patches until these are in

**Comment by DenWav** [comment]
This really comes down to a difference in opinion regarding what sacrifices to vanilla behavior vs potential performance gain etc we're willing to make.

I've been outside this debate from the beginning and still am, and I see merits on both impls, and the arguments for and against both seem valid to me.

Difference of opinion in open source is totally okay and fine, and that's why I encourage you to work on your fork with your impl, that's totally cool. We don't need to try and strong-arm each other into taking only a single way.

If merging this is an absolute requirement for you to continue contributing then well, thats a bummer. We appreciate your contributions but if this patch is that important to you then so be it. I see no reason why we can't run different impls of this patch in Paper vs Tuinity, but they are your patches and your PRs, so it's up to you.

Stirring up drama over a couple patches of impl seems a little silly to me, and that's by no means just from you, Spotted. The Paper team has definitely contributed to that drama as well. I'm going to continue to stay out of it, this isn't really my wheelhouse, but I just wanted to share my perspective on this whole situation.

**Comment by Spottedleaf** [comment]
It looks like it's also time for me to explain why I'm going to die on the hill of these two patches.

> Downsizing thing was 100% intentional and desired. The reason for this is to avoid memory allocations, as we have seen numerous issues with Humongous Allocations due to this.
> 
> Downsizing and then re-upsizing will continuously trigger these allocations.

Sorry. It looks like I made an error in analyisng the logic you had. It looks fine.
But it doesn't eliminate the downsize/upsize allocation. It's just moved to one patch.

My patch sets the initial capacity to 8192 - fastutil will only downsize if the current size after remove is less than 1/4th of the maximum capacity (which is determined via loadFactor) and the current capacity is greater-than the initial capacity. I don't think it's an actual risk to consider, and certainly nothing to rewrite a patch over. 

> My solution also avoids all main-thread full copies, keeping those allocations at bay. Only off thread accesses from plugins touching NMS would invoke the copy.

My patch has main thread copies for full save. Let's be real - the issue with full save is saving thousands of chunks. The saves alone creates a lot of garbage - far more than the copy op. Again, nothing to rewrite a patch over - editing? sure. rewriting? no.

I also appreciate the credit you gave me in the patch, you totally had a valid reason to rewrite the patch. I suspect you did it for the patch author given the total non-issues you have laid out here (and the fact you claimed that you solved issues in discord, I had to correct you on that), but I can't be sure.

But I can say I'm not going to put up with you rewriting my patches for fun as a point of principle. Not only is it annoying to lose the invested time, but how many times did I need to tell you your implementation was broken before you actually fixed it, and how many times did you think you fixed it but didn't? It's just bullshit I don't want to put up with. Use what works. Make an edit if you want - the original wasn't perfect. 
There's nothing wrong with writing "Co-Authored by" in the patch.

> For Mid Tick, we want to give all worlds a chance, not just the currently ticking world, otherwise you still have other worlds deprived of the benefit while larger worlds are being ticked.

The patch in this PR actually addresses this. Read the patch next time.

> Additionally, if the server is falling behind, we don't want to continue to put pressure on the current tick by continuously executing more tasks.

The reason I want to put pressure on the current tick is because without that pressure chunks simply do not load. My current impl limits to 4%. I'm sure server owners will gladly trade off 4% of tick just to have chunks load. People don't want a low tps because it ruins user experience. And guess what really ruins user experience? Chunks not loading. So the tradeoff is worth it.

> By doing it this way, we then can let it fall back to the Oversleep System to finish processing the rest of the Tasks. If the server is super behind, then we simply wont process more at all to allow it to catch up.

This is where bothering to listen to me would be useful. The oversleep system is incapable of loading chunks at any reasonable pace. I'm going to repeat, __again__(yes, I told you this before), why.

Oversleep behaves as follows:
At the start of a tick it is given 50ms of time to execute tasks from the queue. If there are no remaining tasks, oversleep period ends. The fact it ends right after there are no tasks left to execute is critical to understanding what I'm about to explain.

Chunk loads need the main thread to process __each__ chunk status - and there are 11 chunk statuses. So what happens when the server takes a long time to tick? The chunk loads simply stall - as observed. When oversleep comes by, it executes tasks to start them again. However, if you had listened to me you would have heard this before, those resumed chunk tasks don't immediately complete. So then oversleep period ends - as there are no tasks left to execute. Effectively, oversleep only executes a small number of tasks - not anywhere enough to keep chunks loading at a non-miserable rate. Why do you think chunk loads are slow at high tick times if oversleep has 50ms?

This is why I'm pissed off - the patch I wrote is __designed__ to fight this: Hit the queue as many times as possible during tick. This is why the backoff of the queue is 25us and the max execution time is 1us - Time spent on the queue isn't important. How often we hit is far more important - we _need_ to hit it as often as possible.

However due to implementation detail of the entity map / tile entity list / and so on it's hard to load/unload chunks during the most expensive parts of tick - but your patch doesn't fix it, and I'm working on a fix for that.

But instead of listening to me you decided to rewrite the patch. Your patch is blatantly arrogant of the facts of the chunk system I just laid out - it's not executed in areas of tick where stuff is commonly looped on, and it backs off after every chunk task execution (for up to 100us). And this would not have happened if you bothered to listen to me or port my patch.

And I'm not going to want to PR patches if you just take the idea and just totally ignore everything I say about it as if I have no idea what I'm doing and then proceed to screw up the implementation. Whether you like it or not, I wrote the mid tick patch to be complex because it had to be. Because the fundamental underlying system is complex to deal with, it's not simple.


And this is why I don't want to continue PRing. I don't want to put up with any of this, and the fact you doubled down on your logic tells me you will. And I want nothing to do with it.

**Comment by Spottedleaf** [comment]
Hey @aikar I'd like to apologise for my post on this pr.
I shouldn't have let my anger get the best of me. I don't think it was right for me to accuse you of stealing, especially when you've been very supportive of my prs.

I'm going to continue work on my own fork, I don't think it's right to ask people to review my changes if this is how I treat them.

**Comment by aikar** [comment]
Thank you for the apology. I assure you there was no malicious intent, just differences of opinions. 

I respect your desire to keep some things in your preferred way, that's why we have open source. 
I hope we can continue to work together on the changes we do agree on though (which will usually be most).

**Pull request closed without merging**
