### PR TITLE
Resolve Plugin Dependency Issues, Improve PluginLoading Compat, Small Loading Issues (part 2)

### LINKED ISSUE #8971: Paper fails to load plugins with dependencies through API
### Expected behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) the plugin's dependencies should be checked against the plugins that are currently loaded on the server, and be permitted to enable if present.

### Observed/Actual behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) paper says the dependencies of the plugin being loaded are missing (even if they are not) and fails to enable the plugin. 

### Steps/models to reproduce

1. Create a plugin that can load another plugin from an addons folder
2. Create another plugin that depends on the first plugin
3. Place the second plugin in the first plugins addon folder
4. Load the second plugin from the addons folder (through a command or something) using Bukkit.getPluginManager().loadPlugin(file)
5. You will receive an error like this https://pastebin.com/DLYc6Q6n

### Plugin and Datapack List

- MBedwars (Our plugin)
- ExtraSpectialItems (The plugin being loaded from an addons folder of MBedwars)
- PlaceholderAPI

### Paper version

[23:40:59 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36) You are running the latest version
Previous version: git-Paper-399 (MC: 1.19.3)

### Other

We have been using this API for close to a year now, and was working great until a fairly recent Paper update. I believe the API was broken in Paper's move to their own plugin system, as it works fine on the latest spigot version. Let me know if you would like me to test anything, or need more detailed info. Thanks everyone!

### LINKED ISSUE #9114: Plugin dependencies of paper plugins fail to load as of build 503
### Expected behavior

The changes introduced in https://github.com/PaperMC/Paper/pull/9068 break the loading of plugin dependencies for paper plugins.

I have a [plugin](https://modrinth.com/plugin/huskhomes/version/4.1.1) that defines a paper-plugin.yml file which contains several dependencies.

<details>
<summary>paper-plugin.yml snippet</summary>

```yaml
dependencies:
  - name: Vault
    required: false
  - name: RedisEconomy
    required: false
  - name: PlaceholderAPI
    required: false
  - name: dynmap
    required: false
  - name: BlueMap
    required: false
  - name: Plan
    required: false
  - name: Pl3xMap
    required: false
load-before:
  - name: Essentials
load-after:
  - name: Vault
  - name: RedisEconomy
  - name: PlaceholderAPI
  - name: dynmap
  - name: BlueMap
  - name: Plan
  - name: Pl3xMap
```
</details>

On builds 502 and below, on servers with (for example) Dynmap installed alongside my plugin, the hook I wrote for Dynmap loads fine.

### Observed/Actual behavior

On builds 503 and up, Dynmap's API is not added to the classpath of my plugin and throws a ClassNotFound exception when trying to load

<details>
<summary>stack trace provided by an end user</summary>

image
</details>

The same is true with other plugin API hooks written for my plugin. Note that I wrote a custom loader for my plugin that loads some libraries; this is unrelated and these libraries load fine, but for reference [here's the class](https://github.com/WiIIiam278/HuskHomes2/blob/master/paper/src/main/java/net/william278/huskhomes/PaperHuskHomesLoader.java).

### Steps/models to reproduce

Download HuskHomes v4.1.1 https://modrinth.com/plugin/huskhomes/version/4.1.1
Download Dynmap
Install HuskHomes on your Paper (build 503+) server
Ensure HuskHomes' dynmap hook is turned ON in its config
Observe as it throws the exception

### Plugin and Datapack List

HuskHomes
Dynmap

### Paper version

build 506-8be7a60

### Other

_No response_

### PR DESCRIPTION
**Pull request by Owen1212055**
Redo of #9068

Fixes: https://github.com/PaperMC/Paper/issues/8971, https://github.com/PaperMC/Paper/issues/9057

Pass dependency tree when loading, this allows us to correctly resolve dependencies when loading while plugins already in the plugin manager.

Closes: https://github.com/PaperMC/Paper/issues/9114

---
Download the paperclip jar for this pull request: [paper-9129.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/660377927.zip)

### CODE REVIEW

**Comment by Owen1212055** [comment]
The issue should have been fixed. I will be adding some more tests, but if servers could test this build that would be great.

**Comment by CloudeLecaw** [comment]
i can confirm that this testbuild inside paper-9129.zip works fine for loading, unloading and reloading if the plugin has a dependency

image

**Comment by TheFruxz** [comment]
I think, this may be related to this one:

Since today, I get the following error during the loading of my paper plugin:

```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.github.TheFruxz:Ascend:pom:2023.2-RC from/to jitpack (https://jitpack.io/): Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver.register(MavenLibraryResolver.java:122) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.loader.PaperClasspathBuilder.buildClassLoader(PaperClasspathBuilder.java:44) ~[paper-1.19.4.jar:?]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:44) ~[paper-1.19.4.jar:git-Paper-511]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:23) ~[paper-1.19.4.jar:git-Paper-511]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:67) ~[paper-1.19.4.jar:git-Paper-511]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.19.4.jar:git-Paper-511]
	... 20 more
Caused by: org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
```

As you can see, only the first char of the checksum is different. I don't fully know how these work, but this small difference is kind of weird.

**Comment by CloudeLecaw** [comment]
> I think, this may be related to this one:
> 
> Since today, I get the following error during the loading of my paper plugin:
> 
> ```
> Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.github.TheFruxz:Ascend:pom:2023.2-RC from/to jitpack (https://jitpack.io/): Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
> 	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
> 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> 	at io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver.register(MavenLibraryResolver.java:122) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.loader.PaperClasspathBuilder.buildClassLoader(PaperClasspathBuilder.java:44) ~[paper-1.19.4.jar:?]
> 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:44) ~[paper-1.19.4.jar:git-Paper-511]
> 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:23) ~[paper-1.19.4.jar:git-Paper-511]
> 	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:67) ~[paper-1.19.4.jar:git-Paper-511]
> 	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.19.4.jar:git-Paper-511]
> 	... 20 more
> Caused by: org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
> ```
> 
> As you can see, only the first char of the checksum is different. I don't fully know how these work, but this small difference is kind of weird.
> 
> Edit: I switched from the PreRelease to a commit build of the dependencies, this resolved the issue. But due to the fact, that this problem did not occur in the Gradle projects but here, this may still be relevant.

and you got this error with the Test version from the zip file?
It only would maybe related if this happens with the version from the zip file in this thread.

**Comment by TheFruxz** [comment]
> > I think, this may be related to this one:
> > Since today, I get the following error during the loading of my paper plugin:
> > ```
> > Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.github.TheFruxz:Ascend:pom:2023.2-RC from/to jitpack (https://jitpack.io/): Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
> > 	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> > 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> > 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
> > 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> > 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
> > 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
> > 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
> > 	at io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver.register(MavenLibraryResolver.java:122) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> > 	at io.papermc.paper.plugin.loader.PaperClasspathBuilder.buildClassLoader(PaperClasspathBuilder.java:44) ~[paper-1.19.4.jar:?]
> > 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:44) ~[paper-1.19.4.jar:git-Paper-511]
> > 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:23) ~[paper-1.19.4.jar:git-Paper-511]
> > 	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:67) ~[paper-1.19.4.jar:git-Paper-511]
> > 	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.19.4.jar:git-Paper-511]
> > 	... 20 more
> > Caused by: org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, expected 56b2045d6d7330b432300e09fe8145d0870b66c but is 056b2045d6d7330b432300e09fe8145d0870b66c
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As you can see, only the first char of the checksum is different. I don't fully know how these work, but this small difference is kind of weird.
> > Edit: I switched from the PreRelease to a commit build of the dependencies, this resolved the issue. But due to the fact, that this problem did not occur in the Gradle projects but here, this may still be relevant.
> 
> and you got this error with the Test version from the zip file too? It only would maybe related if this happens with the version from the zip file in this thread!
> 
> your error shows Build 511. so create a new thread for your issue you run into with the the build 511 and not report error here. The error is not realted here because here we only test a testbuild that has code in it to test the loading unloading and reloading behave of plugins to see if this may fixed the issue we currently got with it.
> 
> Only report it if also apears in the Testbuild paper-paperclip-1.19.4-R0.1-SNAPSHOT-reobf
> 
> Snag_bd953

The error also appears in the [paper-9129.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/644633022.zip) build. Because this PR also aims to address Loading Issues and my paper plugin won't load, I thought, this PR might be related to that problem.

**Comment by bergerkiller** [comment]
Just passing by to say I had no (more) issues loading up plugins with the **paper-9129.zip** as linked.

**Comment by Owen1212055** [comment]
Tested with some internal tests as well. This generally seems to be ready, unless anyone seems to encounter any other issues.

**Review by kennytv — APPROVED** [review]

**Pull request merged**
