### PR TITLE
Use Redis as world backend

### PR DESCRIPTION
**Pull request by ronnyjauch**
With this patch applied, you get options to save and load your worlds to and from redis instead of filesystem.

### CODE REVIEW

**Comment by kashike** [comment]
I am sorry, but this is not something we will be accepting.

**Comment by Spottedleaf** [comment]
in the future you should discuss with us prior to making the changes to avoid a situation where you spend quite a bit of effort making the patch but the idea gets shut down immediately

**Comment by ronnyjauch** [comment]
I did this in the past and experienced it as a useful feature, it was not a lot of affort to make this work, so no problem there. 

But can you explain, why this it isnt useful for the community?

**Comment by electronicboy** [comment]
Principally, Redis is not designed for data storage

but, more importantly:
You *cannot* relocate netty

there are questions over the maintainability of such a patch,if we were to ever go down such a route, it would need to be implemented in a much cleaner manner so that this could be expanded.

**Comment by egg82** [comment]
Correction, Redis is designed as a network cache- ie. Temporary data storage that can easily be replaced (because it can also be erased easily, by Redis itself and/or the OS)

**Comment by ronnyjauch** [comment]
Im not going to discuss what redis is or what redis not is, you should look that up on your own.

But Im right there with you in terms of maintainability, its possible to do it way more cleaner.

**Comment by egg82** [comment]
Using the right tools for the job is important. Redis is a tool designed for caching data across a network. Storing data for world files for a server does not fit. It's like using a screwdriver to hammer in a nail.

**Comment by HexedHero** [comment]
> Using the right tools for the job is important. Redis is a tool designed for caching data across a network. Storing data for world files for a server does not fit. It's like using a screwdriver to hammer in a nail.

Not related at all but I've done that irl

**Pull request closed without merging**
