### PR TITLE
Add FurnaceBurnEvent.setBurnTime(short burnTime)

### LINKED ISSUE #8178: Values above SHORT.MAX_VALUE for org.bukkit.event.inventory.FurnaceBurnEvent#setBurnTime do not play burning animations inside the furnace UI for players
### Expected behavior

The furnace should play a burning animation for the furnace inside the furnace UI window

### Observed/Actual behavior

No furnace burning animation is played to show that the furnace is fueled, however the furnace continues to operate

### Steps/models to reproduce

Use org.bukkit.event.inventory.FurnaceBurnEvent#setBurnTime and set it to a value substantially higher than Short.MAX_VALUE, observe that the furnace no longer plays an animation inside the UI window

### Plugin and Datapack List

This was tested by modifying mcMMO source code, but the bug is inside Bukkit, the burnTime of a furnace should be a short (as that is how it is saved in NBT) yet instead allows an integer

### Paper version

This server is running Paper version git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)
You are running the latest version

### Other

A simple fix without breaking the API would be to apply Math.min(Short.MAX_VALUE, burnTime) in the implementation of setBurnTime

### PR DESCRIPTION
**Pull request by nossr50**
This also deprecates setBurnTime(int burnTime) and fixes its implementation as well
Fixes #8178

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Is there a better way? There's no way to write short literals in java right? So you'd now have to do 
```java
furnace.setBurnTime((short) 40);
```
just to avoid it using the deprecated integer method.
maybe just throw exception if its too big to be converted to a short?

**Comment by emilyy-dev** [comment]
Even if the int variant wasn't there you need to either cast to a short or put the number into a short variable to use the method (more specifically, narrowing conversions are not allowed in a method invocation context, and int literals are, well, `int` literals).
Maybe put a `@Range` annotation on the int parameter? I think clamping the value is a reasonable approach, exceptions are nasty

**Comment by Machine-Maker** [comment]
> Even if the int variant wasn't there you need to either cast to a short or put the number into a short variable to use the method

Oh I figured in the absence of another method that took an int, it'd accept a regular int in a short parameter.

**Comment by nossr50** [comment]
I don't see the issue with having to cast to short since it's new API and not a change of an existing signature.

**Comment by emilyy-dev** [comment]
Casting is actively annoying and, when you have a method that does not require casting, it's very easy to miss and forget.
Others might think differently but those are my two cents.

**Comment by lynxplay** [comment]
I'd also be in favour of just limiting the setBurnTime(int)  method to Short.MAX_VALUE like done right now for backwards compat.
The getter is returning an integer. As pointed out by emily, the @Range annotation could be added to actively inform developers about the constraint on the values even without reading through javadocs.

A new method that requires developers to add rather ugly casts for little to no benefit seems overkill for a problem this small.

**Review by Owen1212055 — CHANGES_REQUESTED** [review]
Many of NMS' values are represented by integers by the API. Instead, just Math.min (or clamp it to the min/max short) on the provided integer. This would help avoid creating a new method like this.

**Pull request closed without merging**
