### PR TITLE
Fix hex colours not being allowed in MOTD

### LINKED ISSUE #3754: MOTD hex colors aren't working with Paper but are with Spigot/Craftbukkit.
### What behavior is expected:
To be able to use hex colors in MOTD by doing https://ibb.co/GM9PFyJ

### What behavior is observed:
Hex colors are changed to legacy colors.

### Paper build number:
git-Paper-34 (MC: 1.16.1)

### Anything else:
This was fixed In Craftbukkit  [7560f5f5a69](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7560f5f5a69fc5fa17ec0c33eaba8abe026a53ef) but it seems like when it got merged to Paper it broke.

### PR DESCRIPTION
**Pull request by calumari**
Fixes #3754

### CODE REVIEW

**Comment by aikar** [comment]
good catch

**Comment by andrew121410** [comment]
Forgot but don't forget about [008f039f373](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/008f039f373d8313553a94188ecec36b3d927e9d)

**Comment by andrew121410** [comment]
^^^ That fixes (MOTD no longer supports new line character)

**Comment by calumari** [comment]
Oops 😅

**Pull request merged**
