### PR TITLE
Fixes #1415 - Llama setCarryingChest() don't refresh to other players

### LINKED ISSUE #1415: Llama setCarryingChest() don't refresh to other players
### What behaviour is expected:
Hi! i'm writing a piece of code trying to make shift right-click llama with chest, drops the chest and inventory contents and works fine for me, no errors in console. But for other players close to me, they still see llama with chest texture and if they ride it, can see llama inventory slots, but if they reconnect to the server they see it without, it's like if needs some kind of refresh to other players, i don't know... this is my code:

https://pastebin.com/FYepcKvC

### What behaviour is observed:
If my code is correct, i think if it works fine for me then should work fine for anybody.

### Steps/models to reproduce:
Try this code, tame llama, put chest, Shift right-click with empty hand, the chest (and llama's inventory drops). Try it with another person around.

### Plugin list:
None.

### Paper build number:
Paperclip-221

### Anything else:
I also tried to cast Llama using ChestedHorse, but same issue. If my code is wrong, sorry for the inconvenience of this opened issue.

### PR DESCRIPTION
**Pull request by caojohnny**
Fixes #1415.

~~Cancelling the interaction event causes a metadata packet to be sent to the player that performs the interaction, which in turn causes the "dirty" flag for the `DataWatcher` to be reset to `false`.

I noticed that `DataWatcher#e()` clears the "dirty" flag. I concluded that the intent for the `flag` variable in the constructor must probably have been something to do with whether or not the dirty flag is cleared, where `true` means that it should not be cleared, and `false` meaning that it should be cleared. 

By commenting out the call to `DataWatcher#e()`, the contents of the `DataWatcher` should be encoded without undirtying. When the player is sent `PacketPlayOutEntityMetadata` after the event is cancelled, the `DataWatcher` remains dirty and the metadata of the entity will then be broadcasted the next time the entity tracker runs.

I'm still not exactly sure why the flag is undirtyed in the first place here, I can only assume it must be a mistake. At worst, I'd think that the entity would simply just keep being updated for the players tracking it, but otherwise I don't see any negative impacts coming from this change.~~

**Demo**
https://streamable.com/r2zsq

### CODE REVIEW

**Review by aikar — CHANGES_REQUESTED** [review]
I don't think this is the right fix. 
the correct fix is to make Playerconnection send packet to do the following instead:

```java
// Refresh the current entity metadata
//this.sendPacket(new PacketPlayOutEntityMetadata(entity.getId(), entity.datawatcher, true));
entity.tracker.track(worldserver.players); // Paper
```
So that a single packet state is captured and sent to all players tracking this entity.

**Comment by caojohnny** [comment]
While I agree that your solution seems to be a better fit to rectify the issue, my question still remains as to the purpose of the `flag` parameter in `PacketPlayOutEntityMetadata`. Is this simply just an artifact from decompilation? Or is there some other explanation that I seem to be missing?

**Comment by electronicboy** [comment]
The flag is used to determine if we're sending all or just dirty data

**Comment by caojohnny** [comment]
Should be fixed by now. Force pushes are due to me running into a bunch of noob problems, don't mind me lol.

**Comment by aikar** [comment]
@AgentTroll you did check that my proposed solution does actually still solve the problem right lol. Incase I missed something else being needed.

**Comment by caojohnny** [comment]
@aikar Of course, checked the code path and uploaded a new streamable link when I pushed :)

**Review by aikar — APPROVED** [review]

**Pull request merged**
