### PR TITLE
Fix NPE for AIR in meta operations in ItemStack

### PR DESCRIPTION
**Pull request by TheMolkaPL**
They will throw `NullPointerException` when the type of `ItemStack` is `Material.AIR`.

### CODE REVIEW

**Comment by JRoy** [comment]
imo `getItemMeta()` should be checked by the plugin. A plugin shouldn't be blindly changing an item's meta in the first place.

**Comment by Owen1212055** [comment]
Yea uh, hasItemMeta() exists.

**Comment by TheMolkaPL** [comment]
> imo getItemMeta() should be checked by the plugin. 

It's not stated in the documentation to do so. Even if it was there should be a better exception message that certain materials can't have `ItemMeta` than a generic `NullPointerException` with no message at all.

> Yea uh, hasItemMeta() exists.

`hasItemMeta()` checks if the `ItemStack` has an item meta, not if the `ItemFactory` can actually create one for this material. This is only useful in read operations where you don't use `ItemFactory`.

**Review by Proximyst — APPROVED** [review]

**Comment by Proximyst** [comment]
Thanks for your contribution! :)

**Pull request merged**
