### PR TITLE
1.8.8 port of the "Introduce a setting to handle offline proxies" patch

### PR DESCRIPTION
**Pull request by sgdc3**
Servers behind a bungeecord proxy in offline mode
will now properly pull offline mode UUIDs and data
when this setting is set to false. Default is unchanged.
Ported from Paper 1.10.2

### CODE REVIEW

**Comment by zachbr** [comment]
We do not support or maintain the 1.8.8 branch or any other branch for an old version.
It only exists in case we want to backport a security fix.

**Comment by sgdc3** [comment]
This patch doesn't require testing, it's just an HUGE fix for any offline mode server.

**Comment by zachbr** [comment]
Great, it wasn't rejected because it wasn't tested.
It was rejected because we do not support 1.8.8. People can apply it to their own forks and branches, we will not.

**Comment by sgdc3** [comment]
Define "support"

**Comment by sgdc3** [comment]
support is related to issues reported by users, this is just an addition.

**Comment by zachbr** [comment]
We. Do. Not. Want. This. Patch. Or. Any. Patch. For. Any. Unsupported. Version.
The only time we may take one is if it is a critical security fix, and those will be handled case-by-case.

This is not one of those.

**Pull request closed without merging**
