### PR TITLE
Updated Upstream (Bukkit/CraftBukkit/Spigot)

### PR DESCRIPTION
**Pull request by Machine-Maker**
Upstream has released updates that appear to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
97445251 Update ASM
8301151f Add dimension setting getters to World

CraftBukkit Changes:
61e4ca7b Update ASM and add support for Java 17
c30e8f8d PR-913: Handle campfire damage with EntityDamageByBlockEvent
6cfc062a Add dimension setting getters to World
97a4f34a SPIGOT-2222, SPIGOT-6687: Pre-set keepLevel and only use it

Spigot Changes:
ff89b973 Add log-named-deaths option

### CODE REVIEW

**Review by MiniDigger — APPROVED** [review]
stupid method names aside (seriously spigot, isBedWorks and isRespawnAnchorWorks?!) lgtm

**Comment by Doc94** [comment]
> stupid method names aside (seriously spigot, isBedWorks and isRespawnAnchorWorks?!) lgtm

Sorry (? (i make the PR for this) i based in the NMS name (in craftbukkit nms is called isBedWorks then they tell me use the same names)

**Review by electronicboy — APPROVED** [review]

**Comment by Machine-Maker** [comment]
> Sorry (? (i make the PR for this) i based in the NMS name (in craftbukkit nms is called isBedWorks then they tell me use the same names)

Yeah, that's spigot's stupid mappings. The actual mojmapped names make much more sense. Generally regardless of what the server code says, method names make somewhat actual sense to say out loud. `isBedWorks` sounds absurd. There is 0 reason why they have to have the exact same name.

**Comment by Machine-Maker** [comment]
Added upstream ASM updates

**Comment by MiniDigger** [comment]
> Sorry (? (i make the PR for this) i based in the NMS name (in craftbukkit nms is called isBedWorks then they tell me use the same names)

yeah, didn't mean that on an attack on you, spigot named the nms method dum in the first place, and reusing those names in the api doesn't make them better. but oh well, maybe in the next decade spigot will use mojang mappings like the rest of the community

**Pull request merged**
