### PR TITLE
Add Anti-Xray bypass permission

### LINKED ISSUE #4233: Permission for bypassing Anti-Xray (Can be given to staff on the server) Feature Request
**Is your feature request related to a problem? Please describe.**
With Paper's anti-xray it's kinda frustrating that when you (op) go into gmsp and try looking at players to make sure they aren't xraying/hacking it kinda get's in the way and if you are looking for a xrayer then you can't really tell either as for you it looks the same as the xrayer does instead of you being able to see the ores.

**Describe the solution you'd like**
It would be cool if ops bypassed it, or there could be a perm added which you could give staff so you could bypass the anti-xray.

**Describe alternatives you've considered**
To ignore it and live with it.

**Additional context**
None

### PR DESCRIPTION
**Pull request by stonar96**
This is a frequently requested feature. <strike>In rare cases two chunk packets
must be created.</strike> The permission is 'paper.antixray.bypass'. <strike>I have added
all the required OBFHELPERs to 0004-MC-Utils.patch.</strike>

### CODE REVIEW

**Comment by JRoy** [comment]
Pretty sure there was a reason this wasn't added due to permission checks becoming a very expensive bottleneck with some (if not all) permissions plugins. 

I'm fairly certain this will increase TPS, I could be wrong tho so I'd wait for other people to chime in before either discarding or rethinking how this is implemented.

**Comment by Proximyst** [comment]
Modern plugins like LuckPerms should be fine as they should maintain a cache. If this isn't expected, we *could* move to check perm *once* and store the result on the player.

**Comment by stonar96** [comment]
@JRoy yeah I also had this thought and I wanted to see what other people think. An alternative way is to check if the player is an operator. However, permissions are much more flexible.

**Comment by BillyGalbreath** [comment]
> I have added all the required OBFHELPERs to 0004-MC-Utils.patch

OBFHELPERs should be in the first patch that uses them. This prevents scenarios where patches can get removed over time and the OBFHELPERs end up remaining for no reason

**Comment by JRoy** [comment]
I would say the best option would be a list of users in the paper config itself would be best. That way we don't have to deal with permissions at all because not everyone uses modern permissions plugins sadly.

**Comment by stonar96** [comment]
> OBFHELPERs should be in the first patch that uses them. This prevents scenarios where patches can get removed over time and the OBFHELPERs end up remaining for no reason

I have tried to keep the Anti-Xray patch clean regarding OBFHELPERs (also in the past). Currently all the OBFHELPERs of Anti-Xray are in 0004-MC-Utils.patch. If it's really a problem I can change this ofc. But what's so bad about remaining OBFHELPERs?

**Comment by electronicboy** [comment]
> But what's so bad about remaining OBFHELPERs?

We have to maintain them;
The major "against" of anti-xray having an override perm was trying to get the info in the correct context without having to blow much more in terms of resources or complexity

**Comment by stonar96** [comment]
Thanks for the numerous feedback. Of course I can change these things. But for now I'll wait for final decisions about all the mentioned things before I change anything. If I should definitely change something specific, please review the PR and request changes.

**Comment by A248** [comment]
What you might be able to do is cache whether the user has the permission when they switch worlds.

**Comment by stonar96** [comment]
- Changed the base branch from master to progress/1.16.2
- Rebased
- Mojang made changes in 1.16.2, there are no cases where two chunk packets must be created anymore
- Therefore less OBFHELPERS are required than before and complexity was drastically reduced
- Moved OBFHELPERS from 0004-MC-Utils.patch to 0368-Anti-Xray.patch
- Added config option `use-permission: false` to enable this feature and a warning if enabled (as discussed on Discord)

**Comment by SoulxluoS** [comment]
Hi, this is a very important feature.
Optimization and convenience for honest players.
Why is it frozen?

**Comment by TheoRetisch1** [comment]
I would love to see this feature :)

**Review by Floffah — DISMISSED** [review]

**Comment by molor** [comment]
When this will be merged?

**Comment by Proximyst** [comment]
When we get around to it.

**Review by Proximyst — DISMISSED** [review]

**Comment by stonar96** [comment]
Rebased due to conflicts. Tested.

**Review by zachbr — DISMISSED** [review]
Your continued work on the anti-xray patch is appreciated

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Comment by MiniDigger** [comment]
thanks!

**Pull request merged**
