### PR TITLE
Switch to Component API for Conversations API

### PR DESCRIPTION
**Pull request by njsharpe**
Switch over to using Adventure's Component API for the Conversations API to bring things in line with generic Paper standards

### CODE REVIEW

**Comment by Leguan16** [comment]
Correct me if I am wrong but i think you should deprecate the old methods and create entirely new ones that take Components :)

**Comment by njsharpe** [comment]
> Correct me if I am wrong but i think you should deprecate the old methods and create entirely new ones that take Components :)

I cannot deprecate the old methods due to the method signatures. The signature of the old methods and the new methods are the same but the return type is different and because Java doesn't consider the return type in the method signature, I simply need to replace them entirely.

**Comment by Leguan16** [comment]
> > Correct me if I am wrong but i think you should deprecate the old methods and create entirely new ones that take Components :)
> 
> I cannot deprecate the old methods due to the method signatures. The signature of the old methods and the new methods are the same but the return type is different and because Java doesn't consider the return type in the method signature, I simply need to replace them entirely.

Usually you just use the record style getter/setter methods then 
- getInputNotNumericText -> inputNotNumericText
- getPrefix -> prefix
- getPromptText -> promptText

But how you do it right now it breaks backwards compatibility with bukkit and all plugins that used those methods before.

**Comment by njsharpe** [comment]
> > > Correct me if I am wrong but i think you should deprecate the old methods and create entirely new ones that take Components :)
> > 
> > 
> > I cannot deprecate the old methods due to the method signatures. The signature of the old methods and the new methods are the same but the return type is different and because Java doesn't consider the return type in the method signature, I simply need to replace them entirely.
> 
> Usually you just use the record style getter/setter methods then
> 
>     * getInputNotNumericText -> inputNotNumericText
> 
>     * getPrefix -> prefix
> 
>     * getPromptText -> promptText
> 
> 
> But how you do it right now it breaks backwards compatibility with bukkit and all plugins that used those methods before.

You make an excellent point about the record-style formatting for Component-based API changes, this is an oversight on my part and will be resolved ASAP. Thanks!

**Review by Owen1212055 — CHANGES_REQUESTED** [review]
I think that we didn't want to continue this API, and instead just deprecate it.... Although that has not been done yet! :)

**Comment by njsharpe** [comment]
> I think that we didn't want to continue this API, and instead just deprecate it.... Although that has not been done yet! :)

Why though? I rather like this API, as to why I'm making changes for it. Will there be a replacement planned? Capturing user input via the chat box with this API is much easier than book or sign captures. I would hate to see it go...

**Comment by lynxplay** [comment]
Thank you for the PR but sadly Owen is right.
We already declined further maintenance in an earlier [issue](https://github.com/PaperMC/Paper/issues/9877#issuecomment-2081338086).

In general the API is rather old and has become rather undesirable to maintain given its low adoption in the community.
Upstream also does not seem interested in this API being further developed.
Between the small userbase, a lack of interest in our and apparently upstream's team and its *interesting* interactions with chat signatures, the conversation API is, at least for this project, sunset. While it "works", we do not want to invest effort into maintaining patches for the conversation API.

I am sorry you put in all this work into a PR towards a sunset system, but I hope my above points at least make our reasoning clear as to why we are considering it sunset.

Thanks again for the effort!

**Pull request closed without merging**
