### PR TITLE
Fix item duplication

### PR DESCRIPTION
**Pull request by AlfieC**
Doesn't allow offline players/entities to drop items.

### CODE REVIEW

**Comment by Shevchik** [comment]
So i may guess that it happens when server disconnects player, but packet is already in a queue, am i right?
If so, maybe we should block packets, not actions?

**Comment by AlfieC** [comment]
That was my conclusion - but doing so would prevent players from doing actions & logging off on laggy servers. Or, if a player logged off during a lag spike then they would get "rolled back" per se

**Comment by Shevchik** [comment]
But some plugins may expect that event can be only thrown by online player.
Maybe there should be an option to block all packets from already offline players then.

PlayerConnectionsUtils can be modified to do the check to avoid adding a check to every packet in PlayerConnection

**Comment by AlfieC** [comment]
No need to actively avoid PlayerConnection patching - I'll update the PR shortly to avoid any packet processing of offline players. 

**EDIT:** Made it so that isFrozen() returns true if the player is offline. This achieves the same effect but with a lot less code on our part

**Pull request merged**
