### PR TITLE
Warn on plugins accessing faraway chunks

### PR DESCRIPTION
**Pull request by Owen1212055**
Warns when plugins do silly stuff with chunks.
Warns the cause of issues like: https://github.com/PaperMC/Paper/issues/7006

``[12:56:18 WARN]: [Paper-Test-Plugin] Plugin is getting a faraway chunk at (13225852, 22907744), this might cause issues.``

This adds a util method that can be used to see if code is executed by another plugin by looking for the first class loaded by a plugin in the stacktrace.

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Owen1212055** [comment]
Rebased

**Comment by Malfrador** [comment]
Wouldn't this be more useful if it used the worldborder instead of just always 30000000? Vanilla also uses that for most of its within bounds checks for things like chunk ticks, mob spawning, interact packets, structure locations etc. There is also a convenient `isChunkInBounds `method on `WorldBorder` for this exact purpose.

**Comment by electronicboy** [comment]
The concern here is more about stuff crashing the server rather than worrying about stuff peaking outside of the world border, think if stuff like a map rendering plugin started throwing warns because you generated a slither outside of the world border, etc

**Comment by Owen1212055** [comment]
Not to mention this is only meant for coordinates that might cause issues. In this case, chunks outside here seem to cause certain issues with generation.

**Pull request merged**
