### PR TITLE
Fix item locations dropped from campfires

### LINKED ISSUE #4259: [Bug] Items generated by cooking on a campfire collide strangely with non-solid blocks
### What behaviour is expected:
When items pop off of a campfire, they do not get stuck inside adjacent blocks or jump through blocks completely

### What behaviour is observed:
Items that pop off of a campfire they have a very high chance of getting stuck within a non-cube block and further pop outside of it OR the item seems to spawn inside of a solid block and delete itself, though this has only happened about twice in roughly 30 tests

(This behavior is **not observed** in Vanilla Singleplayer MC)

### Steps/models to reproduce:
Use this structure to simulate items being ejected towards from a block:
image
This is a simple cage of oak trapdoors around a campfire to hopefully direct an item towards a single opening - this however is not what happens 100% of the time.

image

Use this structure to simulate the loss of items when an item apparently generates or moves into the solid blocks and disappears: (this is far less common)

image
image

________________________

image

### Plugin list:
Plugins (18): 
AcceptTheRules, BuycraftX, ChestSort, DeathLocation*, DeluxeMenus, DiscordSRV, Essentials, EssentialsChat, GSit, InventoryRollback, LuckPerms, PlaceholderAPI, ResourceWorld, SmoothSleep, spark, TAB, Vault, WorldEdit

### Paper version:
git-Paper-157 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
bukkit.yml https://paste.gg/p/anonymous/873a12ccd46947d6b212ebb19d3a84ba

paper.yml https://paste.gg/p/anonymous/5f718735ae804e3bab3f410615f97540

spigot.yml https://paste.gg/p/anonymous/d45a060985534505ac1eec0d26950f16

### PR DESCRIPTION
**Pull request by BillyGalbreath**
Fixes #4259 by not flooring the blockposition among other weirdness

### CODE REVIEW

**Review by Proximyst — DISMISSED** [review]

**Review by electronicboy — DISMISSED** [review]
Accepting, but, if this is the issue, this makes me somewhat wear of dropItem in general, is this just bad luck on the basis of the "random" of the code causing it to clip in the campfire block itself?

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — DISMISSED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Review by aikar — APPROVED** [review]

**Comment by MiniDigger** [comment]
thanks, sorry for taking so long, looked at this last week and forgot to merge

**Pull request merged**
