### PR TITLE
Don't Display Success Message on Alias Reload Fail

### PR DESCRIPTION
**Pull request by willies952002**
Make it so that if reloading the command aliases fails, a failure message is displayed instead of always showing the success message. Also add "commands" to Tab Completion

**Note:** This required a signature change to Bukkit#reloadCommandAliases() so that it returns a boolean based on if the command aliases reloaded or not.

### CODE REVIEW

**Review by sweepies — CHANGES_REQUESTED** [review]
~~Correct "An Error Occurred While Trying to Reload Command Aliases." to "An error occurred while trying to reload command aliases."~~

**Comment by AlfieC** [comment]
Might be irrelevant now - but should include a specialsource mapping for the method signature change if specialsource is still used

**Comment by kamcio96** [comment]
You can add remapper into classloader ;P

**Comment by zachbr** [comment]
Special Source is not part of the process anymore and I do not want to add it or a similar system back in.

**Comment by aikar** [comment]
I think the risk is non existant for the signature change. Highly unlikely someone integrated this on an API level, and even then, the likelyhood of it being a public plugin trying to support multiple versions is even less so. 

If someone did integrate this, they can just update their plugin.

**Review by zachbr — APPROVED** [review]

**Review by kashike — APPROVED** [review]

**Pull request merged**
