### PR TITLE
Port 04-Util.patch from Tuinity

### PR DESCRIPTION
**Pull request by Spottedleaf**

### CODE REVIEW

**Review by aikar — APPROVED** [review]

**Comment by heathfx** [comment]
I'm not seeing the new/expected config options anywhere after deleting bukkit.yml, spigot.yml, paper.yml and tuinity.yml and running paper build 183

```
target-chunk-sends-per-player-per-second: 40.0
delay-chunkunloads-by: 10
world-settings:
  default:
    max-pending-chunk-loads: 1
    optimized-tracker: true
    optimized-tracker-track-range: -1
    optimized-tracker-untrack-range: -1
    no-tick-view-distance: -1
    spawn-limits:
      monsters: -1
      animals: -1
      water-animals: -1
      ambient: -1
```

**Comment by clrxbl** [comment]
None of those settings, or any settings from Tuinity have been ported to Paper. Nor does this issue mention anything about those settings either.

**Comment by heathfx** [comment]
what does this patch actually do then?

**Comment by clrxbl** [comment]
Probably nothing relevant for you. It doesn't port any of Tuinity's known features, just some codebase changes.

**Comment by mikroskeem** [comment]
Try looking at the code then, lol?

**Pull request merged**
