### PR TITLE
added can/setBreakDoor methods (#3837)

### LINKED ISSUE #3837: Add Method to Check if Zombies Can Bang on Doors
**Is your feature request related to a problem? Please describe.**
In my custom plugin, I'd like some sort of access to the Zombie "CanBreakDoors" property in "EntitySpawnEvent".  Specifically, my goal is to prevent the spawning of Zombies who are able to bang on doors (by cancelling the event for those who have that ability).    I can see methods like "isBaby" and "isConverting" and "isArmsRaised", but nothing related to being able to bang on doors.

**Describe the solution you'd like**
A method that exposes the "CanBreakDoors" field for Zombies so that I can cancel the spawning of Zombies who have the ability to bang on doors.

**Describe alternatives you've considered**
I am already able to prevent doors from breaking, but I'd like to prevent Zombies from even being able to bang on doors, whether or not the doors break.

**Additional context**
Thank you for considering this request.  If there is already a way to do this, I would love to know about it.

### PR DESCRIPTION
**Pull request by Machine-Maker**
Closes #3837 

Adds two methods to set and check if Zombies can break doors

### CODE REVIEW

**Comment by WonderDave** [comment]
Are these two methods waiting for some sort of review?  I'd love to see them become part of Paper.

**Review by Proximyst — DISMISSED** [review]

**Review by MiniDigger — DISMISSED** [review]

**Review by zachbr — DISMISSED** [review]

**Comment by MiniDigger** [comment]
@limbo-app ready

**Review by limbo-app — APPROVED** [review]
Pull request automatically approved for merging - a core team member has previously approved this pull request.

**Comment by MiniDigger** [comment]
I actually had a patch for this in a fork of mine and never upstreamed it...
thanks!

**Pull request merged**
