### PR TITLE
Updated Upstream (Bukkit/CraftBukkit/Spigot)

### PR DESCRIPTION
**Pull request by Machine-Maker**
Upstream has released updates that appear to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
e7b0f8d6 #⁠642: Add Crafting methods to API
9e58831e SPIGOT-6641: Use varargs in sendMessage
e409fe49 SPIGOT-6545: Unable to set Guardian target via API while awareness is disabled
6997c726 SPIGOT-6661: Fix missing radius from GenericGameEvent
02d03f35 SPIGOT-6369: Add ItemStack to HangingPlaceEvent

CraftBukkit Changes:
0abf420c SPIGOT-6665: Shearing a Snowman does not drop a carved pumpkin
e8e3cbcc #⁠893: Add Crafting methods to API
879acfee Fix missing varargs from previous commit
6572b9c3 SPIGOT-6641: Use varargs in sendMessage
9e06bb2a SPIGOT-6663: Chicken Jockeys chickens don't despawn
699f2d36 SPIGOT-6545: Unable to set Guardian target via API while awareness is disabled
8ffa54ba SPIGOT-6369: Add ItemStack to HangingPlaceEvent
c851639c SPIGOT-6645: Call EntityChangeBlockEvent before PlayerHarvestBlockEvent
8d244b0b SPIGOT-3725, SPIGOT-6638, MC-136917: Properly clear tile entities before replacing

Spigot Changes:
18c71bf4 Rebuild patches

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by tastybento** [comment]
FYI, a number of admins reported chest inventories were empty since Build 124, which is this PR. The latest Spigot upstream build does not have the issue. I believe the fix is [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/aa69d1cfb99f4784ed19b8918a7f5c1780b55fdb), which is related to the previous `8d244b0b SPIGOT-3725, SPIGOT-6638, MC-136917: Properly clear tile entities before replacing`.

**Comment by Machine-Maker** [comment]
@tastybento fixed in 9a0263e2ac2a4bd52274c836b6ee70f064acef74

**Comment by gecko10000** [comment]
Still happening in build 130, unfortunately. Not sure why, as out of testing on Spigot, Paper, Tuinity, and Purpur, only Paper continues to have this issue.

**Comment by Proximyst** [comment]
Please open a new issue in that case; we need proper reproduction steps as I couldn’t reproduce it.

**Pull request merged**
