### PR TITLE
Begin switching to JSpecify annotations

### PR DESCRIPTION
**Pull request by Machine-Maker**
Adjusts the annotation test to check if the class as the NullMarked annotation, and if it does, to skip the whole class.

This will probably be several PRs so it's not just one HUGE pr.

### CODE REVIEW

**Comment by electronicboy** [comment]
Because JSpecify is the new annotation library developed by a commit, including JetBrains, google, etc., in order to create one true framework. it being new means that it's not going to have as many users yet.

**Comment by electronicboy** [comment]
Once again, it's new; it's not going to show up high on the lists, they don't blindly show preference to their own library

**Comment by powercasgamer** [comment]
>  It doesn't even show on the list.

It obviously won't show up in the list if you haven't added it to your project. https://i.imgur.com/wixYnGI.png

**Comment by kennytv** [comment]
There is no "default" included nullness annotations beyond javax', jetbrains annotations are their own library you have to explicitly depend on like any other. If you need help updating your dependencies or understanding the purpose of these libraries, you can ask in our Discord

**Pull request merged**
