### PR TITLE
Fix Naming issue inside Add PlayerArmorChangeEvent

### LINKED ISSUE #11612: PlayerArmorChangeEvent returns the same item for both old item and new item.
### Expected behavior

The PlayerArmorChangeEvent should return the old item and the new item.

### Observed/Actual behavior

The PlayerArmorChangeEvent returns the old item for both the old item variable and new item variable.

### Steps/models to reproduce

1. Write code that uses the PlayerArmorChangeEvent
2. Call the event by swapping armor.
3. Ouput the data for each item

### Plugin and Datapack List

A baseline testing plugin with just that function.

### Paper version

[09:59:05 INFO]: Checking version, please wait...
[09:59:06 INFO]: This server is running Paper version 1.21.3-DEV-master@661839e (2024-11-13T06:32:18Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-131-84281ce (MC: 1.21.1)

### Other

_No response_

### PR DESCRIPTION
**Pull request by vivianh-dev**
Fix for issue #11612 (Accidentally used master last time)

### CODE REVIEW

**Review by lynxplay — COMMENTED** [review]
I think this would benefit from obfhelpers on the respective variable declarations.
E.g
```patch
diff --git a/src/main/java/net/minecraft/world/entity/LivingEntity.java b/src/main/java/net/minecraft/world/entity/LivingEntity.java
index e86314de8d..a06d52a3a4 100644
--- a/src/main/java/net/minecraft/world/entity/LivingEntity.java
+++ b/src/main/java/net/minecraft/world/entity/LivingEntity.java
@@ -3392,9 +3392,9 @@ public abstract class LivingEntity extends Entity implements Attackable {
                     throw new MatchException((String) null, (Throwable) null);
             }
 
-            ItemStack itemstack2 = itemstack1;
+            ItemStack itemstack2 = itemstack1; final ItemStack oldEquipment = itemstack2; // Paper - PlayerArmorChangeEvent - obfhelper
 
-            itemstack = this.getItemBySlot(enumitemslot);
+            itemstack = this.getItemBySlot(enumitemslot); final ItemStack newEquipment = itemstack;// Paper - PlayerArmorChangeEvent - obfhelper
             if (this.equipmentHasChanged(itemstack2, itemstack)) {
                 // Paper start - PlayerArmorChangeEvent
                 if (this instanceof ServerPlayer && enumitemslot.getType() == EquipmentSlot.Type.HUMANOID_ARMOR) {
```

**Review by kennytv — APPROVED** [review]
Thanks!

**Comment by vivianh-dev** [comment]
Wasn't sure about the helpers, since the variable names themselves seem to be weird so I figured someone may want to change them. Never worked with obfuscated code so wanted to minimize the impact.

**Review by NoahvdAa — APPROVED** [review]
+1 on what lynx said, lgtm for the rest

Congrats on making your first PR, welcome to Paper :)

**Comment by vivianh-dev** [comment]
OBFHelper added! Interesting thing, definitely going to look into it should I notice anything else.

**Comment by Lulu13022002** [comment]
So now you can use the new explicit vars see: https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md#obfuscation-helpers

**Comment by vivianh-dev** [comment]
Ah I thought it was something for the JVM/Javadocs. Thanks!

**Comment by vivianh-dev** [comment]
I'm sure more could be used to make the code more readable, but I don't know which changes came from deobfuscation and don't want to risk messing that stuff up.

**Review by lynxplay — APPROVED** [review]

**Comment by vivianh-dev** [comment]
Thank you for the nitpicks, wasn't sure what the proper formatting would be  and didn't want to risk messing w/ something that shouldn't change.

**Pull request merged**
