### PR TITLE
Fix nerf-spawner-mobs not persisting restarts

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Comment by electronicboy** [comment]
part of me is mixed between this being okay, but also wondering if we should just be storing the state of the flag seperatly, I can understand why people might love this as-is, but i question the current exposure of this behavior to plugins, beyod the crappy internal field name... *thonks*

**Comment by BillyGalbreath** [comment]
I originally had what you suggest, but z said no. https://discordapp.com/channels/289587909051416579/289587909051416579/675429009596743691

**Comment by electronicboy** [comment]
That's fine then, at least it gets me outta the "eer" point

**Review by electronicboy — APPROVED** [review]

**Comment by BillyGalbreath** [comment]
No longer relevant now with the awareness API

**Pull request closed without merging**
