### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rafalohaki**

### CODE REVIEW

**Comment by electronicboy** [comment]
Thanks for the PR, but, this will be updated when that section is updated for 1.17

**Comment by rafalohaki** [comment]
well, i requested  1 commit into PaperMC:dev/1.17, so its right section

**Comment by Prof-Bloodstone** [comment]
Your PR fixed nothing - whole README is outdated. No longer need maven or bash, the dependency group also changed.

The whole README and contributing guidelines need to be updated, which will be done once tooling stabilizes a bit more.

**Comment by Doc94** [comment]
This changes are already made in another PR https://github.com/PaperMC/Paper/pull/5338

**Pull request closed without merging**
