### PR TITLE
Fix server deadlock when loading some chunks

### PR DESCRIPTION
**Pull request by Spottedleaf**
Upstream has released updates that appears to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

CraftBukkit Changes:
7554e08e Add UUID support to CraftProfileBanList
3fe37460 SPIGOT-5378: Fix TileEntity fixer deadlock
12386dd4 SPIGOT-5375: Add spaces to coordinates from tile fixer
606c19e2 SPIGOT-5373: Simultaneous left+right click in creative mode does not work
13caf848 SPIGOT-5370: Fix Block#rayTrace considering other blocks.

### CODE REVIEW

**Comment by Spottedleaf** [comment]
Check https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/3fe3746012d5f3575a063425b972f3aef47f8d71 for details

**Comment by ghost** [comment]
>.... [12:53:54 ERROR]: --- **DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-219 (MC: 1.14.4)** ---
>.... [12:53:54 ERROR]: The server has not responded for 15 seconds! Creating thread dump
>.... [12:53:54 ERROR]: ------------------------------
>.... [12:53:54 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [12:53:54 ERROR]: The server is waiting on these chunks: [[( 12142,63258) in 'world'], [( 12142,63258) in 'world']]
>.... [12:53:54 ERROR]: ------------------------------
>.... [12:53:54 ERROR]: Current Thread: Server thread
>.... [12:53:54 ERROR]: PID: 31 | Suspended: false | Native: false | State: TIMED_WAITING
>.... [12:53:54 ERROR]: Stack:
>.... [12:53:54 ERROR]: sun.misc.Unsafe.park(Native Method)

"do not report this to paper - this is not a bug or a crash" lul server deadlocked once an hour and I though I was the problem!

**Comment by skerit** [comment]
I'm running build 221, but I still had a deadlock issue:

```
[21:39:57] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-221 (MC: 1.14.4) ---
[21:39:57] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[21:39:57] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:39:57] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:39:57] [Paper Watchdog Thread/ERROR]: The server is waiting on these chunks: [[( 316,8) in 'world_the_end']]
[21:39:57] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:39:57] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[21:39:57] [Paper Watchdog Thread/ERROR]: 	PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
[21:39:57] [Paper Watchdog Thread/ERROR]: 	Stack:
[21:39:57] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.bi(IAsyncTaskHandler.java:131)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:285)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:373)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IWorldReader$1.tryAdvance(IWorldReader.java:158)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.StreamAccumulator$1.tryAdvance(SourceFile:31)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.VoxelShapes.a(VoxelShapes.java:178)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.Entity.a(Entity.java:851)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.Entity.a(Entity.java:839)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.Entity.e(Entity.java:801)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.Entity.move(Entity.java:560)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2185)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityHuman.e(EntityHuman.java:1495)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2559)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityHuman.movementTick(EntityHuman.java:416)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2321)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:426)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[21:39:57] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
```

**Comment by Spottedleaf** [comment]
please provide the full watchdog log

**Comment by electronicboy** [comment]
We'd need the full log, that just shows that your server is waiting on a chunk load

**Comment by skerit** [comment]
With watchdog, you mean this? Or really the entire log of the process? 
[watchdog.log](https://github.com/PaperMC/Paper/files/3776394/watchdog.log)

**Comment by Redstone-ray** [comment]
Can confirm, deadlock still exists in paper 221

**Comment by electronicboy** [comment]
We'd need logs, skerit's issue is somewhat deeper, looks like the chunk load request went missing or something

**Comment by tpsutphin** [comment]
I can confirm it is still an issue in paper 225

**Comment by electronicboy** [comment]
If you're having issues, please create a new issue including the relevant information, e.g. the actual server logs.

**Pull request merged**
