### PR TITLE
Only capture actual tree growth

### LINKED ISSUE #6458: Observers detect saplings advancing their growth stage once and then they stop
### Expected behavior

Hi! Observers should be able to detect when a sapling advances its growth stage, even when surrounded by opaque blocks with a redstone lamp on top to give enough light for the sapling to advance the next stage.
It should fire every 8 minutes or so on average, but it can be manually activated using bonemeal.

If my explanation of the expected behavior sounds confusing, I'll attach a link to a [video](https://www.youtube.com/watch?v=OrvPW1rI4Js) made by ilmango that showcases thew contraption I'm mentioning.
The contraption I'm mentioning

### Observed/Actual behavior

On the server I play on, both in creative and survival (I attach a screen with the paper version), the observer only detects the growth stage advancement, but then it stops receiving block updates from the sapling, even if I bonemeal it.

### Steps/models to reproduce

Just build the contraption I attached in the expected behavior section of this issue and spam bonemeal on the sapling. It should work in vanilla.

### Plugin list

plugin list

### Paper version

paper version

DISCLAIMER: The server I'm playing on doesn't run the latest version of Paper, but going through all the 102 changelogs I haven't seen any mention of this issue, so it may still be affecting newer versions. Also I aked on the Paper Discord and they suggested to write this issue since it sounds like a bug. This is to inform that I checked the "I am running the latest version of Paper available from https://papermc.io/downloads. *" box, even though this isn't the latest version. 

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_No response_

### PR DESCRIPTION
**Pull request by Machine-Maker**
Fixes #6458

I figured that instead of trying to find all the places where this needed to be changed, I'd only attempt to "revert" the change where it mattered, in the tree growers.

### CODE REVIEW

**Review by lynxplay — APPROVED** [review]
Probably the best solution we have for ensuring the sappling <-> air interchange without re-implementing the mess that is the captureBlockState boolean.

The patch resolved the mentioned issue when tested locally for me.
Additionally I made sure that the author did not edit the patch by hand :upside_down_face:

**Comment by Machine-Maker** [comment]
Rebased for 1.18.1

**Comment by Machine-Maker** [comment]
Rebased for 1.18.2

**Comment by Machine-Maker** [comment]
Rebased for 1.19.3

**Review by kennytv — APPROVED** [review]

**Pull request merged**
