### PR TITLE
[CI-SKIP] set shwordsplit on zsh

### PR DESCRIPTION
**Pull request by electronicboy**
By default, zsh will not expand the spaces inside of the gitcmd
variable, and will attempt to execute as is, causing the git command
to fail. This patch fixes this by enabling the shwordsplit option
if not already enabled (and disables afterhand if it was enabled by us)

### CODE REVIEW

**Comment by LaxWasHere** [comment]
✅ 🌯

**Review by LaxWasHere — APPROVED** [review]

**Comment by zachbr** [comment]
- [x] Windows 10 1803 - git-for-windows 2.17.1.windows.2 - bash 4.4.19
- [x] Ubuntu 18.04 - bash 4.4.19
- [x] macOS 10.13 - zsh 5.5.1
- [ ] macOS 10.13 - bash 3.2.57 - Functional but has problems
```
bash-3.2$ ./paper e a
./paper: line 10: setopt: command not found
Successfully rebased and updated refs/heads/master.
./paper: line 191: conditional binary operator expected
./paper: line 191: syntax error near `revertwordsplit'
./paper: line 191: `if [[ -v revertwordsplit ]]; then'
```

**Comment by electronicboy** [comment]
Should be fixed, trust apple to be shipping an outdated version of bash \o/

**Comment by electronicboy** [comment]
Closing this PR, I messed up on branching (aka, completely forgot) and ended up biting myself in the foot; I'm going to set the option required here locally, worth as a note for anybody who is using ZSH on how to fix compiling if they hit any issues;
If somebody is better with shell scripts and wishes to PR something which solves this, that would be nice!

**Pull request closed without merging**
