### PR TITLE
Deprecate set/doesBounce from Projectile

### PR DESCRIPTION
**Pull request by Owen1212055**
Has done nothing for 10 years

### CODE REVIEW

**Review by kennytv — APPROVED** [review]

**Comment by Owen1212055** [comment]
Rebased

**Comment by kennytv** [comment]
a 1.19 removal is honestly a bit soon lol

**Comment by Owen1212055** [comment]
~~Okay, another 10 years it is!~~
Should the for ScheduledForRemoval annotation be removed then?

**Comment by kennytv** [comment]
I'd say just remove the version and we'll remove the method whenever we think it's been deprecated for long enough (probably 1.20, but god knows)

**Comment by Owen1212055** [comment]
Rebased and done.

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
