### PR TITLE
Fix silly Javadocs in Bukkit.broadcast(BaseComponent) and Bukkit.broadcast(BaseComponent...)

### PR DESCRIPTION
**Pull request by Spottedleaf**
The Javadocs for Bukkit.broadcast(BaseComponent) and Bukkit.broadcast(BaseComponent...) specified a **single player**. Changed to specify "all online players"

### CODE REVIEW

**Comment by 0x277F** [comment]
You think that's bad, you should take a look at the javadocs in the chunkgen code.

**Comment by Spottedleaf** [comment]
No, I think this (old patch) is O.K Javadocs by **Bukkit's** standards.

**Comment by Spottedleaf** [comment]
Didn't change the Javadocs in the Server interface...

**Comment by zachbr** [comment]
I'll get it here in a second

**Pull request merged**
