### PR TITLE
Updated Upstream (Bukkit/CraftBukkit)

### PR DESCRIPTION
**Pull request by kennytv**
Upstream has released updates that appear to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
cfd18bd0 SPIGOT-6436: Add Player#stopAllSounds

CraftBukkit Changes:
b58f4299 SPIGOT-6436: Add Player#stopAllSounds
eb191612 SPIGOT-6783: Items do not appear in custom anvil inventories
376edf4f SPIGOT-6779: Fix LivingEntity#attack for Player entities
747a73ec SPIGOT-6772: Use entity mailbox and re-schedule entities if they get unloaded

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Bobcat00** [comment]
Is the Spigot getEntities() change compatible with whatever changes Paper made to entity processing?

**Comment by kennytv** [comment]
No, it was broken before, but the Spigot code there still doesn't really look all that enticing. Before that code is re-added, it needs testing or improvement

**Comment by Bobcat00** [comment]
But didn't this PR put back the spigot code? Or is Paper still using a different implementation?

**Comment by kennytv** [comment]
No, it's still removed

**Pull request merged**
