### PR TITLE
Update TerminalConsoleAppender + JLine, use Jansi instead of JNA

### LINKED ISSUE #1690: Solaris / SmartOS - Server console goes unresponsive after running command
### What behaviour is expected:
```
>say Can you hear me?
[22:12:59 INFO]: [Server] Can you hear me?
>
```
Command is entered and executed command prompt renders.  Further commands show up when entered.  Logging data from game continues uninterrupted.  This behavior occurs on vanilla, and on Spigot.

### What behaviour is observed:
```
> say Can you hear me?
[22:11:47 ERROR]: Caught previously unhandled exception :
[22:11:47 ERROR]: java.io.IOError: java.io.IOException: Error executing 'stty icrnl ixon echo icanon eof ^D eol ^A min 11111111111111111111111111111111 time 11111111111111111111111111111111': stty: invalid integer argument: '11111111111111111111111111111111': Value too large for defined data type

```
Command is entered but fails to execute.  Exception is raised.  Command prompt is not rendered again.  Further commands fail to show when typing.  Logging data from game continues uninterrupted.  This behavior occurs on paper.

### Steps/models to reproduce:
I'm running the following java options on a test server:
```java -Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar server.jar```

### Plugin list:
No plugins are installed on this test server.

### Paper build number:
```
This server is running Paper version git-Paper-451 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-448 (MC: 1.13.2)
Checking version, please wait...
You are running the latest version
```

### Anything else:
The operating environment is Illumos/SmartOS:
```
System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.181-b00) Host:  SunOS 5.11 (amd64)
```

Attempting to execute the stty command directly on the shell yielded the same results:
```
$ stty icrnl ixon echo icanon eof ^D eol ^A min 11111111111111111111111111111111 time 11111111111111111111111111111111
stty: invalid integer argument: '11111111111111111111111111111111': Value too large for defined data type
```
Why does paper need 11 nonillion character minimum for a completed read, or a 3.52x10^22 year timeout on input?  These values seem kind of off.

### LINKED ISSUE #1734: Uppercase Color Codes Incorrectly Handled
### What behavior is expected:
Both uppercase and lowercase color codes should be expected to validate when used in plugins or chat (§e would be the same as using §E and &a would be the same as using &A)

### What behavior is observed:
The console just spits out the color code without parsing it. Sometimes, it glitches and repeats certain characters. However, the game itself parses the color code correctly.

### Steps/models to reproduce:
1. Create a dummy plugin with a line in it like `System.out.println("§EHi);`
2. Type a message like `&ETest` in the chat (Essentials installed)

### Plugin list:
- EssentialsX
- EssentialsX-Chat
- A custom plugin with the aforementioned line in it

### Paper build number:
git-Paper-474 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
Translation of color codes in individual plugins to lower-case may solve this issue temporarily, and testing was done in a Spigot 1.13 server, and the issue didn't occur there.

### Images of the issue occurring:
issue1
issue2
issue3

### PR DESCRIPTION
**Pull request by stephan-gh**
Fixes #1734. Fixes #1690 (?)

There were a few larger changes (new JLine/JNA version, changes in implementation of colors in TCA), so I am looking for some testing before I release the new version of TCA. @zachbr asked for a new release in https://github.com/Minecrell/TerminalConsoleAppender/issues/7, so maybe you'd like to help with testing on Paper. :)

It looks fine to me in IDE+Terminal on Arch GNU/Linux, but I cannot test on macOS or Windows at the moment.

### CODE REVIEW

**Comment by zachbr** [comment]
The JNA change is breaking, this will need to be held until 1.14.4 if that is required.

**Comment by stephan-gh** [comment]
> The JNA change is breaking, this will need to be held until 1.14.4 if that is required.

It seems so: https://github.com/jline/jline3/commit/9d24f655b78d52a871d109f1676ff788e372ed3b

Edit: Urgh, this is going to cause me headaches for Forge...

**Comment by stephan-gh** [comment]
@zachbr Do you use JNA for anything except TCA on Paper?
Given that the new JNA version is going to cause me headaches for Forge, I've been thinking about using [Jansi](https://github.com/fusesource/jansi) again. There is no functional difference for JLine; both are equally supported. And Jansi is actually much smaller (280 KB vs 1400 KB for JNA).

I think I stopped using Jansi back then because I felt it was old and somewhat messy. But it has been continuously updated together with JLine, so it's probably fine.

**Comment by astei** [comment]
@DemonWav has a branch for his experimental `paperd` daemon which uses JNA.

**Comment by astei** [comment]
I can test this new TCA release in Velocity if you want.

**Comment by stephan-gh** [comment]
@astei Sure. Any help with testing is appreciated!

**Comment by stephan-gh** [comment]
> @DemonWav has a branch for his experimental `paperd` daemon which uses JNA.

Okay. Either way is fine really. I think I'll just make it clear in the TCA documentation that both can be used. Right now it strongly recommends JNA for no real reason.

**Comment by zachbr** [comment]
Looks good on macOS 10.15 and Windows 10 20H1

**Comment by DenWav** [comment]
I'm not doing anything fancy with JNA in [`feature/daemon`](https://github.com/PaperMC/Paper/tree/feature/daemon) that needs any one feature over another, as long as we don't downgrade.

It's also certainly possible for me to switch to a JNI approach. JNA doesn't require any other native code which is why I went with it, but we'd only need a small amount of C code to use JNI instead which could be a separate project where the prebuilt binary is simply downloaded at build time for Paper.

Another option that would be even better if I could get it to work is the JNI code could be part of the `paperd` binary itself, which could be used in daemon mode as well...

So don't worry about me, if removing JNA is the best way forward for this, go for it, using JNI won't be that hard (and will have a lot less overhead too).

**Comment by stephan-gh** [comment]
> So don't worry about me, if removing JNA is the best way forward for this, go for it, using JNI won't be that hard (and will have a lot less overhead too).

I have decided that I will stop recommending one of them, so you will need to decide what to use in Paper. You could keep JNA now and switch to Jansi later once an alternative has been written for paperd.
Or whatever you like :) The functional difference is so minor that it does not matter which one is used.

**Comment by zachbr** [comment]
I wouldn't mind *not* using JNA because it would let us backport this change to older versions. I will have to try and find some time to test 1.12.2 and 1.13.2 with the jansi dependency instead.

**Comment by stephan-gh** [comment]
I've pushed a commit to TCA to stop depending on JNA explicitly. Therefore each project using TCA now has to add an explicit dependency on either `jline-terminal-jansi` or `jline-terminal-jna`.

I've changed this PR to depend on Jansi instead (and keep the JNA dependency as-is), so it is no longer breaking :)

**Comment by DenWav** [comment]
I'm testing out a new JNI implementation for `paperd`, should have it working today if all goes well. Should be cool to remove the JNA dep.

**Comment by DenWav** [comment]
`paperd` and the `feature/daemon` branch are now moved off JNA and onto JNI.

**Comment by stephan-gh** [comment]
Yay for conflicts! Now fixed :)
/me glances at #2324

**Comment by zachbr** [comment]
I've added a commit to this PR to remove the JNA runtime dependency.
Jansi version confirmed as expected on Arch Linux, macOS 10.15, and Windows Server 2016

**Comment by stephan-gh** [comment]
> I've added a commit to this PR to remove JNA.
> Jansi version confirmed as expected on Arch Linux, macOS 10.15, and Windows Server 2016

Great, thank you! I will release the new version of TCA soon and then we can merge this. 👍

**Comment by stephan-gh** [comment]
Updated TerminalConsoleAppender to the 1.2.0 release, ready for merge now!

@zachbr I squashed your commit into mine. I hope you don't mind :)

**Review by zachbr — APPROVED** [review]

**Review by DenWav — APPROVED** [review]

**Comment by zachbr** [comment]
Thanks for your continued support and assistance with TCA :+1:

**Comment by HexedHero** [comment]
Since this update me and a lot of other owners have had this issue with their console:
https://cdn.hexedhero.com/u/uc2OBgyS7N.jpg

Using Pterodactyl 0.7.14
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)

Using `-Dterminal.jline=false -Dterminal.ansi=true` startup flags completely removed the >.... issue

**Comment by clrxbl** [comment]
@HexedHero Yeah I asked Minecrell about this earlier, I've made an issue for the Pterodactyl panel & the workaround PR with those arguments has been merged into parkervcp's eggs. (so this should be built in with the next daemon update) https://github.com/parkervcp/eggs/pull/261

**Comment by stephan-gh** [comment]
I will need to reproduce this myself with some debugging code to be able to say more. The problem is likely a mixture of many things. JLine prints `>....` in weird situations (see https://github.com/jline/jline3/issues/411 for a similar problem that was already fixed), but Pterodactyl likely provides an incomplete console implementation if it is visible.

Unfortunately, Pterodactyl does not quite look like it can be installed in a few minutes....

**Pull request merged**
