### PR TITLE
Added smelt checking in "Material" class

### PR DESCRIPTION
**Pull request by TrevorMickelson**
I did this to add a faster time complexity for checking the smelt result. And it just makes life better. I needed this for a CustomEnchants plugin a while back, and ended up having to create a custom solution because it wasn't built in. Figured I'd try to build it in, and see if you guys like it! Thank you! <3

### CODE REVIEW

**Comment by electronicboy** [comment]
given the plans to basically rewrite this entire class, definitely not fond of adding a static block to the class

**Comment by TrevorMickelson** [comment]
> 

Oh, I wasn't aware you were going to rewrite the class. That's interesting.

**Comment by qixils** [comment]
the main issue i have with this is that recipes are not static, as they can be added by both datapacks and plugins, and the Sponge+Paper APIs are generally moving away from hardcoding dynamic data like this. it also doesn't quite make sense to just ignore the NBT data of the input/output items as is being done here. i think this is better left to plugins to handle

**Comment by TrevorMickelson** [comment]
> the main issue i have with this is that recipes are not static, as they can be added by both datapacks and plugins, and the Sponge+Paper APIs are generally moving away from hardcoding dynamic data like this. it also doesn't quite make sense to just ignore the NBT data of the input/output items as is being done here. i think this is better left to plugins to handle

Interesting, I hadn't considered plugins implementing custom recipes. I really like the idea of getting the smelt result easily though. I may try to think of a more dynamic way to do it. It's definitely possible.

**Pull request closed without merging**
