### PR TITLE
Chunk.getBlockArray API

### PR DESCRIPTION
**Pull request by PaulBGD**
The intent behind this API is to provide a way for plugins to access the blocks in a chunk without having to create any allocations. Using of the other APIs when implementing anything that scans chunks will create a ridiculous amount of allocations due to all the arrays being copied.

As for the javadocs, please someone help. I have no idea how to describe this to your average developer :(

### CODE REVIEW

**Comment by MiniDigger** [comment]
mmmh. not a fan of the getChunkData name, since we already have a ChunkData class, which is related https://papermc.io/javadocs/paper/1.16/org/bukkit/generator/ChunkGenerator.ChunkData.html
exposing flat arrays like that is also not a nice api. I cant look at how ChunkData is implemented rn, but isn't that just a nice wrapper for such an array? couldnt we reuse that here? or would that lead to allocations again?

**Comment by PaulBGD** [comment]
I agree, getChunkData isn't a good name for it either. The issue with using ChunkData is a lot of unnecessary copies, allocations, and such. On top of all of that, once you're using it you lose a lot of performance due to dispatching the function calls. This PR contains an implementation that ideally (assuming the caller properly reuses the array) creates 0 allocations, besides the initial array. For things like scanners calculating Skyblock levels, or things like [Insights](https://github.com/InsightsPlugin/Insights) which scans a lot of chunks in the world, you run into GCs forced nearly every second just trying to scan blocks.

For the name, maybe loadBlockData? Although I think load generally makes me think of IO, so maybe not.

**Comment by PaulBGD** [comment]
Here's a few examples of plugins that I could see using an API like this and their NMS hackery they use now:

https://github.com/OmerBenGera/SuperiorSkyblock2/blob/625829a8d5028cd74d51698681c198156e159133/v1_16_R3/src/main/java/com/bgsoftware/superiorskyblock/nms/NMSBlocks_v1_16_R3.java#L379-L419

https://github.com/InsightsPlugin/Insights/blob/03e3b531131f738ce5390c75eb7845481e7fb4d4/Insights-API/src/main/java/dev/frankheijden/insights/api/concurrent/containers/ChunkContainer.java#L79-L107

**Comment by PaulBGD** [comment]
Rebased and renamed, open to opinions.

**Comment by Draycia** [comment]
> open to opinions.

pineapple belongs on pizza

**Comment by electronicboy** [comment]
being perfectly honest, this API already has a crosshair on it for deprecation, the returning of only materials vs like say, BlockData, seems very short sighted on what the method implies that it wants to return

I can understand the merits of having a faster, less memory trashing alternative to the ChunkSnapshot API, but, I don't see what this really offers bar moving some of the resource frashing from reading the data to creating it, while at the same time limiting its usefulness

Needs to factor in getWorldMin, or whatever upstream called it, and the silent replacing of a miss sized array also seems case-specific impl detail

**Comment by PaulBGD** [comment]
Taking a step back, I agree entirely. The use-case for this API to be used correctly is niche, and it'd be better to implement this as part of a fully, non-version dependent API. I think something with less memory trashing is still useful though, so I've continued this into #5439

**Pull request closed without merging**
