### PR TITLE
Don't allow entities to become passengers of themselves

### PR DESCRIPTION
**Pull request by AlfieC**

### CODE REVIEW

**Review by Ichbinjoe — APPROVED** [review]

**Comment by AlfieC** [comment]
Addresses #573.

**Comment by AlfieC** [comment]
Addresses #573

**Comment by aikar** [comment]
This is Paper code you are modifying, so it wouldn't be a new patch. But this isn't the right answer anyways.

We need to block adding yourself as a passenger to yourself instead if there is a problem with that.

**Comment by AlfieC** [comment]
Altered PR

**Comment by AlfieC** [comment]
oops fixing it now

**Comment by AlfieC** [comment]
fixed

**Comment by Spottedleaf** [comment]
Motivation?

**Comment by prplz** [comment]
@Spottedleaf #572

**Review by prplz — APPROVED** [review]

**Pull request merged**
