### PR TITLE
Keep newlines in outdated client/server message

### LINKED ISSUE #10041: spigot's `messages.outdated-client` no longer supports multiple lines
### Expected behavior

In 1.20.1, all lines was sent to the player if he tries to connect using old game version.

### Observed/Actual behavior

Now, only `Line 1` is sent.

### Steps/models to reproduce

image

1. Download experimental server build from https://papermc.io/downloads/paper
2. Run it, accept the EULA, run it again and stop
3. Change `messages.outdated-client` in `spigot.yml` to something similar to the screenshot above
4. Run server again
5. Try to connect to it using Minecraft 1.20.1
6. See that only `Line 1` is sent from the server

### Plugin and Datapack List

None

### Paper version

1.20.4-330

### Other

I can't reproduce this on `3973-Spigot-ce0f71e-e37e29c (MC: 1.20.4)`.

Also note that `Server#spigot().getSpigotConfig().get("messages.outdated-client");` returns all lines correctly, so looks like the issue is somewhere between configuration file reading and disconnection packet sending.

### PR DESCRIPTION
**Pull request by Warriorrrr**
Fixes #10041

---
Download the paperclip jar for this pull request: [paper-10042.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/1135456730.zip)

### CODE REVIEW

**Comment by 456dev** [comment]
Do the rest of spigot yml message need changing too?

**Review by Machine-Maker — CHANGES_REQUESTED** [review]
We should use adventure's legacy serializer instead of CraftChatMessage. Change the field type/name to adventure component, then wrap the component in PaperAdventure.asVanilla.

**Review by Machine-Maker — CHANGES_REQUESTED** [review]
It needs to use the legacySection serializer

**Review by Machine-Maker — APPROVED** [review]

**Comment by molor** [comment]
Add `build-pr-jar` label please

**Comment by molor** [comment]
(where is the link to jar file? o: I want to test it, but I can't)

**Comment by Machine-Maker** [comment]
Oh yeah, ok. The events won't run if the branch has conflicts. That is a github thing. So when kenny added the label yesterday, it didn't build a jar

**Comment by molor** [comment]
So it needs a rebase? Or what someone need to do?

(currently this issue prevents us from updating our server to 1.20.4 because we have an Easter egg consisting of several lines in outdated client message :c)

**Pull request merged**
