### PR TITLE
Updated Upstream (Bukkit/CraftBukkit)

### PR DESCRIPTION
**Pull request by Machine-Maker**
Upstream has released updates that appears to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

Bukkit Changes:
f47abd88 SPIGOT-6242: Fix some file line endings
de96535b SPIGOT-6234: enum classes don't serialize properly when implementing ConfigurationSerializable

CraftBukkit Changes:
4475707d SPIGOT-6244: /spawnpoint ignores angle
8b3b096d SPIGOT-6242: Fix some file line endings
4b33c749 SPIGOT-6186: Canceling a CreatureSpawnEvent​ results in a "Unable to summon entity due to duplicate UUIDs" error
2b3ca726 SPIGOT-6236: Vehicle passenger portal cooldown does not change

### CODE REVIEW

**Comment by aikar** [comment]
erm you did something wrong here, its missing 0402 and it still fails.

@Chew did have an attempt at this last night and gave them the change needed to finish it.

**Comment by Chew** [comment]
Ahh haven't done it yet, I can try again when I get a chance. Mine was I put it in the wrong spot, but it did compile

**Comment by Machine-Maker** [comment]
Yep, realized it like 15 seconds after I opened the pr. I think I got it now tho... two seconds while its rebuilding patches.

**Comment by Machine-Maker** [comment]
actually, it looks like server patch 0546 can be removed now. All its adding is some comments. unless you wanna keep the comments.

**Comment by aikar** [comment]
yep was just about to say that before i saw your comment. Spigot fixed it themselves.
go ahead and remove it, no point commenting on something Spigot has now done.

**Comment by Machine-Maker** [comment]
Yep ok. Its gone. It doesn't need to be moved to the `removed` folder right? since it doesnt have any content that might wanna be referenced later.

**Review by aikar — APPROVED** [review]

**Pull request merged**
