### PR TITLE
Fix crash when player's hand is changed to new instance of  air in PlayerInteractEvent

### PR DESCRIPTION
**Pull request by Toranktto**
When you are in creative mode and right click air with non-empty hand (clicking air with empty hand is not sent to server) and server has plugin that change player's hand to new instance of air itemstack, server is crashing.
```
on right click:
	player's gamemode is creative
	player's target block is not set
	set player's tool to 1 of air # Crash
```
or equivalent Java code:
```java
@EventHandler
public void onInteract(PlayerInteractEvent event) {
    Player player = event.getPlayer();
    if (player.getGameMode() != GameMode.CREATIVE || event.getAction() != Action.RIGHT_CLICK_AIR) {
        return;
    }

    player.getInventory().setItemInMainHand(new ItemStack(Material.AIR)); // Crash
}
```

Crash report:
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11.11.19 13:27
Description: Exception in server tick loop

java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:109)
	at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:897)
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:403)
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1416)
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
	at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by electronicboy** [comment]
I'm concerned that such a change would have other potential side effects, e.g. plugins modifiying the ItemStack itself in the event vs modifying just the players hand; In part, plugins /really/ need to be responsible with their modifications here, this is just one of many areas in which such an exception could be thrown due to plugins incorrectly modifying items

**Comment by electronicboy** [comment]
Ignore that, I thought that CB was potentially cloning the item somewhere, I'm not 100% convinced on this one, however; Feels like the most compatible option would be to replicate the isEmpty check before calling the interaction manager, mainly as it would potentially cover more scenarios

**Review by electronicboy — APPROVED** [review]

**Comment by HexedHero** [comment]
Thanks for the PR, I had the issue a few days ago.

**Comment by zachbr** [comment]
I screwed up the rebase, that's on me. I've cherry-picked this in as 86daffa21c13f46361313120dd49f4bb9118b8d9. Thank you.

**Pull request closed without merging**
