### PR TITLE
Add Option to stop Witch Transformations in Paper Config

### PR DESCRIPTION
**Pull request by TheShermanTanker**

### CODE REVIEW

**Comment by kennytv** [comment]
https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/entity/EntityZapEvent.html this should be done with a plugin

**Comment by TheShermanTanker** [comment]
> 
> 
> https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/entity/EntityZapEvent.html ...

Yes, I am aware of that but I thought it would be nice for users who aren't developers to have that option in the Config by default

**Comment by kennytv** [comment]
Even then, this should also definitely not be disabled by default; this breaks expected behaviour for no apparent reason (also please use spaces instead of tabs and align them with the rest of the code)

**Comment by TheShermanTanker** [comment]
> 
> 
> Even then, this should also definitely not be disabled by default, this breaks expected behaviour for no apparent reason (also, spacing is _still_ bork)

My bad I set it to disabled by default by mistake, will fix

**Comment by kennytv** [comment]
You can edit patches, the readme goes over that process. In this case, you could even hand edit the patch itself, since you don't actually add/remove any lines, you'd just need to replace the boolean and spaces.

**Pull request closed without merging**
