### PR TITLE
Add isCritical to EntityDamageByEntityEvent

### LINKED ISSUE #6752: Add a PlayerCriticalDamageEvent
### Is your feature request related to a problem?

There's no built-in method to check if a player's damage is critical.
 
### Describe the solution you'd like.

Here's an example of what will the event look like
```
@EventHandler
public void onCritical(PlayerCriticalDamageEvent event) {
     if(event.isCritical) {
          event.getPlayer().sendMessage("Critical Damage!!!");
     }
}
```
The event should be cancellable and have ```event.getPlayer()``` ,  ```event.getDamage()``` , ```event.setCritical()``` , and ```event.setDamage()```.

### Describe alternatives you've considered.

I tried making a method like this 
```
public boolean isCritical(Player player) {
     return !player.isOnGround
      && !player.hasPotionEffect(PotionType.BLINDNESS);
}
```
But sometimes it doesn't work or it's not very accurate.

### Other
This event will certainly be handy in some plugins like RPG-Based plugins when you do critical damage it will say "Crit!"

### PR DESCRIPTION
**Pull request by Machine-Maker**
Closes #6752

### CODE REVIEW

**Comment by imDaniX** [comment]
What about #6275?

**Comment by Machine-Maker** [comment]
TBH, I didn’t realize that existed. There are a couple problems with it. I think the isCritical should only be in the EntityDamageByEntity event, not the EntityDamageByBlock event or the EntityDamageEvent base. 

But idrc, whatever people think is better.

**Comment by kennytv** [comment]
Put a "conflict on change" comment on the critical/flag2 boolean

**Comment by Machine-Maker** [comment]
Gonna close this cause the other PR is close enough. Ill comment my suggestions over there, not looking to take credit for smth someone else pretty much already did

**Pull request closed without merging**
