### PR TITLE
Add HalloweenChecker to optimize mob spawns

### PR DESCRIPTION
**Pull request by HexedHero**
Follows up #4947 since sadly it doesn't look like it'll get updated.

Rebased with new packages and 1.17 and did all the requested changes along with some cleanup.
Personally tested on a droplet with fake hardware dates.

Let me know if I fucked anything up/need to change anything.

### CODE REVIEW

**Review by MiniDigger — APPROVED** [review]

**Comment by Spottedleaf** [comment]
Is there any proof for this affecting performance or is it just going to be accepted as-is? I've never seen this show in sparks.

**Comment by MiniDigger** [comment]
@PaulBGD can you chime in here? since this seems the be the 4th PR trying to port your patch, lol https://github.com/TECHNOVE/Airplane/blob/ver/1.17/patches/server/0008-Only-check-for-spooky-season-once-an-hour.patch

**Comment by PaulBGD** [comment]
It's funny that this patch is the one that has been constantly PR'd. It’ll show up in a profiler if you have a lot of chunks and your ticks-per ambient spawns is low. It gets called every time it tries to spawn a bat, so it mostly depends on the setup whether it’ll be effective. My personal opinion though is that Paper doesn't scale very well to the amount of chunks needed for this to be a real issue and most servers have bat spawn frequency pretty low, so it's probably not very effective here anyways.

**Comment by HexedHero** [comment]
> It's funny that this patch is the one that has been constantly PR'd. It’ll show up in a profiler if you have a lot of chunks and your ticks-per ambient spawns is low. It gets called every time it tries to spawn a bat, so it mostly depends on the setup whether it’ll be effective. My personal opinion though is that Paper doesn't scale very well to the amount of chunks needed for this to be a real issue and most servers have bat spawn frequency pretty low, so it's probably not very effective here anyways.

This patch covers the other mobs affected by Halloween time which do have low ticks-per spawn and high caps.

**Comment by Brokkonaut** [comment]
Those should be 2 different checks. the one is halloween season from oct 20 to nov 3 (line 136 of the patch) and the other is halloween only at oct 31 (line 153 and 170 of the patch)

**Comment by PaulBGD** [comment]
> This patch covers the other mobs affected by Halloween time which do have low ticks-per spawn and high caps.

Feel free to show some performance metrics of it then, but I'd be surprised if you could get enough chunks/entity spawning while running Paper on a real server for this to be a serious issue. You'll run into many bottlenecks before this even shows up.

**Pull request closed without merging**
