### PR TITLE
Always allow item changing in EntityFireball

### PR DESCRIPTION
**Pull request by Owen1212055**
Similar to the EntityEnderSignal there is a patch that allows you to set any item. This extends that functionality to EntityFireballFireball as well.

### CODE REVIEW

**Comment by Owen1212055** [comment]
shoo!

**Comment by electronicboy** [comment]
Stalebot be lyk: FITE ME

**Comment by Owen1212055** [comment]
Updated to 1.17

**Comment by Owen1212055** [comment]
rebased

**Review by Machine-Maker — APPROVED** [review]

**Comment by Owen1212055** [comment]
👊

**Review by MiniDigger — APPROVED** [review]
Lgtm
You said there is a path like this already, maybe merge it with that one?

**Comment by Owen1212055** [comment]
It’s a spigot patch I think

**Pull request merged**
